# -*- coding: utf-8 -*-
"""Generate out_012.json through out_016.json from todo files."""
import json
from pathlib import Path

from maps_013 import MAPS_013
from maps_014 import MAPS_014
from maps_015 import MAPS_015
from maps_016 import MAPS_016

DIR = Path(__file__).parent

# Vietnamese key -> English value for each chunk
MAPS = {}

MAPS["012"] = {
    "In thành công": "Printed successfully",
    "Máy in cục bộ (cùng mạng)": "Local printer (same network)",
    "Print Agent không nhận lệnh trong 90 giây.": "Print Agent did not receive the command within 90 seconds.",
    "Kiểm tra Sunmi: Agent BẬT + đã chọn chip máy in + app đang mở.": "Check Sunmi: Agent ON + printer chip selected + app open.",
    "chờ in": "waiting to print",
    "In tem thành công": "Label printed successfully",
    "Chưa cấu hình in cloud / Print Agent": "Cloud print / Print Agent not configured",
    "Agent chưa đăng ký server — bật Agent + chọn chip máy in": "Agent not registered with server — enable Agent + select printer chip",
    "Sunmi native test thất bại": "Sunmi native test failed",
    "Bỏ job cũ để ưu tiên test cloud": "Clear old jobs to prioritize cloud test",
    "Đã in trên máy Agent (claim bỏ qua)": "Printed on Agent device (claim skipped)",
    "HÓA ĐƠN ĐẶT HÀNG": "ORDER INVOICE",
    "PHIẾU GIAO HÀNG": "DELIVERY NOTE",
    "123 Nguyễn Huệ, Q.1, TP.HCM": "123 Nguyen Hue, Dist. 1, HCMC",
    "Anh Hòa Q.1": "Mr. Hoa Dist. 1",
    "Mười sáu triệu đồng chẵn": "Sixteen million dong exactly",
    "NV Bán hàng": "Sales staff",
    "Giày thể thao Nam Adidas Blue": "Men's Adidas Blue sports shoes",
    "Đôi": "Pair",
    "Lần in: 1": "Print copy: 1",
    "PHIẾU CHẾ BIẾN": "KITCHEN TICKET",
    "Mã hàng & barcode": "Item code & barcode",
    "Định mức tồn thấp/cao": "Min/max stock levels",
    "Vị trí & trọng lượng": "Location & weight",
    "Đơn vị / hàng cùng loại": "Unit / variant items",
    "Tính giờ / gói buổi (dịch vụ)": "Hourly / session pack (service)",
    "Tab Mô tả & ghi chú bán": "Description & sales notes tab",
    "Loại hàng cần tạo": "Product type to create",
    "Có tồn kho, biến thể": "Tracked stock, variants",
    "Không trừ tồn kho": "Do not deduct stock",
    "Gói nhiều hàng — trừ tồn thành phần": "Multi-item bundle — deduct component stock",
    "In trực tiếp": "Print directly",
    "Không tạo được PDF": "Could not create PDF",
    "Đơn vừa bán": "Recently sold orders",
    "HÓA ĐƠN BÁN HÀNG IN LẠI": "SALES INVOICE REPRINT",
    "*** Bản in lại — thông báo chủ cửa hàng ***": "*** Reprint — store owner notice ***",
    "Đang gửi lệnh in…": "Sending print command…",
    "Máy in Sunmi (mẫu V2)": "Sunmi printer (V2 template)",
    "Không in được hóa đơn trên máy in cục bộ": "Could not print invoice on local printer",
    "Không in": "Do not print",
    "Tự động sau thanh toán": "Auto after payment",
    "In thủ công (nút Báo kho)": "Manual print (Notify kitchen button)",
    "Không in tem ly": "Do not print cup labels",
    "In thủ công (nút Tem ly)": "Manual print (Cup label button)",
    "Tự in khi báo bếp (+ nút Tem ly)": "Auto when notifying kitchen (+ cup label button)",
    "Tự in khi thanh toán (+ nút Tem ly)": "Auto on payment (+ cup label button)",
    "Giá bán đã bao gồm thuế": "Selling price includes tax",
    "Thuế theo từng mặt hàng": "Tax per line item",
    "Thuế trên tổng đơn hàng": "Tax on order total",
    "PHIẾU KIỂM KHO": "STOCK COUNT SHEET",
    "Kiểm thực tế": "Physical count",
    "Ghi chú:": "Notes:",
    "PHIẾU NHẬP KHO": "STOCK RECEIPT",
    "Người lập phiếu": "Prepared by",
    "Thủ kho": "Warehouse keeper",
    "Mẫu in thử K58": "K58 test print template",
    "Mẫu in thử K80": "K80 test print template",
    "Tiếng Việt: ĂÂÊÔƠƯ Đ": "Vietnamese: ĂÂÊÔƠƯ Đ",
    "SL x Giá": "Qty x Price",
    "125.000 đ": "125,000 VND",
    "PHIẾU XUẤT KHO": "STOCK ISSUE",
    "*** CHƯA THANH TOÁN ***": "*** UNPAID ***",
    "Tổng thành tiền:": "Subtotal:",
    "Chiết khấu:": "Discount:",
    "Thanh toán:": "Paid:",
    "Còn nợ:": "Balance due:",
    "Kiểm tra máy in": "Check printer",
    "Tiếng Việt: Đậu phộng da cá — 35.000 đ": "Vietnamese: Fish-skin peanuts — 35,000 VND",
    "Tự động (khuyến nghị)": "Automatic (recommended)",
    "In ảnh — tiếng Việt chuẩn": "Image print — proper Vietnamese",
    "Không dấu (ASCII)": "Unaccented (ASCII)",
    "nghìn": "thousand",
    "triệu": "million",
    "tỷ": "billion",
    "nghìn tỷ": "trillion",
    "triệu tỷ": "quadrillion",
    "hai triệu … nghìn": "two million … thousand",
    "không trăm": "zero hundred",
    "mốt": "one (after ten)",
    "mười": "ten",
    "lẻ": "odd",
    "không": "zero",
    "bốn": "four",
    "năm": "five",
    "sáu": "six",
    "bảy": "seven",
    "tám": "eight",
    "chín": "nine",
    "Không tải được dữ liệu báo cáo": "Could not load report data",
    "Tùy chọn khác": "More options",
    "Không tạo được file Excel hợp lệ.": "Could not create a valid Excel file.",
    "Ca làm việc, vào sớm, đi trễ, về sớm, tăng ca": "Shifts, early in, late in, early out, overtime",
    "Face ID, GPS, cấp quyền thiết bị, vùng chấm công": "Face ID, GPS, device permissions, check-in zones",
    "Ngày nghỉ lễ, hệ số công, cấu hình lịch nghỉ": "Public holidays, workday factors, leave schedule",
    "Kết nối, quản lý, điều khiển máy chấm công": "Connect, manage, control time clocks",
    "Min/Max nhân sự theo ca, phòng ban, từng thứ T2–CN": "Min/max staff per shift, dept, Mon–Sun",
    "Phụ cấp cố định, phụ cấp ngày công": "Fixed allowances, per workday allowances",
    "Đi trễ, về sớm, tái phạm, kỷ luật": "Late in, early out, repeat offenses, discipline",
    "BHXH, BHYT, BHTN, lương cơ sở": "Social, health, unemployment insurance, base salary",
    "Bậc thuế, giảm trừ gia cảnh": "Tax brackets, personal deductions",
    "Nhóm SP, sản phẩm, đơn giá theo bậc": "Product groups, products, tiered pricing",
    "Người dùng, kích hoạt, vai trò": "Users, activation, roles",
    "Ma trận quyền, vai trò, module": "Permission matrix, roles, modules",
    "Giờ kết thúc ngày, tham số vận hành": "End-of-day time, operational parameters",
    "Quản lý chi nhánh, cây chi nhánh, thống kê": "Branch management, branch tree, statistics",
    "K58, K80, A5, A4 — thiết kế hóa đơn, phiếu": "K58, K80, A5, A4 — invoice & slip design",
    "Hồ sơ ngành, bàn/ghế, tính giờ, gói buổi": "Industry profile, tables/seats, hourly, session packs",
    "Tên, địa chỉ, VAT, VietQR thanh toán": "Name, address, VAT, VietQR payment",
    "In hoá đơn, Bluetooth/LAN/USB, tem ly": "Invoice print, Bluetooth/LAN/USB, cup labels",
    "Sơ đồ mặt bằng, tạo/sửa bàn ghế": "Floor plan, create/edit tables",
    "Gemini, bật/tắt AI": "Gemini, enable/disable AI",
    "Đi trễ - Về sớm": "Late in - Early out",
    "đi trễ từng ca không\n/// gộp chung lại 1 ngày": "late per shift not\n/// merged into one day",
    "Chưa xếp ca": "No shift assigned",
    "GPS: chưa có": "GPS: unavailable",
    "SBOX HRM · Ảnh hiện trường": "SBOX HRM · On-site photo",
    "Tăng ca trưa": "Midday overtime",
    "Giờ cố định": "Fixed hours",
    "LHT ÷ công chuẩn ÷ 8h": "Contract salary ÷ standard days ÷ 8h",
    "(LCB + LHT) ÷ công chuẩn ÷ 8h": "(Base + contract) ÷ standard days ÷ 8h",
    "LCB ÷ công chuẩn ÷ 8h": "Base salary ÷ standard days ÷ 8h",
    "áº": "áº",
    "Trợ lý AI – Thông tin quyền riêng tư": "AI Assistant – Privacy notice",
    "Khi sử dụng trợ lý AI, nội dung câu hỏi và dữ liệu nhân sự liên quan (ca làm việc, phép, chấm công)": "When using the AI assistant, your questions and related HR data (shifts, leave, attendance)",
    "sẽ được gửi đến máy chủ của chúng tôi và xử lý bằng Google Gemini AI để tạo phản hồi.": "will be sent to our server and processed by Google Gemini AI to generate responses.",
    "Dữ liệu sinh trắc học (khuôn mặt, vân tay) không được gửi đến AI.": "Biometric data (face, fingerprint) is not sent to AI.",
    "Bạn đồng ý để tiếp tục sử dụng tính năng này không?": "Do you agree to continue using this feature?",
    "Không đồng ý": "Decline",
    "Micro chưa sẵn sàng": "Microphone not ready",
    "Vui lòng cấp quyền micro và thử lại": "Please grant microphone permission and try again",
    "Lỗi trợ lý AI": "AI assistant error",
    "⚠️ Thiếu ngày hoặc giờ để tạo phiếu.": "⚠️ Missing date or time to create request.",
    "✅ Đã tạo yêu cầu sửa giờ thành công!": "✅ Time correction request created!",
    "Trạng thái: Đang chờ duyệt.": "Status: Pending approval.",
    "Đã tạo yêu cầu sửa giờ thành công. Đang chờ duyệt.": "Time correction request created. Pending approval.",
    "✅ Mở form xin nghỉ phép": "✅ Open leave request form",
    "✅ Mở form ứng lương": "✅ Open salary advance form",
    "✅ Mở form phản ánh": "✅ Open feedback form",
    "✅ Mở đăng ký ăn": "✅ Open meal registration",
    "✅ Mở form tăng ca": "✅ Open overtime form",
    "✅ Mở form đổi ca": "✅ Open shift swap form",
    "✅ Mở hồ sơ công tác mới": "✅ Open new business trip record",
    "✅ Mở bản đồ / công tác": "✅ Open map / business trip",
    "✅ Xác nhận tạo": "✅ Confirm create",
    "Xem nghỉ phép": "View leave",
    "+ Thêm phiếu nghỉ": "+ Add leave request",
    "+ Đổi ca": "+ Swap shift",
    "Phiếu sửa giờ": "Time correction",
    "+ Sửa giờ / Quên chấm": "+ Fix time / Missed punch",
    "+ Gửi phản ánh": "+ Send feedback",
    "Bảng tin": "News feed",
    "+ Thêm phiếu ứng lương": "+ Add salary advance",
    "Tăng ca / OT": "Overtime / OT",
    "+ Đăng ký tăng ca": "+ Register overtime",
    "Đi công tác": "Business trip",
    "+ Tạo phiếu công tác": "+ Create business trip",
    "Đăng ký ăn": "Meal registration",
    "KPI cá nhân": "Personal KPI",
    "Giao dịch quỹ": "Fund transactions",
    "+ Hồ sơ công tác": "+ Business trip record",
    "BC nghỉ phép": "Leave report",
    "BC ứng lương": "Advance report",
    "BC công tác phí": "Travel expense report",
    "Xem hướng dẫn": "View guide",
    "Trợ lý ảo HRM": "HRM virtual assistant",
    "Hỗ trợ nghỉ phép, lịch làm, chấm công, lương": "Help with leave, schedule, attendance, payroll",
    "Tắt đọc": "Turn off read-aloud",
    "Bật đọc": "Turn on read-aloud",
    "Đang suy nghĩ...": "Thinking...",
    "Dừng ghi âm": "Stop recording",
    "Nói": "Speak",
    "Đang nghe...": "Listening...",
    "Hỏi trợ lý (VD: \"Còn bao nhiêu phép?\")": "Ask assistant (e.g. \"How much leave left?\")",
    "Ngắn gọn": "Concise",
    "Đồng cảm": "Empathetic",
    "Vui lòng mô tả điều bạn muốn AI viết": "Please describe what you want AI to write",
    "Không tạo được nội dung": "Could not generate content",
    "Mô tả nội dung muốn AI viết *": "Describe content for AI to write *",
    "VD: Phản ánh về bữa trưa hôm nay ít rau...": "E.g. Feedback about today's lunch lacking vegetables...",
    "Tạo nội dung": "Generate content",
    "Tạo lại": "Regenerate",
    "Kết quả AI": "AI result",
    "Nối vào": "Append",
    "Nhập mô tả ngắn về điều bạn muốn viết, AI sẽ soạn giúp bạn bằng tiếng Việt.": "Enter a short description; AI will draft it in Vietnamese for you.",
    "AI soạn thảo": "AI drafting",
    "gọi ngay": "call now",
    "liên hệ gia hạn": "contact to renew",
    "Liên hệ gia hạn ngay": "Contact to renew now",
    "Mở liên kết": "Open link",
    "Tôi đã đọc": "I have read",
    "Chi tiết lỗi (gửi ảnh màn hình này cho IT):": "Error details (send this screenshot to IT):",
    "Đóng app hoàn toàn rồi mở lại. Nếu lỗi lặp lại, chụp màn hình này và báo quản trị.": "Force close the app and reopen. If it persists, screenshot this and notify admin.",
    "thấy nút nhưng kích không được": "button visible but not clickable",
    "Lý do bổ sung": "Additional reason",
    "Lý do chỉnh sửa": "Edit reason",
    "Lý do xóa": "Deletion reason",
    "Điền mẫu": "Fill template",
    "Chọn gợi ý hoặc chỉnh sửa nội dung bên dưới": "Pick a suggestion or edit the text below",
    "Nhập lý do hoặc chọn gợi ý phía trên": "Enter a reason or pick a suggestion above",
    "Quên chấm công / máy không ghi nhận": "Missed punch / device did not record",
    "Sự cố thiết bị hoặc mất điện": "Device failure or power outage",
    "Công tác / họp ngoài — bổ sung theo xác nhận quản lý": "Business trip / off-site meeting — per manager confirmation",
    "Điều chỉnh theo đơn tờ / giấy phép đã duyệt": "Adjust per approved form / permit",
    "Ca qua đêm — điều chỉnh ngày hoặc giờ chấm": "Overnight shift — adjust date or punch time",
    "Quên chấm công — bổ sung giờ vào/ra": "Missed punch — add in/out time",
    "Máy chấm công không ghi nhận": "Time clock did not record",
    "Ca qua đêm — điều chỉnh giờ chấm": "Overnight shift — adjust punch time",
    "Chấm công trùng / nhầm lần": "Duplicate / mistaken punch",
    "Ghi nhận sai người hoặc sai giờ": "Wrong person or wrong time recorded",
    "Theo yêu cầu điều chỉnh sau khi duyệt": "Per approved adjustment request",
    "Bạn có chắc muốn xóa lần chấm công này? (áp dụng ngay)": "Delete this punch? (applies immediately)",
    "Bạn có chắc muốn yêu cầu xóa lần chấm công này?": "Request deletion of this punch?",
    "Vui lòng chọn gợi ý hoặc nhập lý do xóa": "Pick a suggestion or enter deletion reason",
    "Trình duyệt chưa cấp quyền camera.\nVui lòng cho phép truy cập camera và thử lại.": "Browser has not granted camera access.\nPlease allow camera and try again.",
    "Không tìm thấy camera.\nVui lòng kiểm tra thiết bị camera.": "No camera found.\nPlease check your camera device.",
    "Camera đang được sử dụng bởi ứng dụng khác.": "Camera is in use by another app.",
    "Quay mặt sang TRÁI": "Turn face LEFT",
    "Quay mặt sang PHẢI": "Turn face RIGHT",
    "Cần bật quyền Camera cho SBOX HRM.": "Enable Camera permission for SBOX HRM.",
    "Vào Cài đặt > Ứng dụng > SBOX HRM > Quyền > Camera → Cho phép.": "Go to Settings > Apps > SBOX HRM > Permissions > Camera → Allow.",
    "Cần cấp quyền camera để đăng ký khuôn mặt.": "Camera permission required for face enrollment.",
    "Nhấn «Thử lại» hoặc cấp quyền khi hệ thống hỏi.": "Tap «Retry» or grant permission when prompted.",
    "Không tìm thấy camera nào.": "No camera found.",
    "Không phát hiện khuôn mặt": "No face detected",
    "Ảnh chưa nhìn thẳng — giữ mặt vuông với camera": "Face not straight — keep face square to camera",
    "Ảnh chưa quay trái đủ — thử lại bước này": "Not turned left enough — retry this step",
    "Ảnh chưa quay phải đủ — thử lại bước này": "Not turned right enough — retry this step",
    "Ảnh chưa ngẩng lên đủ — thử lại bước này": "Not looking up enough — retry this step",
    "Ảnh chưa cúi xuống đủ — thử lại bước này": "Not looking down enough — retry this step",
    "Tư thế chưa đúng — thử lại bước này": "Pose incorrect — retry this step",
    "Giữ nguyên — đủ sáng, máy ổn định...": "Hold still — good light, steady device...",
    "Quay mặt sang phải thêm": "Turn face more to the right",
    "Quay mặt sang trái thêm": "Turn face more to the left",
    "Cúi mặt xuống thêm": "Look down more",
    "Ngẩng mặt lên thêm": "Look up more",
    "Quay mặt sang trái nhiều hơn": "Turn face further left",
    "Quay mặt sang phải nhiều hơn": "Turn face further right",
    "Ngẩng mặt lên cao hơn": "Look up higher",
    "Cúi mặt xuống thấp hơn": "Look down lower",
    "Tải nhân viên từ máy": "Load employees from device",
    "Tải chấm công từ máy": "Load attendance from device",
    "Máy có thể chỉ gửi lại log cũ (trùng). Thử khởi động lại máy SANA hoặc chấm thử 1 lần;": "Device may resend old logs (duplicates). Try restarting the SANA device or test one punch;",
    "hệ thống sẽ tự đồng bộ lại mỗi ~2 phút.": "system will auto-sync again every ~2 minutes.",
    "Máy có thể chậm hoặc log mới chưa được đẩy lên.": "Device may be slow or new logs not pushed yet.",
    "Gửi lệnh thất bại": "Command failed",
    "Chờ máy gửi dữ liệu...": "Waiting for device to send data...",
    "Lệnh đồng bộ thất bại": "Sync command failed",
    "Trên máy": "On device",
    "Server trước": "Previous server",
    "Server hiện": "Current server",
    "Chưa lên server": "Not on server yet",
    "Tìm tên, mã NV, phòng ban, SĐT...": "Search name, emp. code, dept, phone...",
    "Đã xảy ra lỗi": "An error occurred",
    "Chưa có dữ liệu nào được thêm vào": "No data added yet",
    "Không tìm thấy kết quả": "No results found",
    "Không có kết quả phù hợp với tiêu chí tìm kiếm": "No results match your search",
    "Quay đầu sang trái": "Turn head left",
    "Quay đầu sang phải": "Turn head right",
    "Nháy mắt": "Blink",
    "Mỉm cười": "Smile",
    "Đang phân tích khuôn mặt...": "Analyzing face...",
    "Đang xác thực...": "Verifying...",
    "Xác thực thành công!": "Verification successful!",
    "Không nhận diện được. Thử lại.": "Not recognized. Try again.",
    "Bắt đầu xác thực": "Start verification",
    "Cần bật Camera trong Cài đặt > SBOX HRM > Quyền": "Enable Camera in Settings > SBOX HRM > Permissions",
    "Cần cấp quyền camera": "Camera permission required",
    "Đang nhận dạng khuôn mặt...": "Recognizing face...",
    "Đang so sánh khuôn mặt (AI)...": "Comparing face (AI)...",
    "Không trích xuất được đặc trưng khuôn mặt. Vui lòng thử lại với ánh sáng tốt hơn.": "Could not extract face features. Try again with better lighting.",
    "Không thể chụp ảnh xác thực.": "Could not capture verification photo.",
    "Lỗi khởi tạo nhận diện trên máy (iOS)": "On-device recognition init error (iOS)",
    "Không nạp được TFLite MobileFaceNet trên thiết bị.": "Could not load TFLite MobileFaceNet on device.",
    "Sẽ chuyển sang xác thực qua server. Vui lòng gửi log này cho kỹ thuật:": "Will switch to server verification. Send this log to support:",
    "Đã copy lỗi vào clipboard": "Error copied to clipboard",
    "Copy lỗi": "Copy error",
    "Tiếp tục (dùng server)": "Continue (use server)",
    "Xác thực khuôn mặt": "Face verification",
    "Nhìn thẳng vào camera và giữ nguyên": "Look straight at camera and hold still",
    "Huỷ bỏ": "Cancel",
    "Mở Cài đặt": "Open Settings",
    "Chạm để xem chi tiết": "Tap for details",
    "Chạm để xem / chỉnh sửa": "Tap to view / edit",
    "tổng kết nhanh": "quick summary",
    "Xem trước ảnh sẽ được sử dụng": "Preview photo to be used",
    "Sử dụng ảnh": "Use photo",
    "Tỉ lệ 1:1 (vuông)": "1:1 ratio (square)",
    "Tỉ lệ thẻ CCCD": "ID card ratio",
    "Tỉ lệ tự do": "Free ratio",
    "Không mở được tệp đính kèm": "Could not open attachment",
    "Trình phát trực tiếp hiện hỗ trợ trên bản web.": "Live player is currently supported on web.",
    "Chưa có quỹ phép năm (gắn hồ sơ lương trong Thiết lập lương).": "No annual leave balance (link payroll profile in Payroll setup).",
    "Chọn nhóm loại nghỉ": "Select leave category group",
    "Chọn loại nghỉ cụ thể": "Select specific leave type",
    "Sửa đơn nghỉ phép": "Edit leave request",
    "Bước 1 — Chọn nhóm chế độ": "Step 1 — Select pay category group",
    "Mỗi ngày nghỉ chỉ áp dụng một chế độ chi trả.": "Each leave day uses only one pay category.",
    "Chọn nhóm loại nghỉ ở bước trước": "Select leave group in previous step",
    "Ca nghỉ": "Leave shift",
    "Người thay ca (tùy chọn)": "Cover person (optional)",
    "Giấy nghỉ / hồ sơ BHXH": "Medical leave / social insurance file",
    "Số seri giấy nghỉ, mã hồ sơ BHXH…": "Leave slip serial, SI file code…",
    "Bắt buộc với chế độ BHXH": "Required for SI category",
    "Mô tả ngắn gọn lý do nghỉ…": "Brief reason for leave…",
    "Không ghi \"Phép\" trên chấm công": "Do not mark \"Leave\" on attendance",
    "Duyệt luôn khi tạo": "Approve on create",
    "0.5 công / ngày": "0.5 workday / day",
    "Chọn nhân viên trước.": "Select employee first.",
    "Chưa gắn ca trong Thiết lập lương.": "No shift linked in Payroll setup.",
    "Chọn người thay ca": "Select cover person",
    "Quy định nghỉ phép (tóm tắt)": "Leave policy (summary)",
    "• DN trả lương: phép năm, lễ, VR có lương, nghỉ bù, ốm dùng phép năm.": "• Employer paid: annual leave, holidays, paid personal leave, comp leave, sick using annual leave.",
    "• Không lương: VR không lương, nghỉ dài hạn không lương.": "• Unpaid: unpaid personal leave, long-term unpaid leave.",
    "• BHXH: ốm hưởng BHXH, thai sản — cần giấy tờ, không trùng lương DN cùng ngày.": "• SI: sick with SI, maternity — documents required, no employer pay same day.",
    "• Mỗi ngày chỉ một chế độ.": "• One category per day only.",
    "• Ca nghỉ theo Thiết lập lương; người thay ca cùng phòng ban.": "• Leave shift per Payroll setup; cover same department.",
    "Chọn loại nghỉ": "Select leave type",
    "Chọn ít nhất một ca": "Select at least one shift",
    "Đã cập nhật đơn": "Request updated",
    "Đã gửi đơn nghỉ phép": "Leave request submitted",
    "Không rõ nguyên nhân": "Unknown cause",
    "Độ chính xác thấp": "Low accuracy",
    "Bạn đã từ chối quyền truy cập vị trí.\nVui lòng cho phép trong cài đặt trình duyệt.": "You denied location access.\nPlease allow it in browser settings.",
    "Không thể xác định vị trí.\nVui lòng thử lại.": "Could not determine location.\nPlease try again.",
    "Hết thời gian chờ xác định vị trí.\nVui lòng thử lại.": "Location request timed out.\nPlease try again.",
    "Lỗi vị trí": "Location error",
    "Nhấn vào bản đồ để chọn vị trí chấm công": "Tap map to select check-in location",
    "Giờ chấm công đã được sửa": "Punch time updated",
    "Không thể sửa giờ chấm": "Could not update punch time",
    "Xóa bản ghi chấm công": "Delete attendance record",
    "Bản ghi chấm công liên kết (nếu có) cũng sẽ bị xóa.": "Linked attendance records (if any) will also be deleted.",
    "Bản ghi chấm công đã được xóa": "Attendance record deleted",
    "Không thể xóa bản ghi": "Could not delete record",
    "Chưa có ảnh hiện trường — chụp khi chấm công": "No on-site photo — capture when checking in",
    "Điểm chấm công": "Check-in point",
    "Tọa độ GPS": "GPS coordinates",
    "Khoảng cách": "Distance",
    "Độ khớp khuôn mặt": "Face match score",
    "Bản ghi không có tọa độ GPS hợp lệ (có thể do tắt định vị khi chấm).": "Record has no valid GPS (location may have been off when punching).",
    "Đã lưu bố cục thanh công cụ": "Toolbar layout saved",
    "Tùy chỉnh thanh công cụ": "Customize toolbar",
    "5 vị trí cố định — kéo để đổi thứ tự, chạm để đổi chức năng.": "5 fixed slots — drag to reorder, tap to change action.",
    "Mặc định: Trang chủ · Tổng quan · Chấm công · Công việc · Thêm.": "Default: Home · Overview · Attendance · Tasks · More.",
    "Tùy chỉnh truy cập nhanh (tab Thêm)": "Customize quick access (More tab)",
    "Vị trí giữa — nút nổi (Chấm công)": "Center slot — floating button (Attendance)",
    "Đã lưu truy cập nhanh": "Quick access saved",
    "Tùy chỉnh truy cập nhanh": "Customize quick access",
    "9 ô trong tab «Thêm» — kéo đổi thứ tự, chạm để đổi chức năng.": "9 slots in «More» tab — drag to reorder, tap to change action.",
    "Bạn không có quyền truy cập": "You do not have access",
    "Quét mã vạch / QR": "Scan barcode / QR",
    "Tắt đèn": "Turn off light",
    "Bật đèn": "Turn on light",
    "Đưa mã vào tâm khung — chạm màn hình để lấy nét. Ưu tiên quét cứng Sunmi nếu có.": "Center code in frame — tap screen to focus. Prefer Sunmi hardware scan if available.",
    "Đưa mã vào tâm khung · chạm màn hình để lấy nét nhanh hơn": "Center code in frame · tap screen to focus faster",
    "Chạm để phóng to": "Tap to zoom",
    "Báo cáo lương chỉ hiển thị nhân viên đã gán bảng lương.": "Payroll report shows only employees with assigned payroll.",
    "Vào Hồ sơ nhân sự → Thiết lập lương để cấu hình trước khi xem báo cáo.": "Go to HR profile → Payroll setup before viewing report.",
    "Chưa có dữ liệu tổng hợp lương": "No payroll summary data",
    "Hãy thiết lập lương trước — sau đó báo cáo mới tính được lương và xuất Excel.": "Set up payroll first — then report can calculate pay and export Excel.",
    "Không có nhân viên phù hợp bộ lọc hoặc khoảng thời gian đã chọn.": "No employees match filter or selected period.",
    "Mở Thiết lập lương": "Open Payroll setup",
    "Nhập nội dung HTML...": "Enter HTML content...",
    "<!-- Nhập mã HTML tại đây -->": "<!-- Enter HTML code here -->",
    "Đậm (Ctrl+B)": "Bold (Ctrl+B)",
    "Nghiêng (Ctrl+I)": "Italic (Ctrl+I)",
    "Gạch chân (Ctrl+U)": "Underline (Ctrl+U)",
    "Danh sách gạch đầu dòng": "Bullet list",
    "Danh sách đánh số": "Numbered list",
    "Danh sách kiểm tra": "Checklist",
    "Trích dẫn": "Quote",
    "Khối code": "Code block",
    "Đường kẻ ngang": "Horizontal rule",
    "Căn đều": "Justify",
    "Chèn nút": "Insert button",
    "Màu chữ": "Text color",
    "Màu nền chữ": "Text background color",
    "Hoàn tác (Ctrl+Z)": "Undo (Ctrl+Z)",
    "Làm lại (Ctrl+Y)": "Redo (Ctrl+Y)",
    "Xóa định dạng": "Clear formatting",
    "Soạn thảo trực quan": "Visual editor",
    "Xem mã HTML": "View HTML code",
    "Kiểu đề mục": "Heading style",
    "Đoạn văn": "Paragraph",
    "Tiêu đề 1": "Heading 1",
    "Tiêu đề 2": "Heading 2",
    "Tiêu đề 3": "Heading 3",
    "Tiêu đề 4": "Heading 4",
    "Cỡ chữ": "Font size",
    "Rất nhỏ": "Extra small",
    "Nhỏ": "Small",
    "Vừa": "Medium",
    "Lớn": "Large",
    "Rất lớn": "Extra large",
    "Cực lớn": "Huge",
    '<li style="margin:4px 0"><input type="checkbox" style="margin-right:8px;cursor:pointer;width:16px;height:16px;vertical-align:middle"/>Mục 1</li>': '<li style="margin:4px 0"><input type="checkbox" style="margin-right:8px;cursor:pointer;width:16px;height:16px;vertical-align:middle"/>Item 1</li>',
    '<li style="margin:4px 0"><input type="checkbox" style="margin-right:8px;cursor:pointer;width:16px;height:16px;vertical-align:middle"/>Mục 2</li>': '<li style="margin:4px 0"><input type="checkbox" style="margin-right:8px;cursor:pointer;width:16px;height:16px;vertical-align:middle"/>Item 2</li>',
    '<li style="margin:4px 0"><input type="checkbox" style="margin-right:8px;cursor:pointer;width:16px;height:16px;vertical-align:middle"/>Mục 3</li>': '<li style="margin:4px 0"><input type="checkbox" style="margin-right:8px;cursor:pointer;width:16px;height:16px;vertical-align:middle"/>Item 3</li>',
    "Văn bản hiển thị": "Display text",
    "Nhập văn bản...": "Enter text...",
    "Upload ảnh": "Upload image",
}

def write_chunk(num: str, mapping: dict) -> int:
    todo_path = DIR / f"todo_{num}.json"
    out_path = DIR / f"out_{num}.json"
    keys = json.loads(todo_path.read_text(encoding="utf-8"))
    missing = [k for k in keys if k not in mapping]
    if missing:
        print(f"out_{num}: MISSING {len(missing)} keys")
        for k in missing[:5]:
            print(f"  - {k[:80]}")
    out = {k: mapping.get(k, f"[UNTRANSLATED] {k}") for k in keys}
    out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"out_{num}.json: {len(out)} keys written")
    return len(out)

if __name__ == "__main__":
    MAPS["013"] = MAPS_013
    MAPS["014"] = MAPS_014
    MAPS["015"] = MAPS_015
    MAPS["016"] = MAPS_016
    total = 0
    for num in ("012", "013", "014", "015", "016"):
        total += write_chunk(num, MAPS[num])
    print(f"TOTAL: {total} keys")
