T = [
    "Enable Agent and select at least one printer chip below",
    "Agent registration failed",
    "Job is being processed",
    "Job missing printerId",
    "Agent does not serve this printer — reselect printer chip",
    "Print exceeded 45 seconds — check paper / Sunmi device",
    "Printing document…",
    "Printer configuration not found",
    "SaleOrderJson is not an object",
    "SaleOrderJson job requires Sunmi as Agent",
    "Unable to load order for Sunmi print",
    "KitchenSlipJson is not an object",
    "KitchenSlipJson job requires Sunmi as Agent",
    "Kitchen slip has no items",
    "Kitchen slip has no valid items",
    "TestPrintJson job requires Sunmi as Agent",
    "Invalid payload",
    "Unable to send data to printer",
    "Print failed on agent",
    "HRM Settings sidebar module order and display",
    "Notification from SBOX HRM",
    "Device connected",
    "Device disconnected",
    "Absent day (no approved leave). Choose action:",
    "Manually add in/out times",
    "Create leave slip",
    "Add leave request for this day",
    "Create unauthorized leave penalty slip",
    "Employee not found in HR system",
    "Employee not found to create penalty slip",
    "Penalty amount",
    "Invalid penalty amount",
    "Unauthorized leave recorded",
    "Failed to create penalty slip",
    "Unable to update agent",
    "Server returned no confirmation data — please reload list",
    "Server reported success but store still has agent — please reload",
    "Server reported success but store could not assign agent — please reload",
    "Unable to assign license",
    "Server returned no license data — please reload",
    "No license assigned to agent",
    "Server reported success but license not assigned — please reload",
    "Account does not have permission for this action.",
    "Account does not have permission to create this slip type.",
    "connection lost",
    "no network",
    "UI overloaded",
    "Display error occurred. Fully close app (swipe from multitasking) then reopen.",
    "Network connection lost",
    "Cannot connect to server. Please enable Wi‑Fi or 4G and retry.",
    "Server not responding",
    "Request timed out with no response. Check network and retry.",
    "Server is experiencing issues. Please try again later.",
    "Application error",
    "An unexpected error occurred. Please retry or reopen the app.",
    "broken",
    "maintenance",
    "in use",
    "Loading devices and configuration...",
    "Loading leave, salary, leave balance...",
    "Attendance record not found. Check PIN/time or reload data and retry.",
    "Employee account not found.",
    "Attendance approval slip not found.",
    "Save error when deleting attendance (linked to shift/meal/penalty). Reload page and retry.",
    "Request failed. Please retry.",
    "Applied (auto-approved). Open Attendance Approval → All or Approved → filter Delete action.",
    "Request sent — pending approval (account lacks self-approve permission)",
    "Attendance request sent successfully",
    "Loading page 1...",
    "Advance pending approval",
    "Advance approved",
    "Advance disbursed",
    "Settlement draft",
    "Settlement pending approval",
    "Settlement approved",
    "Final settlement",
    "Link setup → Cloud server",
    "Date of birth (dd/MM/yyyy)",
    "Education level",
    "Marital status",
    "Permanent address",
    "Rank",
    "Start date (dd/MM/yyyy)",
    "Account no.",
    "Bank account name",
    "Downloaded file is empty.",
    "Server returned web page instead of Excel file. Please log in again.",
    "Server returned JSON instead of Excel file.",
    "Use camera to capture",
    "Choose existing photo on device",
    "Software registration",
    "Path: sboxhrm.com → Register",
    "Store login code: max 20 chars, lowercase a–z and 0–9",
    "Receive store code (Store ID) after successful registration",
    "Log in to web/app with store code + admin account",
    "Use real email and phone for fast activation support.",
    "Go to HR Profiles to create employee list: add individually or import Excel. Assign department, position, employee ID before scheduling and syncing time clock.",
    "Menu: HR Profiles",
    "Add manually or import Excel (download template on screen)",
    "Assign department, position, employee ID",
    "Update base salary in Salary Settings (next step)",
    "Excel import helps bulk-add employees faster than manual entry.",
    "Shift configuration",
    "Create shifts at Settings → Shift Settings. Then go to Work Schedule to assign shifts per employee or department.",
    "Settings → Shift Settings: create morning/afternoon/night, rotating shifts",
    "Work Schedule menu: assign by day/week/month",
    "Supports overnight and weekly rotating schedules",
    "Approve schedule at Schedule Approval (if approval workflow enabled)",
    "Use \"Duplicate shift\" to quickly create similar shift without re-entering.",
    "Configure salary per employee and payroll policies: allowances, penalties, insurance, PIT. View Payroll Summary and Payslips at period end.",
    "HR Profiles → Salary Settings: base salary per employee",
    "Settings → Allowances, Penalties, Insurance, PIT Tax",
    "Reports → Payroll Summary: payroll by period",
    "Employees view Payslip on app",
    "Set late/early penalty policy before running attendance.",
    "Two-sided setup: on ZKTeco device enter ADMS cloud server; in software add device serial and monitor online status.",
    "In software: Settings → Time clock → Add device (SN or scan code)",
    "Online device appears automatically, attendance syncs real-time",
    "Cannot connect? Call hotline 0973 024 042 — remote support via Zalo.",
    "Employee clock-in & fingerprint",
    "Sync employees from profiles to time clock, then enroll fingerprint or face on ZKTeco device.",
    "Menu: Attendance personnel",
    "Sync employee list from HR Profiles to device",
    "Enroll fingerprint / face on ZKTeco device",
    "Check Raw Attendance to confirm in/out logs",
    "Employee ID on device must match profile ID for accurate sync.",
    "Mobile attendance & approval",
    "Enable phone clock-in (GPS, WiFi, Face ID). Employees register devices; managers approve at Attendance Approval.",
    "Settings → Mobile attendance: GPS, WiFi, clock-in zones",
    "Menu: Mobile Attendance Registration",
    "Employees clock in at Mobile Attendance menu",
    "Managers approve at Attendance Approval",
    "Enable store WiFi/GPS to prevent out-of-zone clock-in.",
    "System auto-generates penalty slips from attendance or create manually at Finance → Penalty Slips.",
    "Settings → Penalties: late, early leave, repeat offense rates",
    "Finance → Penalty Slips",
    "Approve / cancel / reject slips per workflow",
    "Cancelled or rejected slips excluded from reports.",
    "Create salary advance slip",
    "Employees submit advance requests on app; managers approve at Finance → Salary Advance.",
    "Finance → Salary Advance: create & approve slips",
    "Employees create requests on mobile app",
    "Track amount advanced and remaining debt",
    "Reports → Salary Advance Report",
    "When disbursing advance via Cash Flow, system auto-updates slip status.",
    "Create bonus slip",
    "Record bonuses at Finance → Bonus Slips. Bonus amount included in corresponding payroll period.",
    "Create bonus slip by employee, period, reason",
    "Approve slip before payroll calculation",
    "Shown in Payroll Summary",
    "Create bonus slips before monthly payroll finalization.",
    "Record cash fund income/expense at Finance → Cash Flow. Link advance and penalty slips on actual receipt/payment.",
    "Finance → Cash Flow: record income, expense by date",
    "Link advance slip when disbursing",
    "Link penalty slip when collecting penalty",
    "Reports → Cash Flow Report",
    "Recording on correct date helps reconcile fund and reports accurately.",
    "Reports",
    "All reports in Reports menu: attendance, penalties, advances, cash flow, leave, assets.",
    "Attendance summary · Shift summary",
    "Payroll Summary (Payroll menu)",
    "Penalty · Advance · Cash flow · Leave · Asset reports",
    "Cancelled/rejected slips excluded from advance, penalty and leave reports.",
    "Assign shifts, swap shifts and track schedules by week/month per employee or department.",
    "Menu: Work Schedule",
    "Assign shifts by day, week, month",
    "Employees submit swap requests at Shift Swap",
    "Managers approve at Schedule Approval",
    "Assign shifts before period start for accurate attendance and payroll.",
    "Set KPI targets, assign evaluation tasks and track results by period per employee/department.",
    "Menu: KPI (Operations Management)",
    "Create targets, achievement levels and weights",
    "Record actual results by period",
    "Used in performance evaluation and bonuses",
    "Link KPI to bonus slips to automate achievement recording.",
    "Manage periodic, spot and KPI bonuses — integrated into payroll.",
    "Create by employee, period, bonus type",
    "Approve before Payroll Summary finalization",
    "Review in Payroll Summary",
    "Only approved bonuses added to payslip.",
    "Employees create leave requests on app; managers approve/reject. System deducts annual leave and reflects in attendance.",
    "Menu: Leave",
    "Employees create request with reason and dates",
    "Managers approve / reject / cancel slips",
    "Reports → Leave Report",
    "Rejected or cancelled slips excluded from leave report.",
    "Configure late, early, repeat offense penalties and auto penalty slips from attendance.",
    "Settings → Penalties: rules and amounts",
    "Finance → Penalty Slips: auto & manual",
    "Collect penalties via Cash Flow (link slip)",
    "Set late minute thresholds before going live.",
    "Enter output by product group, shift or employee for piece-rate/product payroll.",
    "Menu: Output (Operations Management)",
    "Settings → Product pay: product groups, unit rates",
    "Enter output by day/shift",
    "Payroll Summary auto-adds product pay portion",
    "Declare tiered unit rates before bulk output entry.",
    "Manage company assets and equipment: assign, reclaim, warranty and track holder.",
    "Menu: Assets (Operations Management)",
    "Add asset, code, purchase date, warranty",
    "Assign asset to employee/department",
    "Reports → Asset Report",
    "Record warranty expiry date for advance reminders.",
    "Post internal news, announcements, policies and newsletters to all or employee groups.",
    "Menu: Communications",
    "Create posts, pin important news",
    "Send push notifications to employee app",
    "Employees view on Dashboard and Communications",
    "Use communications to announce new attendance and payroll policies.",
    "Feedback / Complaints",
    "Receive anonymous or public employee feedback; managers respond and track resolution.",
    "Menu: Feedback / Opinions",
    "Employees submit feedback from app (anonymous or named)",
    "Managers view, reply and close tickets",
    "Track resolved / pending status",
    "Encourage anonymous feedback for honest team input.",
    "Record meal servings / meal attendance by shift or day for meal cost control.",
    "Menu: Meal attendance",
    "Configure meals per shift (if applicable)",
    "Employee or manager records meals",
    "Monthly reconciliation with HR reports",
    "Link meal attendance to shifts to avoid duplicate recording.",
    "Create employee account",
    "Create app/web login for employees, assign permissions and link to HR profile.",
    "Settings → Accounts",
    "Add account, select matching HR employee",
    "Assign role at Settings → Permissions",
    "Employees log in with store code + assigned account",
    "Each employee should have own account, no shared passwords.",
    "Tap to view",
    "Device attendance",
    "Attendance summary",
    "Rewards & penalties",
    "Production",
    "New notification",
    "at",
    "notification",
    "new notification",
    "Salary",
    "Meal serving",
    "Workday adjustment",
    "leave request",
    "business trip advance",
    "travel allowance",
    "travel expense accounting",
    "travel document supplement",
    "business trip",
    "advance disbursement",
    "request",
    "penalty slip",
    "output",
    "import output",
    "kpi salary",
    "income transaction",
    "feedback",
    "opinion",
    "on-site",
    "shift swap",
    "shift exchange",
    "schedule registration",
    "schedule approval",
    "revert schedule approval",
    "work schedule",
    "delete work schedule",
    "work shift",
    "new shift",
    "attendance edit",
    "workday adjustment",
    "device registration",
    "device change",
    "attendance device",
    "field clock-in",
    "field pending approval",
    "mobile attendance",
    "need",
    "time clock",
    "time clock device",
    "task",
    "message",
    "post",
    "internal announcement",
    "allowance",
    "benefits",
    "rewards & penalties",
    "payroll",
    "payslip",
    "new profile",
    "department",
    "account",
    "menu",
    "meal serving",
    "meal",
    "new attendance device registration",
    "device change request",
    "report",
    "registration submitted",
    "device registration approved",
    "device registration rejected",
    "device change request sent",
    "you can clock in",
    "rejected",
    "new feedback",
    "Overview (legacy)",
    "Real-time attendance",
    "Absent employees",
    "Late / early leave",
    "Internal newsletter",
    "Organization chart",
    "Mobile Attendance Registration",
    "POS Products",
    "POS Revenue Report",
    "Clock-in zones",
    "Dept. permissions",
    "Work shifts (API)",
    "Shift templates (API)",
    "Shift pay grades (API)",
    "Benefits (API)",
    "Transactions (API)",
    "Reports (legacy)",
    "service plan",
    "does not include",
    "Navigation",
    "Home, notifications",
    "Overview (Dashboard)",
    "Each dashboard block",
    "Employees, departments, salary settings, documents",
    "Raw attendance, schedule, approval, mobile, OT, shift swap",
    "Reports & payroll",
    "Attendance summary, payslips, statistics reports",
    "Bonuses, penalties, advances, cash flow, bank accounts",
    "Products, sales, inventory",
    "Operations management",
    "Meals, assets, tasks, KPI, output",
    "Shifts, holidays, time clocks, allowances, tax, branches",
    "Accounts, permissions, dept. permissions",
    "Price with VND",
    "Do not print price",
    "Price without unit",
    "Price with unit",
    "Do not print store name",
    "Print store name",
    "3-label roll template",
    "12-label sheet template",
    "65-label sheet template",
    "Jewelry item label template",
    "Print quantity",
    "Paper template",
    "ingredients",
    "Draft slip — stock not affected yet",
    "Stock count in progress — not balanced yet",
    ">> SALES",
    ">> RETURN / VOID",
    ">> PAYMENT",
    ">> SOLD ITEMS",
    "Order count",
    "Total revenue",
    "After returns",
    "Voided invoices",
    "Choose print or PDF export.",
    "Share / Print",
    "This month (lunar)",
    "Last month (lunar)",
    "This quarter",
    "Last quarter",
    "This year",
    "Last year",
    "This year (lunar)",
    "Last year (lunar)",
    "By week",
    "By month",
    "By quarter",
    "By year",
    "Product-assigned printer",
    "Select store printer",
    "Local printer (LAN/BT)",
    "No printer assigned",
    "Printer does not exist",
    "Print command failed",
    "Draft cart",
    "No printer assigned to product",
    "KITCHEN ORDER SLIP",
    "Print stock export slip",
    "Cannot print on local printer",
    "Printer no longer in store configuration",
    "Printer not found",
    "Local printer not enabled in Print Settings",
    "Local printer not connected",
    "No HTML template for stock export slip",
    "Fish skin peanuts",
    "35,000 VND",
    "Server returned no slip data — please reload",
    "Server reported success but slip not deleted — please reload",
    "Kitchen slip",
    "print received",
    "Cannot print document",
    "print no output",
    "sent",
    "Kitchen slip not sent",
    "Cannot connect to printer",
    "Cannot connect to local printer",
]
