T = [
    "Photo/video | invoice — customer display only",
    "Cannot open secondary display",
    "Allow popup or open #/customer-display on another screen",
    "No secondary display detected — not shown on main screen",
    "Cannot access table",
    "Draft order not loaded — still on floor plan",
    "Other terminal still holds table — retry in a few seconds",
    "Guests at table",
    "Unlock may be uncertain",
    "Returned to floor plan — other terminal try \"Take control\" in a few seconds if still editing",
    "No table assigned",
    "Select table before sending to kitchen",
    "No changes",
    "No new items or cancellations pending kitchen",
    "Missing terminal ID",
    "Cannot identify terminal — reopen app then retry kitchen send",
    "Wait for save to finish then resend to kitchen",
    "Other terminal is opening this table — ask them to exit to floor plan and reopen",
    "Order not saved yet",
    "Cannot send to kitchen — check terminal holding table",
    "Print command failed — check printer / paper",
    "(synced to server)",
    "Sent to kitchen — slip not printed",
    "Open pending print icon to reprint",
    "Items already sent to kitchen",
    "Permission not granted",
    "Enable \"Allow provisional bill\" in Industry Settings",
    "Wait for save to finish then reprint provisional bill",
    "Order not saved",
    "Save draft order before printing provisional bill",
    "Provisional bill status not saved",
    "Draft table highlighted — recheck if color lost on reload",
    "Printing provisional bill…",
    "Send print command",
    "Provisional bill not printed",
    "Unable to load order",
    "PROVISIONAL BILL",
    "Provisional bill print command sent",
    "Kitchen void slip printed",
    "Kitchen void print failed",
    "Void recorded — slip not printed",
    "Open pending print to reprint kitchen void slip",
    "Cup labels off",
    "Enable in Printer Settings → Cup labels",
    "No new labels",
    "All items labeled or cart empty",
    "Check thermal printer / Sunmi",
    "Cup labels printed",
    "No table/room selected",
    "Industry profile requires table/room before hold or checkout",
    "Select customer to deduct package session",
    "Session deducted",
    "Cannot add invoice",
    "Must keep at least 1 invoice",
    "Clear all items and close this invoice?",
    "Cannot close invoice",
    "Insufficient combo stock",
    "Insufficient stock",
    "Low stock",
    "Batch expired",
    "Batch expiring soon",
    "Orders awaiting payment",
    "Auto-refresh ~12s — paid orders will disappear",
    "On this terminal",
    "Not saved to server",
    "Opening",
    "Draft order on server",
    "Unable to load draft order list.",
    "No draft orders. Add items then tap \"Hold order\" or \"+\" new tab to save to server.",
    "Search more draft orders…",
    "Tab switched",
    "} · view only",
    "Return to floor plan and tap \"Take control\" to edit",
    "Order is being opened",
    "If other terminal returned to floor plan: tap \"Take control\" to edit.",
    "\"View only\" to monitor (no editing).",
    "Wait for other terminal to exit to floor plan then retry.",
    "Other terminal still in order — ask them to exit to floor plan then retry",
    "Cannot lock order",
    "Cannot take edit control — retry in a few seconds",
    "Other terminal still in order — wait for floor plan exit",
    "auto-expires",
    "Retry in a few seconds or return to floor plan and tap \"Take control\"",
    "order being opened\n        // by...",
    "Missing items in cart",
    "Order no longer exists",
    "} no longer on server — removed from tab",
    "Order already paid",
    "Order no longer draft",
    "Order held by another terminal.",
    "Not a draft order",
    "Only draft orders can be resumed",
    "Took control but could not reload order — try reopening table",
    "Draft order loaded",
    "Void item already sent to kitchen?",
    "Confirm will print kitchen void slip immediately.",
    "Print void slip",
    "Customer return quantity",
    "for returned portion already sent to kitchen.",
    "Confirm print slip",
    "Cannot verify code",
    "Invalid voucher",
    "Terminal serial",
    "Failed to save draft order",
    "Order held",
    "Draft saved — other store terminals can reopen from \"Awaiting payment\"",
    "Check connection and retry",
    "Payment failed",
    "Payment successful",
    "Payment failed. Check order before retrying.",
    "Partial kitchen print",
    "Kitchen print failed",
    "Check printer, Print Agent or assign product → kitchen printer",
    "No pending slips",
    "All print jobs succeeded",
    "Kitchen notified",
    "Cart is empty",
    "All cart items sent to kitchen. Add new items to continue printing.",
    "Unable to load just-sold order. Try reprint from order list.",
    "Post-payment print failed",
    "Invoice not printed",
    "Post-payment print error",
    "Post-payment print error. Try reprint from orders.",
    "Zoom QR code",
    "Auto-merge same products",
    "Store, printer, industry…",
    "Open secondary display (customer)",
    "Table / room floor plan",
    "Deduct package session",
    "View end-of-day report",
    "Revenue / stock report",
    "You do not have access to sales screen",
    "Loading sales…",
    "Change table / floor plan",
    "Sending…",
    "Add invoice",
    "Server sync · auto-save on item edit",
    "Items / Barcode",
    "Search and add products to invoice",
    "Search customer (F4)",
    "Product discount",
    "Recipient phone",
    "Delivery partner (GHN, GHTK...)",
    "Not subject to VAT",
    "Subtotal",
    "VAT per item (set on product)",
    "Voucher code",
    "Customer prior debt",
    "Total payment",
    "Change due",
    "This order debt",
    "Total debt after order",
    "Payment (multiple sources)",
    "Pay",
    "COMPLETE",
    "Hold order",
    "Add new items",
    "No item selected",
    "Add to table",
    "Floor plan — tap table to start",
    "Cart",
    "Back to cart",
    "PAYMENT COMPLETE",
    "Back to floor plan",
    "Deduct session",
    "Tap \"Select items\" to add from menu.",
    "Scan barcode to sell",
    "Use Scan button, Sunmi scanner, or USB.\nSelect Products to add manually.",
    "Product note",
    "Cannot merge",
    "Can only merge lines with same product, note, toppings and discount.",
    "Select customer",
    "Name, phone, customer code...",
    "Not sent to kitchen",
    "Split line",
    "Merge lines",
    "Remove from invoice",
    "No toppings yet",
    "Assign topping group or extras in product settings",
    "Unable to save note",
    "No lines match filter",
    "No permission for stock count",
    "Stock count detail",
    "Slip has no line items",
    "No permission to view stock count",
    "Search count code, notes…",
    "No stock counts yet",
    "Total actual",
    "Total variance",
    "Balance",
    "Balanced by",
    "Unable to save quantity",
    "Exit draft slip",
    "Keep",
    "Unable to delete slip",
    "Unable to save slip info",
    "Enter export qty > 0 for at least one line",
    "Exported by",
    "Completion date",
    "Product group",
    "Manage product groups, products and tiered pricing",
    "No product groups yet.\nAdd a product group first.",
    "No products yet.",
    "Pricing not configured",
    "Add product group",
    "Product group added",
    "Edit product group",
    "]}\"? Products in this group will also be deleted.",
    "Delete group",
    "Product updated",
    "Product added",
    "Product group *",
    "Product deleted",
    "aàảãáạăằẳẵắặâầẩẫấậ",
    "dđ",
    "eèẻẽéẹêềểễếệ",
    "iìỉĩíị",
    "oòỏõóọôồổỗốộơờởỡớợ",
    "uùủũúụưừửữứự",
    "yỳỷỹýỵ",
    "This email is already in use",
    "This phone number is already in use",
    "already in use",
    "already exists",
    "Unable to complete",
    "Your store code is:\\s*(\\S+)",
    "Start your journey\nin HR management",
    "Register your business to use the\nsmart HR management system.",
    "QUICK SETUP",
    "ONLY 2 MINUTES",
    "Create a new business account to get started.",
    "BUSINESS NAME",
    "Enter your business name",
    "Please enter business name",
    "Business name must be at least 2 characters",
    "LOGIN NAME (BUSINESS CODE)",
    "Example: sanapos — letters and numbers only, no accents",
    "Regenerate from business name",
    "Please enter login name",
    "Login name must be at least 2 characters",
    "Enter without accents or spaces (a-z, 0-9)",
    "Enter login email",
    "PROVINCE / CITY",
    "Select province / city",
    "PHONE NUMBER",
    "Enter contact phone number",
    "TRIAL PLAN",
    "Loading service plans...",
    "Select trial plan",
    "Please select a trial plan",
    "PASSWORD",
    "Enter password",
    "CONFIRM PASSWORD",
    "Already have an account?",
    "View service plan pricing on homepage",
    "This plan includes basic SBOX HRM features.",
    "View homepage pricing",
    "Basic features",
    "Password reset successful!",
    "Unable to reset password.",
    "Operations",
    "Filter group:",
    "Apply to entire group",
    "Group: View only",
    "Group: Operations",
    "Group: Full access",
    "Group: Disable all",
    "Add new job title",
    "Job title code",
    "E.g.: HR overview, HR setup...",
    "Unable to create job title",
    "Cannot delete system default job title",
    "Unable to delete job title",
    "Select a job title to view and edit permissions",
    "Job Title Permissions",
    "Select features by group — save when tapping \"Save changes\"",
    "Clear all",
    "View list",
    "Data export feature is under development",
    "Search by name or employee ID...",
    "Not set",
    ",\n        )} VND",
    "Paid leave days",
    "Unpaid leave days / month",
    "Annual leave / year",
    "Remaining annual leave",
    "Task completion salary",
    "Fixed daily salary",
    "Pay calculation type",
    "Pay per shift",
    "Social insurance salary (Base)",
    "Social insurance salary (Base + Task)",
    "Region II",
    "Region III",
    "Region IV",
    "12 days (default)",
    "No monthly salary profile assigned",
    "By leave policy",
    "Employee name:",
    "Employee ID:",
    "Salary type:",
    "Base salary:",
    "Task completion salary:",
    "Fixed daily salary:",
    "Annual leave (days/year):",
    "Unpaid leave (days/year):",
    "When assigning monthly salary profile, annual leave goes to employee leave balance.",
    "Pay calculation type:",
    "Pay per shift:",
    "Hourly rate:",
    "Fixed allowance:",
    "Daily allowance:",
    "Field pay (employee)",
    "When enabled, choose field hourly rate method. Only employees with approved mobile field hours appear on payroll.",
    "Disabled — field pay not calculated for this employee.",
    "Use task completion salary from employee profile",
    "Fixed rate (VND/hour)",
    "Field hourly rate:",
    "Standard workdays/month",
    "Used to divide monthly salary: daily rate = monthly salary ÷ standard days.",
    "Payable days may differ from actual when using fixed days.",
    "Days in month − Paid leave days",
    "E.g. 30-day month, Sun off → ≈26 standard days (varies by month)",
    "Fixed day count",
    "Stable daily rate by N workdays (default 26)",
    "Fixed workdays:",
    "Deduct daily salary if month below fixed workdays",
    "Add daily salary if exceeding fixed workdays",
    "Paid leave days:",
    "Saturday & Sunday",
    "Clock-in:",
    "Any punch within shift",
    "1 punch/shift (late by shift, out time = shift end)",
    "2 punches any time/day (no shift, no late/early/OT)",
    "Hours / 1 workday",
    "Default 8",
    "Total shift hours in day = 1 workday",
    "Unable to assign salary profile",
    "Unable to save settings",
    "Shift pay rates configured",
    "Configure shift pay rates in Shift Settings",
    "Select allowance from list",
    "Add fixed allowance",
    "Add daily allowance",
    "Add new allowance",
    "Allowance type *",
    "Hourly allowance",
    "Allowance name *",
    "E.g.: Lunch allowance",
    "Please enter allowance name",
    "Please enter amount",
    "Unable to create allowance",
    "Create allowance",
    "Work shift:",
    "Please add employees from HR Management screen",
    "Approval recorded — awaiting next level",
    "Shift grid",
    "No pending registrations",
    "All registrations this week processed. Choose another week or view Shift grid tab.",
    "Batch approve",
    "No registrations yet",
    "No schedule registrations this week",
    "Approve all this shift",
    "Revert all approvals",
    "Delete all registrations",
    "TOTAL EMP.",
    "No registrations or schedules this week",
    "Remind all",
    "Send reminder to all",
    "Reminder sent",
    "Total REG.",
    "⚠ Large variance — rebalance shift assignment",
    "⚠ Unbalanced",
    "⚠ No shift assigned",
    "⚠ Fewer shifts than average",
    "📌 More shifts than average",
    "ASSIGNED SHIFTS",
    "ALLOCATION",
    "TOTAL REG.",
    "APPROVED",
    "PENDING",
    "REJECTED",
    "✅ Normal",
    "🔴 Unassigned",
    "🟡 Few shifts",
    "🔵 Many shifts",
    "Are you sure you want to approve this registration?",
    "Approve registration",
    "Are you sure you want to reject this registration?",
    "Rejected by manager",
    "Rejection failed",
    "Registration approval reverted",
    "Unable to revert approval",
    "Are you sure you want to delete this registration?",
    "Registration deleted successfully",
    "Confirm batch approval",
    "Batch approve",
    "Batch approval failed",
    "No registrations could be approved",
    "Partially approved",
]
