T = [
    "Confirm batch rejection",
    "Batch rejection failed",
    "No registrations could be rejected",
    "Partially rejected",
    "Batch revert approval",
    "Batch delete",
    "System configuration management",
    "HRM system settings center",
    "Manage all shift, payroll policy, system admin and integration settings.",
    "Update your login password",
    "Bottom toolbar",
    "5 fixed slots — reorder and configure displayed actions",
    "Send feedback to developers",
    "System auto-syncs attendance data every 5 minutes.\nData updates when network is available.",
    "Account information",
    "You can change password in Change Password below.",
    "Password changed successfully",
    "Enter current and new password to update your account.",
    "Enter current password",
    "Unable to install sample data",
    "Unable to delete sample data",
    "Shift schedule",
    "Weekly shift assignment and approval",
    "Please create shifts in Shift Settings",
    "By shift",
    "Fixed shift → select employees by weekday",
    "By employee",
    "Fixed employee → select shifts by weekday",
    "Add employees...",
    "Add emp.",
    "Assigned employees",
    "Pending requests",
    "Assigned shifts",
    "Shift assigned successfully",
    "Shift assignment error",
    "Delete shift assignment",
    "Are you sure you want to delete this shift assignment?",
    "Shift assignment deleted",
    "Search by shift name...",
    "Break time (minutes)",
    "Other info",
    "Abbreviation",
    "Total shifts",
    "Tap \"Add shift\" to create a new shift",
    "Add new shift",
    "Shift & attendance setup guide",
    "1. Create and configure shifts",
    "Tap \"Add shift\" → enter name, code, in/out times.",
    "Choose shift type: Regular (main), Overtime (separate OT), or Overnight.",
    "Fill attendance params (early, late, early leave, OT…).",
    "Save shift → assign to employees in profile / schedule.",
    "2. Attendance parameter meanings",
    "Allow early punch: shift matching window. Punch earlier than threshold → no shift match.",
    "Allow late / early leave: max limits still within shift.",
    "Late/early grace: no late/early deduction within this range.",
    "Pre-shift OT: punch in earlier than threshold to count pre-shift OT.",
    "Post-shift OT: punch out later than threshold to count post-shift OT.",
    "Set \"Allow early punch\" ≥ \"Pre-shift OT\" (+1 min) for pre-shift OT to apply.",
    "3. Example config (shift 07:00–11:00)",
    "Allow early punch = 60 min → accepts punch from 06:00.",
    "Pre-shift OT = 30 min → in at 06:15 counts 45m OT; in at 06:31 no OT.",
    "Post-shift OT = 30 min → out at 11:31 counts 31m OT; out at 11:30 no OT.",
    "Shift hours still calculated 07:00–11:00 when on time (no late/early/OT).",
    "Pre-shift OT example",
    "In 06:15 → Out 11:00 → Pre-shift OT 45 minutes",
    "In 06:31 → Out 11:00 → No OT (early ≤ 30m)",
    "4. Employee clock-in (regular shift)",
    "Normal shift: In at start → Out at end (1 In/Out pair).",
    "Post-shift OT (recommended): Do not Out at shift end — Out only when OT done.",
    "Example: shift 07:00–11:00, work until 13:00 → In 07:00, Out 13:00 → OT 120 minutes.",
    "No Out punch: system reports missing punch, OT not calculated.",
    "Correct / Wrong for post-shift OT",
    "✅ In 07:00 → Out 13:00 (no Out at 11:00) → OT correct",
    "❌ In 07:00 → Out 11:00 → Out 13:00 → may lose OT 11:00–13:00",
    "❌ In 07:00, no Out → missing punch, OT = 0",
    "5. Out at shift end then continue OT",
    "Create additional \"Overtime\" shift (e.g. 11:30–13:00) and assign to employee.",
    "Employee: In/Out regular shift → then In/Out OT shift separately.",
    "Example: 07:00–11:00 (regular) + 11:30–13:00 (OT) → OT from OT shift.",
    "No OT shift but In again after shift end → usually no regular shift match.",
    "6. Shift types",
    "Regular: main shift — late, early, pre/post OT by thresholds.",
    "Overtime: all actual hours count as OT (no late/early).",
    "Overnight: crosses midnight — night shift rate applies per policy.",
    "7. Quick manager checklist",
    "Created enough regular shifts (and OT shifts if separate OT needed).",
    "Assigned shifts to employees / schedule.",
    "Allow early punch large enough vs pre-shift OT.",
    "Instructed employees: 1 In–Out pair when doing continuous post-shift OT.",
    "Check \"Shift summary\" after sample workday.",
    "Edit shift",
    "Add shift",
    "Shift name *",
    "E.g.: Morning shift, Afternoon shift",
    "Abbreviation",
    "Overnight shift",
    "Attendance day boundary from System Settings → Day end time (day_end_time). Night rate configured in pay grade / allowance.",
    "Break / lunch OT",
    "Punch in this window (MealOut/MealIn or app) counts as OT. Main work hours deduct break period.",
    "Break start",
    "Return after break",
    "Please enter shift name",
    "Attendance configuration",
    "Shift updated",
    "Shift added",
    "Unable to save shift",
    "Increase Allow early punch",
    "Employees punching early enough for OT may not match shift.",
    "minutes",
    "No pay grades yet",
    "Tap \"Add pay grade\" to create pay type, rates and employee groups",
    "])} /hour",
    "Pay grade name *",
    "E.g.: Grade 1 - Worker",
    "Fixed shift pay",
    "Shift pay multiplier",
    "Fixed rate (VND/shift)",
    "Hourly rate (VND/hour)",
    "Base salary multiplier",
    "Applicable employee groups",
    "Leave blank = apply to all employees",
    "Please enter pay grade name",
    "Pay grade updated",
    "Pay grade created",
    "Unable to delete shift",
    "Submit request · Feedback · Approval management",
    "Delete quota?",
    "This action cannot be undone.",
    "Quota deleted",
    "Edit quota",
    "Configure min/max headcount per weekday.",
    "Department / division",
    "Near-capacity warning (≤ N slots left)",
    "Used on schedule to warn before reaching max",
    "Weekday quotas",
    "Apply default",
    "Minimum",
    "Maximum",
    "Headcount quota updated",
    "Loading quotas...",
    "Shift headcount quotas",
    "Min/Max Mon–Sun · by shift & department · warnings on Schedule",
    "No quotas yet. Add config to warn understaff/overstaff on schedule.",
    "] ?? 2} slots",
    "Save info below to log in to the system",
    "Sample data installed",
    "Installing sample data...",
    "Install sample data (10 emp., 15 days)",
    "Download info image (PNG)",
    "Log in now",
    "STORE CODE",
    "store code",
    "You must enter STORE CODE each login.\nTake a photo or download PNG to save it!",
    "SBOX HRM  •  Real-time HR management",
    "} — Manage stores within assigned scope",
    "SuperAdmin — Manage entire system",
    "Are you sure you want to log out of admin area?",
    "Unable to load system settings",
    "% for 1 workday must be 1–100 (default 80)",
    "Min hours for half-day must be 0–24 (default 1)",
    "Workday end time",
    "Attendance request approval levels",
    "Work hour rounding rule",
    "Monthly attendance cutoff day",
    "Leave request approval levels",
    "% of standard daily hours for full workday (default 80)",
    "Min hours for half-day / partial day (default 1)",
    "Decimal workday calculation (0.1–1.0, disables % thresholds)",
    "System settings saved",
    "System settings",
    "Day end time",
    "Attendance day split point",
    "Change time",
    "Quick select:",
    "Single source for attendance day boundary / reports / penalties.",
    "• Default 00:00 — attendance day = calendar day",
    "• Set 06:00 → 2 AM punch counts for previous day (night shift friendly)",
    "• Night shifts only need shift type + pay rate; no separate cut time on shift",
    "Workday calculation rules",
    "By total daily work hours (not per shift)",
    "Decimal workday calculation",
    "On: round to nearest 0.1 / 0.2 … 1.0 by hour ratio — disables fixed % full/half thresholds",
    "Min hours for half-day / partial day",
    "hours",
    "Below this (e.g. 0.5h) → 0 workday. Default 1 hour. Applies with decimal mode too.",
    "% for full workday (threshold mode)",
    "% for full workday (disabled — using decimal)",
    "% for full workday",
    "≥ % standard hours → full workday; below (≥ min half-day) → 0.5",
    "Not used when decimal mode enabled",
    "Decimal mode enabled:",
    "• Workday = round (hours worked ÷ standard hours) to nearest 0.1.",
    "• E.g.: 3.6/8 ≈ 0.45 → 0.5 workday; 7.2/8 = 0.9 → 0.9 workday.",
    "• Below \"min half-day hours\" → 0 (avoids 30 min → 0.1).",
    "• Fixed % full/half thresholds: off.",
    "Threshold mode enabled:",
    "• ≥ (standard hours × %) → 1 workday.",
    "• ≥ min half-day hours and below % → 0.5 workday.",
    "• Below min half-day hours → 0 workday.",
    "• E.g.: standard 8h, min half 1h, 80% → ≥6.4h = full; 1–6.4h = half; below 1h = 0.",
    "Attendance approval",
    "Configure attendance correction approval workflow",
    "• 2 levels: Direct manager → HR/Director",
    "• 3 levels: Direct manager → Dept head → HR/Director",
    "Only 1 approver required",
    "2 levels (Manager + HR)",
    "Manager approves first, then HR",
    "3 levels (Manager + Dept head + HR)",
    "Work hour rounding",
    "Rounding rule for work hour calculation",
    "Setting saved but not yet applied to work hour engine. Will connect to payroll engine.",
    "No rounding",
    "Exact to the minute",
    "Round up",
    "Always round up (employee favorable)",
    "Round down",
    "Always round down",
    "Round nearest",
    "Round to nearest 15 minutes",
    "Make-up attendance & Period close",
    "Additional rules and payroll cycle",
    "Employees can request attendance make-up",
    "Monthly attendance cutoff day:",
    "Attendance finalized on this day each month",
    "• Cutoff day defines payroll cycle",
    "• E.g.: Day 25 → Cycle from 26/prev month to 25/this month",
    "• Day 1 → Calendar month close (1–31 each month)",
    "• Setting saved; used when Payroll Summary module is updated",
    "Leave approval",
    "Configure leave request approval workflow",
    "• 2 levels: Direct manager → Senior manager",
    "• 3 levels: Direct manager → Dept head → Admin",
    "• Admin always notified of all leave requests",
    "Direct manager only",
    "2 levels (Direct manager + Senior manager)",
    "Direct manager approves, then senior manager",
    "3 levels (Manager + Dept head + Admin)",
    "Task rejected",
    "Unable to load task list",
    "Unable to load Kanban",
    "Unable to load statistics",
    "Task ID not found",
    "Unable to load task detail",
    "Task Management",
    "Track & assign tasks",
    "No tasks yet",
    "Tap + to create a new task",
    "Search tasks...",
    "Selected",
    "Task type",
    "Overdue today",
    "Due today",
    "1 day left",
    "Completion rate",
    "Distribution by status",
    "Statistics by employee",
    "Task assigned to you — please accept or reject",
    "Confirm task acceptance",
    "Accept & start",
    "Progress",
    "Update progress (notes & images)",
    "Progress report (notes & images)",
    "After accepting, you can update progress and report.",
    "Assigned by",
    "Not assigned",
    "Priority",
    "Start",
    "No rating yet — tap \"Rate\" to score (1-5 stars)",
    "No rating for this task yet",
    "Rated by",
    "Activity & comments",
    "Progress reports and discussion in one timeline",
    "No activity yet",
    "Progress report",
    "System log",
    "Assign task, status change, rating...",
    "No system changes yet",
    "Change task title",
    "Change assignee",
    "Add comment",
    "Update task",
    "Task created successfully",
    "Create task",
    "Follow-up content *",
    "Urgency:",
    "Urgent",
    "Very urgent",
    "Enter follow-up content",
    "Follow-up sent",
    "Work quality",
    "Completion progress",
    "Overall rating",
    "Comments",
    "Rated",
    "Select date & time",
    "Comment added",
    "]} tasks",
    "Task assigned",
    "Task deleted",
    "0 minutes",
    "Select assignee",
    "Progress:",
    "Progress notes",
    "Describe completed work...",
    "No images yet",
    "Document links (one per line)",
    "PIT tax settings saved",
    "Save PIT tax settings",
    "PIT Tax Settings",
    "Configure progressive tax brackets and family deductions per amended PIT Law 2026",
    "Configure dependents per employee",
    "Tap each employee to view and edit details",
    "Dependents",
    "Mandatory insurance",
    "Tax-exempt income",
    "Number of dependents",
    "Dependent deduction",
    "Mandatory insurance",
    "Other tax exemptions",
    "Total tax-exempt income",
    "Family deductions",
    "Self and dependent deduction amounts",
    "Deduction for taxpayer",
    "VND/month",
    "Deduction per dependent",
    "VND/person/month",
    "Progressive tax brackets",
    "7 brackets per PIT Law",
    "BRACKET 7",
    "PIT tax table",
    "Summary of 7 progressive brackets",
    "Taxable income/month",
    "Training programs, internal courses",
    "Search training content...",
    "No training content yet",
    "Published training will appear here",
    "Account management",
    "Permissions, lock/unlock accounts",
    "Lock account",
    "Delete account",
    "]}\"? This action cannot be undone.",
    "Account deleted successfully",
    "Password reset",
    "No shifts configured in payroll settings",
    "Not sent",
    "Understaffed",
    "Near/at quota",
    "PENDING REGISTRATION",
    "APPROVED SCHEDULE",
    "Shift / Day",
    "New registration",
    "Cancel this shift registration",
    "Delete rejected registration",
    "Request shift swap with another employee",
    "Submit leave request for this shift",
    "Current shift:",
    "No list yet — try reloading page",
    "Same department as you",
    "Usually same shift or colleague's shift",
    "Colleague must agree, then manager approves. Track at Schedule Approval → Shift swap.",
    "Unable to submit shift swap request",
    "Leave for:",
    "Unable to submit leave request",
    "Registration reminder",
    "Request extra shift",
    "Copy day schedule",
    "Copy schedule from one day to other days.",
    "Select employees:",
    "Pending send list",
    "Send all registrations",
    "Approve by employee",
    "Approve by shift",
    "Add device error",
    "Device check error",
    "Device registration error",
    "Unable to cancel device registration",
    "};\n      }\n      // Create DeviceUser from Employee\n      final response = await http\n          .post(\n            Uri.parse(",
    ", // Will be taken from employeeId",
    ";\n    }\n\n    // Get relative path from full URL (avoid old host / localhost in DB).\n    if (trimmed.startsWith(",
    "Excel export unavailable (404)",
    "Excel import unavailable (404)",
    "Grant permissions for SBOX HRM",
    "App needs the following permissions to work properly:",
    "• Camera — face enrollment, clock-in",
    "• Location — verify clock-in location",
    "• Notifications — registration approvals, attendance",
    "Tap \"Grant permissions\" for system permission dialogs.",
    "Later",
    "Secondary browser window",
    "Could not extract photo features",
    "Attendance and system notifications",
    "📍 GlobalLocationReporter: skip (off-site clock-in not enabled or device not approved)",
    "MLKit: no enrollment photos",
    "MLKit: no face detected in captured photo",
    "MLKit: could not compare any enrollment photo",
    "Mobile nav bar layout (app)",
    "Mobile nav bar layout (POS)",
    "Mobile More tab quick access grid",
    "No printer chip selected for Agent",
    "Agent has no printer assigned",
]
