T = [
    "Mobile Attendance",
    "Authentication methods",
    "Enable Face ID verification",
    "Allow face-based clock-in",
    "Enable GPS verification",
    "Allow location verification when clocking in",
    "Enable office WiFi verification",
    "Allow clock-in via registered WiFi",
    "Liveness detection",
    "Prevent spoofing with photos/videos",
    "GPS settings",
    "Allowed radius",
    "Auto-approve within range",
    "Auto-approve if within allowed radius",
    "Face ID settings",
    "Minimum accuracy",
    "Max enrollment photos",
    "On-site photo (store)",
    "ON — enable per device in Devices tab",
    "OFF — no photo required after clock-in yet",
    "Approval workflow",
    "Allow manual approval",
    "HR can approve out-of-range cases",
    "Duplicate punch prevention",
    "Minimum interval",
    "Disable duplicate check — allow continuous punches",
    "Save settings",
    "Verification mode",
    "Any 1",
    "Only 1 method required",
    "All methods required",
    "Mobile attendance settings saved",
    "Unable to save settings",
    "Search locations...",
    "No locations yet",
    "Add work locations so employees can clock in",
    "No emp. assigned",
    "Assign employees",
    "Please select a location on the map",
    "New location added",
    "Unable to add location",
    "E.g.: Main office",
    "E.g.: 123 Nguyen Hue, District 1",
    "Location selected",
    "No face enrollment yet",
    "Enroll employee faces to use Face ID",
    "All employees have face enrollment",
    "Camera will capture 5 face photos: front, left, right, up, down",
    "Enrolling face...",
    "Search by employee, device name...",
    "Authorized devices",
    "No authorized devices yet",
    "Authorize employee phones for clock-in",
    "No devices / employees found",
    "Try different filters or keywords",
    "Site photo: On",
    "Site photo: awaiting store enable",
    "Site photo: device off",
    "No face photo on device",
    "Authorize device",
    "Scan QR code from mobile app",
    "Code valid for 5 minutes",
    "Employees need ZKTeco Mobile app to scan code",
    "Location deleted",
    "Location updated",
    "Unable to update",
    "Selected location",
    "Face enrollment deleted",
    "No face photo yet",
    "Retake face photo",
    "Re-enrolling face...",
    "Device authorized",
    "Device authorization revoked",
    "Unable to change authorization",
    "Feature not enabled",
    "Go to General Settings → enable \"On-site photo (store)\" first.",
    "Site photo capture ENABLED for this device",
    "Site photo capture DISABLED for this device",
    "Off-site clock-in allowed",
    "Off-site clock-in disabled — employees removed from HR map",
    "Field clock-in allowed on this device",
    "Field clock-in disabled on this device",
    "Approve device change",
    "Reject device change",
    "Device registration approved",
    "Device registration rejected",
    "Operating system",
    "Device ID",
    "Off-site clock-in",
    "Capture on-site photo after clock-in",
    "Enable \"On-site photo (store)\" in General Settings first",
    "ON on this device",
    "OFF on this device",
    "Authorized",
    "Revoked",
    "Face on device",
    "Employee has no face photo — enroll when authorizing device or scan on employee device",
    "Assign employee to device to view face photo",
    "No face photo linked to this device",
    "Disable off-site",
    "Enable off-site",
    "Disable field",
    "Enable field",
    "On-site photo: ON (camera opens after each punch)",
    "On-site photo: OFF — not enabled at store level",
    "Device: ON · Store: OFF (not effective when clocking in)",
    "On-site photo: OFF on this device",
    "Unable to save employee assignment",
    "No employees in system",
    "Select employees allowed to clock in at this location.",
    "Employee with no assigned location → can clock in anywhere.",
    "Employee with at least 1 location → only assigned locations.",
    "Search by name, ID, department…",
    ";\n    if (m.isEmpty) return fallback;\n    // Legacy API encoding error strings (Device?, Cannot...)\n    if (m.contains(",
    "All marked as read",
    "Delete all notifications?",
    "All notifications deleted",
    "Unread",
    "Read",
    "Notification settings saved",
    "Could not save to server. FCM may still send notifications.",
    "Cannot connect to server. Settings not applied — FCM may still send notifications.",
    "Attendance notifications",
    "Clock-in, field work, device connect/disconnect",
    "Work notifications",
    "Leave, overtime, payroll, KPI, approvals, ...",
    "Choose notification groups to receive. Disabling a group stops that type.",
    "Chart",
    "Unassigned emp.",
    "No org chart data yet",
    "Create departments and assign positions to employees",
    "No employees in this department",
    "No positions yet",
    "Create positions to build org chart",
    "Approved",
    "New assignment",
    "No position assignments yet",
    "Assign positions to employees to build org chart",
    "Add workflow",
    "No approval workflows yet",
    "Create approval workflows to configure approval process",
    "All employees have assigned positions",
    "No employees need additional assignment",
    "Position code *",
    "Position name *",
    "Level *",
    "Color (hex)",
    "Has approval rights",
    "Max approval level",
    "Update position",
    "Approver position",
    "Create approval workflow",
    "Update approval workflow",
    "No overtime requests",
    "Start time (HH:mm) *",
    "End time (HH:mm) *",
    "Please select overtime date",
    "Please enter start and end times",
    "Please enter overtime reason",
    "Unable to register overtime",
    "Reject overtime",
    "Employee payroll detail",
    "Select columns",
    "Column",
    "Select month",
    "Finalized payslip list",
    "Your payslip",
    "No payslips yet",
    "Finalize payroll in Payroll Summary to generate payslips",
    "Apply filter",
    "All months",
    "Unpaid",
    "Gross income",
    "Other deductions",
    "View period attendance sheet",
    "Loading attendance sheet...",
    "No attendance sheet attached",
    "This payslip has no attendance sheet (finalized before feature update).",
    "No attendance records",
    "Finalized",
    ").format(n)} VND",
    "0 VND",
    "Total slips",
    "Violating employees",
    "You have no penalty slips yet",
    "Unable to load penalty settings, using defaults",
    "Penalty settings saved",
    "Configure late, early leave, repeat offense and other penalties",
    "Penalty by late minutes",
    "Early leave penalty",
    "Penalty by early leave minutes",
    "Repeat offense penalty",
    "Extra penalty for multiple violations in a month",
    "Other penalty types",
    "Missed punch, unauthorized leave, policy violations",
    "No clock-in or clock-out",
    "Leave without approval or notice",
    "VND / day",
    "Violation of internal company policies",
    "Penalty amount (VND)",
    "Approve penalty slip",
    "Approving penalty slip will create a matching receipt. Are you sure?",
    "Penalty slip approved and receipt created",
    "Revert penalty approval",
    "Revert will delete related receipt and return slip to pending. Are you sure?",
    "Penalty approval reverted",
    "Cancel penalty slip",
    "Are you sure you want to cancel this penalty slip?",
    "Penalty slip cancelled",
    "Delete penalty slip",
    "Are you sure you want to delete this penalty slip? Only pending slips can be deleted.",
    "Penalty slip deleted",
    "Select rescan date range",
    "Date range too long",
    "Maximum 62 days per scan. Please select a shorter range.",
    "and create missing late/early/missed punch penalties (if any).",
    "This may take a few minutes.",
    "Unable to rescan attendance",
    "Quick approve",
    "Cannot edit",
    "Only pending slips can be edited",
    "Unable to approve penalty slip",
    "Penalty slip updated",
    "Penalty slip created & approved",
    "Penalty slip created",
    "Penalty type *",
    "Select penalty type",
    "Penalty amount (VND) *",
    "Violation date *",
    "Late/early minutes",
    "Violation date",
    "Minutes",
    "]} min",
    "Shift",
    "Actual punch time",
    "Penalty tier",
    "Processed by",
    "Processed date",
    "Discard changes?",
    "Unsaved print template changes. Discard changes?",
    "Enter print template name",
    "Print template updated",
    "Add print template",
    "Sample template",
    "Table 05",
    "Rare beef pho",
    "bowl",
    "Less onion",
    "Iced tea",
    "Sample printed on Sunmi",
    "Sunmi not responding",
    "Test print sent",
    "Check local printer connection",
    "Delete print template?",
    "No templates — tap +",
    "Print template:",
    "Unable to load products",
    "Please try again later",
    "You do not have permission to add products",
    "Unable to update price",
    "Unable to update stock",
    "Delete similar items",
    "Similar items deleted",
    "Products exported to Excel",
    "Add product group",
    "Loading products…",
    "Create combo",
    "Exporting…",
    "Print barcode labels",
    "All product types",
    "Search products",
    "Code, product name…",
    "Create product",
    "Create combo / bundle",
    "Total stock",
    "Change filter",
    "No products yet",
    "Tap \"Create new\" to add products, services or combos",
    "Print barcode labels",
    "More actions",
    "Duplicate product",
    "Add similar item",
    "Amount (VND)",
    "Enter product note…",
    "Product added",
    "Scan code or search name to add to slip",
    "Tax included",
    "Select expiry date",
    "Select manufacture date",
    "Batch code",
    "Missing expiry date",
    "Goods receipt code",
    "Purchase invoice",
    "Amount paid to supplier",
    "Total VAT",
    "Payable to supplier",
    "No permission to receive goods",
    "Search by code, name or scan barcode (F3)",
    "No items to print labels",
    "Purchase invoice number",
    "Purchase invoice no…",
    "Select receiver…",
    "No permission to view goods receipt",
    "Search receipt code, notes…",
    "No goods receipts yet",
    "GR code",
    "Payable to supplier",
    "Payable",
    "Pay supplier",
    "Purchase invoice no.",
    "No permission to return goods",
    "Load from goods receipt (GR code)…",
    "Load GR",
    "Purchase return detail",
    "No items in return slip",
    "Search items or load from goods receipt (F3)",
    "Search supplier",
    "Purchase return code",
    "Supplier refund (F8)",
    "Select returner…",
    "No permission to view purchase returns",
    "Search by return code…",
    "PR code",
    "Revenue exported to Excel",
    "Stock exported to Excel",
    "No permission to view POS reports",
    "Sales revenue",
    "Batch/Expiry",
    "Batch / Expiry",
    "Top sellers",
    "Search product / batch code",
    "Expiring soon",
    "Expired",
    "Active batch",
    "Batch qty",
    "Batch",
    "Delivering",
    "Cannot deliver",
    "Empty order",
    "Order completed",
    "Create new order",
    "Search products by code or name",
    "Add customer",
    "Delivery phone",
    "Discount (VND)",
    "Customer paid",
    "No items — search or scan to add",
    "Complete (quick)",
    "Delivery status",
    "• Restore sold stock",
    "• Restore debt / points / voucher (if any)",
    "• Order moves to \"Cancelled\" (still visible in list)",
    "Use only when order is completed and not yet returned.",
    "Server returned no order data — please reload list",
    "Order cancelled",
    "Remove from list",
    "• No additional stock restore (already processed)",
    "• Removes from screen only — data remains on server",
    "For cancelled, draft, or fully returned orders.",
    "Orders exported to Excel",
    "Export failed",
    "Order type",
    "No delivery",
    "No permission to view orders",
    "Order management",
    "Search order code, customer…",
    "No orders yet",
    "orders",
    "Net revenue",
    "UNKNOWN DATE",
    "Customer",
    "Total due",
    "Processing…",
    "No permission to view returns",
    "New return",
    "Search return code, invoice, customer…",
    "Returns only on completed orders",
    "Unable to load invoice",
    "Unable to cancel return slip",
    "No return quantity entered",
    "Return successful",
    "Return error",
    "Return failed",
    "Change invoice",
    "Sales return",
    "Select completed invoice to return partial or full items.",
    "Select invoice",
    "Select return items",
    "Refund method",
    "Return history",
    "Refund",
    "pcs",
    "Previously returned",
    "Refund this time",
    "RETURN",
    "Price list changed",
    "Enable in Industry Settings first",
    "Device has only 1 screen",
    "Secondary display opens only when device has a second display (customer screen).",
    "Secondary display opened",
]
