// GENERATED by scripts/gen_commercial_templates.py — KHÔNG sửa tay.
// Nguồn: src/ZKTecoADMS.Api/PrintTemplates/A4/*.html (dùng chung với API).
// ignore_for_file: lines_longer_than_80_chars

const posA4QuoteHtml = r'''<div style="font-family:'Times New Roman',Times,serif;font-size:13px;line-height:1.35;color:#000">
  <table style="width:100%;border-collapse:collapse"><tr>
    <td style="width:56%;vertical-align:top;padding:0">
      <!--IF:Logo--><div style="margin-bottom:4px">{Logo}</div><!--ENDIF:Logo-->
      <div style="font-weight:bold;text-transform:uppercase;font-size:14px">{Ten_Cong_Ty}</div>
      <!--IF:MST_Cua_Hang--><div>MST: {MST_Cua_Hang}</div><!--ENDIF:MST_Cua_Hang-->
      <!--IF:Dia_Chi_Cong_Ty--><div>Địa chỉ: {Dia_Chi_Cong_Ty}</div><!--ENDIF:Dia_Chi_Cong_Ty-->
      <div><!--IF:Dien_Thoai_Cong_Ty-->ĐT: {Dien_Thoai_Cong_Ty}<!--ENDIF:Dien_Thoai_Cong_Ty--><!--IF:Email_Cua_Hang--> &nbsp; Email: {Email_Cua_Hang}<!--ENDIF:Email_Cua_Hang--></div>
    </td>
    <td style="width:44%;vertical-align:top;text-align:right;padding:0">
      <div>Số: <b>{So_Chung_Tu}</b></div>
      <div>Ngày {Ngay_So} tháng {Thang} năm {Nam}</div>
      <!--IF:Han_Bao_Gia--><div>Hiệu lực đến: <b>{Han_Bao_Gia}</b></div><!--ENDIF:Han_Bao_Gia-->
    </td>
  </tr></table>
  <h2 style="text-align:center;font-size:20px;margin:14px 0 10px;letter-spacing:1px">BẢNG BÁO GIÁ</h2>
  <table style="width:100%;border-collapse:collapse;margin-bottom:6px"><tr><td style="padding:0">
    <div><b>Kính gửi:</b> {Ben_A_Ten}</div>
    <!--IF:Nguoi_Lien_He_Khac--><div>Người liên hệ: {Khach_Hang}</div><!--ENDIF:Nguoi_Lien_He_Khac-->
    <!--IF:Dia_Chi_Khach_Hang--><div>Địa chỉ: {Dia_Chi_Khach_Hang}</div><!--ENDIF:Dia_Chi_Khach_Hang-->
    <div><!--IF:SDT-->Điện thoại: {SDT}<!--ENDIF:SDT--><!--IF:MST_Khach_Hang--> &nbsp; MST: {MST_Khach_Hang}<!--ENDIF:MST_Khach_Hang--></div>
  </td></tr></table>
  <p style="margin:6px 0">{Ten_Cong_Ty} trân trọng gửi Quý khách bảng báo giá hàng hóa / dịch vụ như sau:</p>
  <table style="width:100%;border-collapse:collapse;margin:6px 0;font-size:12.5px">
    <thead><tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:5px 3px;width:5%;text-align:center">STT</th>
      <th style="border:1px solid #000;padding:5px 4px;text-align:left">Tên hàng hóa / dịch vụ</th>
      <th style="border:1px solid #000;padding:5px 3px;width:7%;text-align:center">ĐVT</th>
      <th style="border:1px solid #000;padding:5px 3px;width:7%;text-align:center">SL</th>
      <th style="border:1px solid #000;padding:5px 4px;width:13%;text-align:right">Đơn giá</th>
      <th style="border:1px solid #000;padding:5px 4px;width:14%;text-align:right">Thành tiền</th>
      <!--IF:Co_Bao_Hanh_Dong--><th style="border:1px solid #000;padding:5px 3px;width:10%;text-align:center;white-space:nowrap">Bảo hành</th><!--ENDIF:Co_Bao_Hanh_Dong-->
      <!--IF:Co_Anh--><th style="border:1px solid #000;padding:5px 3px;width:14%;text-align:center">Hình ảnh</th><!--ENDIF:Co_Anh-->
    </tr></thead>
    <tbody><!--BEGIN_ITEMS--><tr>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{STT}</td>
      <td style="border:1px solid #000;padding:4px 4px;vertical-align:top">{Ten_Hang_Hoa}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{Don_Vi_Tinh}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{So_Luong}</td>
      <td style="border:1px solid #000;padding:4px 4px;text-align:right;vertical-align:top">{Don_Gia}</td>
      <td style="border:1px solid #000;padding:4px 4px;text-align:right;vertical-align:top">{Thanh_Tien}</td>
      <!--IF:Co_Bao_Hanh_Dong--><td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top;white-space:nowrap">{Bao_Hanh}</td><!--ENDIF:Co_Bao_Hanh_Dong-->
      <!--IF:Co_Anh--><td style="border:1px solid #000;padding:3px;text-align:center;vertical-align:middle">{Hinh_Anh}</td><!--ENDIF:Co_Anh-->
    </tr><!--END_ITEMS--></tbody>
  </table>
  <table style="width:52%;margin:2px 0 0 auto;border-collapse:collapse;font-size:12.5px">
    <tr><td style="padding:3px 6px">Tổng tiền hàng</td><td style="padding:3px 6px;text-align:right">{Tong_Tien_Hang}</td></tr>
    <!--IF:Chiet_Khau_Hoa_Don--><tr><td style="padding:3px 6px">Chiết khấu</td><td style="padding:3px 6px;text-align:right">- {Chiet_Khau_Hoa_Don}</td></tr><!--ENDIF:Chiet_Khau_Hoa_Don-->
    <!--IF:Tien_Thue--><tr><td style="padding:3px 6px">Thuế GTGT {Thue_Suat}</td><td style="padding:3px 6px;text-align:right">{Tien_Thue}</td></tr><!--ENDIF:Tien_Thue-->
    <tr><td style="padding:5px 6px;border-top:1.5px solid #000"><b>TỔNG CỘNG</b></td><td style="padding:5px 6px;border-top:1.5px solid #000;text-align:right"><b>{Tong_Cong} đ</b></td></tr>
  </table>
  <p style="margin:6px 0 2px"><b>Bằng chữ:</b> <i>{Tong_Cong_Bang_Chu}</i></p>
  <!--IF:Cach_Tinh_VAT--><p style="margin:2px 0 4px"><i>{Cach_Tinh_VAT}.</i></p><!--ENDIF:Cach_Tinh_VAT-->
  <!--IF:Co_Dot_Thanh_Toan-->
  <p style="margin:10px 0 4px"><b>Tiến độ thanh toán:</b></p>
  <table style="width:100%;border-collapse:collapse;font-size:12.5px;margin-bottom:8px">
    <tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:4px;width:6%">Đợt</th>
      <th style="border:1px solid #000;padding:4px;text-align:left">Nội dung</th>
      <th style="border:1px solid #000;padding:4px;width:15%;white-space:nowrap">Tỷ lệ</th>
      <th style="border:1px solid #000;padding:4px;width:18%;text-align:right">Số tiền</th>
      <!--IF:Co_Han_Dot--><th style="border:1px solid #000;padding:4px;width:16%">Thời hạn</th><!--ENDIF:Co_Han_Dot-->
    </tr>
    <!--BEGIN_STAGES--><tr>
      <td style="border:1px solid #000;padding:4px;text-align:center">{Dot_STT}</td>
      <td style="border:1px solid #000;padding:4px">{Dot_Ten}</td>
      <td style="border:1px solid #000;padding:4px;text-align:center;white-space:nowrap">{Dot_Phan_Tram}</td>
      <td style="border:1px solid #000;padding:4px;text-align:right">{Dot_So_Tien}</td>
      <!--IF:Co_Han_Dot--><td style="border:1px solid #000;padding:4px;text-align:center">{Dot_Han}</td><!--ENDIF:Co_Han_Dot-->
    </tr><!--END_STAGES-->
  </table>
  <!--ENDIF:Co_Dot_Thanh_Toan-->
  <!--IFNOT:Co_Dot_Thanh_Toan--><!--IF:Tien_Coc-->
  <p style="margin:8px 0 2px"><b>Đặt cọc:</b> {Tien_Coc} đ ({Phan_Tram_Coc}% {Coc_Tinh_Tren}) — bằng chữ: {Tien_Coc_Bang_Chu}. Phần còn lại: {Con_Lai_Hop_Dong} đ.</p>
  <!--ENDIF:Tien_Coc--><!--ENDIFNOT:Co_Dot_Thanh_Toan-->
  <!--IF:Hinh_Thuc_Thanh_Toan--><p style="margin:8px 0 4px"><b>Hình thức thanh toán:</b> {Hinh_Thuc_Thanh_Toan}</p><!--ENDIF:Hinh_Thuc_Thanh_Toan-->
  <!--IF:Tai_Khoan_Cua_Hang--><p style="margin:4px 0"><b>Tài khoản:</b> {Tai_Khoan_Cua_Hang} — {Ngan_Hang_Cua_Hang} — Chủ TK: {Chu_Tai_Khoan_Cua_Hang}</p><!--ENDIF:Tai_Khoan_Cua_Hang-->
  <!--IF:Ky_Han_Thi_Cong--><p style="margin:4px 0"><b>Thời gian thực hiện:</b> {Ky_Han_Thi_Cong}</p><!--ENDIF:Ky_Han_Thi_Cong-->
  <!--IF:Bao_Hanh--><p style="margin:4px 0"><b>Bảo hành:</b> {Bao_Hanh}</p><!--ENDIF:Bao_Hanh-->
  <!--IF:Dieu_Khoan--><p style="margin:4px 0;white-space:pre-line"><b>Điều khoản:</b> {Dieu_Khoan}</p><!--ENDIF:Dieu_Khoan-->
  <!--IF:Ghi_Chu--><p style="margin:4px 0;white-space:pre-line"><b>Ghi chú:</b> {Ghi_Chu}</p><!--ENDIF:Ghi_Chu-->
  <p style="margin:8px 0">Rất mong nhận được sự hợp tác của Quý khách. Trân trọng!</p>
  <table style="width:100%;margin-top:14px;border-collapse:collapse;page-break-inside:avoid"><tr>
    <td style="width:50%;text-align:center;vertical-align:top"><b>XÁC NHẬN CỦA KHÁCH HÀNG</b><br/><i>(Ký, ghi rõ họ tên)</i><div style="height:116px"></div><b>{Nguoi_Dai_Dien_Khach}</b></td>
    <td style="width:50%;text-align:center;vertical-align:top"><b style="text-transform:uppercase">ĐẠI DIỆN {Ten_Cong_Ty}</b><br/><i>{Chuc_Vu_Cua_Hang}</i><div style="height:116px;overflow:hidden">{Con_Dau}</div><b>{Nguoi_Dai_Dien_Cua_Hang}</b><!--IF:Nguoi_Bao_Gia--><div style="margin-top:6px;font-size:12px">Người lập: {Nguoi_Bao_Gia}</div><!--ENDIF:Nguoi_Bao_Gia--></td>
  </tr></table>
</div>''';

const posA4ContractHtml = r'''<div style="font-family:'Times New Roman',Times,serif;font-size:13px;line-height:1.4;color:#000">
  <div style="text-align:center;line-height:1.3">
    <div style="font-weight:bold">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div>
    <div style="font-weight:bold">Độc lập - Tự do - Hạnh phúc</div>
    <div style="border-top:1px solid #000;width:170px;margin:4px auto 0"></div>
  </div>
  <h2 style="text-align:center;font-size:19px;margin:16px 0 2px">HỢP ĐỒNG KINH TẾ</h2>
  <div style="text-align:center;font-weight:bold">(V/v: Cung cấp và lắp đặt hàng hóa / thi công)</div>
  <div style="text-align:center;margin-top:2px">Số: <b>{So_Hop_Dong}</b><!--IF:Ma_Bao_Gia--> &nbsp;—&nbsp; Theo báo giá số {Ma_Bao_Gia}<!--ENDIF:Ma_Bao_Gia--></div>
  <p style="margin:10px 0 2px"><i>- Căn cứ Bộ luật Dân sự số 91/2015/QH13 ngày 24/11/2015;</i></p>
  <p style="margin:2px 0"><i>- Căn cứ Luật Thương mại số 36/2005/QH11 ngày 14/06/2005;</i></p>
  <p style="margin:2px 0 8px"><i>- Căn cứ nhu cầu và khả năng của hai bên.</i></p>
  <p style="margin:4px 0">Hôm nay, ngày {Ngay_HD_So} tháng {Thang_HD} năm {Nam_HD}<!--IF:Dia_Diem_Ky-->, tại {Dia_Diem_Ky}<!--ENDIF:Dia_Diem_Ky-->, chúng tôi gồm:</p>

  <p style="margin:8px 0 2px"><b>BÊN A (BÊN MUA): {Ben_A_Ten}</b></p>
  <!--IF:Dia_Chi_Khach_Hang--><div>Địa chỉ: {Dia_Chi_Khach_Hang}</div><!--ENDIF:Dia_Chi_Khach_Hang-->
  <!--IF:MST_Khach_Hang--><div>Mã số thuế: {MST_Khach_Hang}</div><!--ENDIF:MST_Khach_Hang-->
  <!--IF:SDT--><div>Điện thoại: {SDT}</div><!--ENDIF:SDT-->
  <!--IF:Tai_Khoan_Khach_Hang--><div>Tài khoản: {Tai_Khoan_Khach_Hang}<!--IF:Ngan_Hang_Khach_Hang--> tại {Ngan_Hang_Khach_Hang}<!--ENDIF:Ngan_Hang_Khach_Hang--></div><!--ENDIF:Tai_Khoan_Khach_Hang-->
  <div>Đại diện: <b>{Nguoi_Dai_Dien_Khach}</b><!--IF:Chuc_Vu_Khach--> &nbsp; Chức vụ: {Chuc_Vu_Khach}<!--ENDIF:Chuc_Vu_Khach--></div>

  <p style="margin:8px 0 2px"><b>BÊN B (BÊN BÁN / NHÀ THẦU): {Ten_Cong_Ty}</b></p>
  <!--IF:Dia_Chi_Cong_Ty--><div>Địa chỉ: {Dia_Chi_Cong_Ty}</div><!--ENDIF:Dia_Chi_Cong_Ty-->
  <!--IF:MST_Cua_Hang--><div>Mã số thuế: {MST_Cua_Hang}</div><!--ENDIF:MST_Cua_Hang-->
  <div><!--IF:Dien_Thoai_Cong_Ty-->Điện thoại: {Dien_Thoai_Cong_Ty}<!--ENDIF:Dien_Thoai_Cong_Ty--><!--IF:Email_Cua_Hang--> &nbsp; Email: {Email_Cua_Hang}<!--ENDIF:Email_Cua_Hang--></div>
  <!--IF:Tai_Khoan_Cua_Hang--><div>Tài khoản: {Tai_Khoan_Cua_Hang} tại {Ngan_Hang_Cua_Hang} — Chủ TK: {Chu_Tai_Khoan_Cua_Hang}</div><!--ENDIF:Tai_Khoan_Cua_Hang-->
  <div>Đại diện: <b>{Nguoi_Dai_Dien_Cua_Hang}</b> &nbsp; Chức vụ: {Chuc_Vu_Cua_Hang}</div>

  <p style="margin:8px 0">Sau khi bàn bạc, hai bên thống nhất ký kết hợp đồng với các điều khoản sau:</p>

  <p style="margin:8px 0 2px"><b>ĐIỀU 1. HÀNG HÓA / HẠNG MỤC VÀ GIÁ TRỊ HỢP ĐỒNG</b></p>
  <!--IF:Dia_Diem_Thi_Cong--><div>Địa điểm giao hàng / thi công: {Dia_Diem_Thi_Cong}</div><!--ENDIF:Dia_Diem_Thi_Cong-->
  <table style="width:100%;border-collapse:collapse;margin:6px 0;font-size:12px">
    <thead><tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:5px 3px;width:5%">STT</th>
      <th style="border:1px solid #000;padding:5px 4px;text-align:left">Tên hàng hóa / hạng mục</th>
      <th style="border:1px solid #000;padding:5px 3px;width:7%">ĐVT</th>
      <th style="border:1px solid #000;padding:5px 3px;width:7%">SL</th>
      <th style="border:1px solid #000;padding:5px 4px;width:13%;text-align:right">Đơn giá</th>
      <th style="border:1px solid #000;padding:5px 4px;width:14%;text-align:right">Thành tiền</th>
      <!--IF:Co_Bao_Hanh_Dong--><th style="border:1px solid #000;padding:5px 3px;width:8%">Bảo hành</th><!--ENDIF:Co_Bao_Hanh_Dong-->
    </tr></thead>
    <tbody><!--BEGIN_ITEMS--><tr>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{STT}</td>
      <td style="border:1px solid #000;padding:4px 4px;vertical-align:top">{Ten_Hang_Hoa}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{Don_Vi_Tinh}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{So_Luong}</td>
      <td style="border:1px solid #000;padding:4px 4px;text-align:right;vertical-align:top">{Don_Gia}</td>
      <td style="border:1px solid #000;padding:4px 4px;text-align:right;vertical-align:top">{Thanh_Tien}</td>
      <!--IF:Co_Bao_Hanh_Dong--><td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{Bao_Hanh}</td><!--ENDIF:Co_Bao_Hanh_Dong-->
    </tr><!--END_ITEMS--></tbody>
  </table>
  <table style="width:52%;margin-left:auto;border-collapse:collapse;font-size:12.5px">
    <tr><td style="padding:3px 6px">Tổng tiền hàng</td><td style="padding:3px 6px;text-align:right">{Tong_Tien_Hang}</td></tr>
    <!--IF:Chiet_Khau_Hoa_Don--><tr><td style="padding:3px 6px">Chiết khấu</td><td style="padding:3px 6px;text-align:right">- {Chiet_Khau_Hoa_Don}</td></tr><!--ENDIF:Chiet_Khau_Hoa_Don-->
    <!--IF:Tien_Thue--><tr><td style="padding:3px 6px">Thuế GTGT {Thue_Suat}</td><td style="padding:3px 6px;text-align:right">{Tien_Thue}</td></tr><!--ENDIF:Tien_Thue-->
    <tr><td style="padding:5px 6px;border-top:1.5px solid #000"><b>GIÁ TRỊ HỢP ĐỒNG</b></td><td style="padding:5px 6px;border-top:1.5px solid #000;text-align:right"><b>{Tong_Cong} đ</b></td></tr>
  </table>
  <p style="margin:4px 0">Bằng chữ: <i>{Tong_Cong_Bang_Chu}</i>. {Cach_Tinh_VAT}.</p>

  <p style="margin:8px 0 2px"><b>ĐIỀU 2. THANH TOÁN</b></p>
  <!--IF:Hinh_Thuc_Thanh_Toan--><div>Hình thức thanh toán: {Hinh_Thuc_Thanh_Toan}.</div><!--ENDIF:Hinh_Thuc_Thanh_Toan-->
  <!--IF:Co_Dot_Thanh_Toan-->
  <div>Bên A thanh toán cho Bên B theo các đợt sau:</div>
  <table style="width:100%;border-collapse:collapse;margin:4px 0;font-size:12px">
    <tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:4px;width:7%">Đợt</th>
      <th style="border:1px solid #000;padding:4px;text-align:left">Nội dung / điều kiện</th>
      <th style="border:1px solid #000;padding:4px;width:15%;white-space:nowrap">Tỷ lệ</th>
      <th style="border:1px solid #000;padding:4px;width:18%;text-align:right">Số tiền (đ)</th>
      <!--IF:Co_Han_Dot--><th style="border:1px solid #000;padding:4px;width:15%">Thời hạn</th><!--ENDIF:Co_Han_Dot-->
    </tr>
    <!--BEGIN_STAGES--><tr>
      <td style="border:1px solid #000;padding:4px;text-align:center">{Dot_STT}</td>
      <td style="border:1px solid #000;padding:4px">{Dot_Ten}</td>
      <td style="border:1px solid #000;padding:4px;text-align:center;white-space:nowrap">{Dot_Phan_Tram}</td>
      <td style="border:1px solid #000;padding:4px;text-align:right">{Dot_So_Tien}</td>
      <!--IF:Co_Han_Dot--><td style="border:1px solid #000;padding:4px;text-align:center">{Dot_Han}</td><!--ENDIF:Co_Han_Dot-->
    </tr><!--END_STAGES-->
  </table>
  <!--ENDIF:Co_Dot_Thanh_Toan-->
  <!--IFNOT:Co_Dot_Thanh_Toan-->
  <!--IF:Tien_Coc--><div>- Đợt 1: Bên A tạm ứng <b>{Phan_Tram_Coc}%</b> {Coc_Tinh_Tren}, tương ứng <b>{Tien_Coc} đ</b> (bằng chữ: {Tien_Coc_Bang_Chu}) ngay sau khi ký hợp đồng.</div>
  <div>- Đợt 2: Bên A thanh toán phần còn lại <b>{Con_Lai_Hop_Dong} đ</b> (bằng chữ: {Con_Lai_Bang_Chu}) sau khi nghiệm thu, bàn giao.</div><!--ENDIF:Tien_Coc-->
  <!--IFNOT:Tien_Coc--><div>- Bên A thanh toán toàn bộ giá trị hợp đồng sau khi nghiệm thu, bàn giao.</div><!--ENDIFNOT:Tien_Coc-->
  <!--ENDIFNOT:Co_Dot_Thanh_Toan-->
  <div>- Hồ sơ thanh toán: biên bản nghiệm thu / bàn giao, đề nghị thanh toán và hóa đơn GTGT (nếu có).</div>

  <p style="margin:8px 0 2px"><b>ĐIỀU 3. THỜI GIAN VÀ ĐỊA ĐIỂM THỰC HIỆN</b></p>
  <!--IF:Ky_Han_Thi_Cong--><div>- Thời gian thực hiện: {Ky_Han_Thi_Cong}.</div><!--ENDIF:Ky_Han_Thi_Cong-->
  <!--IFNOT:Ky_Han_Thi_Cong--><div>- Thời gian thực hiện: theo thỏa thuận của hai bên, tính từ ngày Bên B nhận tạm ứng.</div><!--ENDIFNOT:Ky_Han_Thi_Cong-->
  <!--IF:Dia_Diem_Thi_Cong--><div>- Địa điểm: {Dia_Diem_Thi_Cong}.</div><!--ENDIF:Dia_Diem_Thi_Cong-->
  <div>- Thời gian thực hiện được kéo dài tương ứng khi có sự kiện bất khả kháng hoặc Bên A chậm thanh toán, chậm bàn giao mặt bằng.</div>

  <p style="margin:8px 0 2px"><b>ĐIỀU 4. BẢO HÀNH</b></p>
  <!--IF:Bao_Hanh--><div style="white-space:pre-line">{Bao_Hanh}</div><!--ENDIF:Bao_Hanh-->
  <!--IFNOT:Bao_Hanh--><div>Bảo hành theo chính sách của nhà sản xuất kể từ ngày nghiệm thu, bàn giao.</div><!--ENDIFNOT:Bao_Hanh-->
  <div>Không bảo hành với hư hỏng do sử dụng sai hướng dẫn, thiên tai, hỏa hoạn hoặc tự ý sửa chữa.</div>

  <p style="margin:8px 0 2px"><b>ĐIỀU 5. QUYỀN VÀ NGHĨA VỤ CỦA CÁC BÊN</b></p>
  <div>- Bên A: thanh toán đúng hạn; bàn giao mặt bằng, tạo điều kiện để Bên B thực hiện; cử người phối hợp nghiệm thu.</div>
  <div>- Bên B: cung cấp đúng chủng loại, số lượng, chất lượng; thực hiện đúng tiến độ; bảo hành theo Điều 4; đảm bảo an toàn, vệ sinh khi thi công.</div>

  <p style="margin:8px 0 2px"><b>ĐIỀU 6. PHẠT VI PHẠM VÀ GIẢI QUYẾT TRANH CHẤP</b></p>
  <div>- Bên vi phạm nghĩa vụ chịu phạt theo thỏa thuận nhưng không quá 8% giá trị phần nghĩa vụ bị vi phạm (Điều 301 Luật Thương mại).</div>
  <div>- Tranh chấp được giải quyết bằng thương lượng; không thương lượng được thì đưa ra Tòa án có thẩm quyền.</div>
  <!--IF:Dieu_Khoan--><p style="margin:8px 0 2px"><b>ĐIỀU 7. THỎA THUẬN KHÁC</b></p><div style="white-space:pre-line">{Dieu_Khoan}</div><!--ENDIF:Dieu_Khoan-->

  <p style="margin:8px 0 2px"><b>ĐIỀU KHOẢN CHUNG</b></p>
  <div>Hợp đồng có hiệu lực kể từ ngày ký, được lập thành 02 bản có giá trị pháp lý như nhau, mỗi bên giữ 01 bản.</div>
  <!--IF:Ghi_Chu--><div style="white-space:pre-line">Ghi chú: {Ghi_Chu}</div><!--ENDIF:Ghi_Chu-->

  <table style="width:100%;margin-top:18px;border-collapse:collapse;page-break-inside:avoid"><tr>
    <td style="width:50%;text-align:center;vertical-align:top"><b>ĐẠI DIỆN BÊN A</b><br/><i>{Chuc_Vu_Khach}</i><br/><i>(Ký, ghi rõ họ tên, đóng dấu)</i><div style="height:116px"></div><b>{Nguoi_Dai_Dien_Khach}</b></td>
    <td style="width:50%;text-align:center;vertical-align:top"><b>ĐẠI DIỆN BÊN B</b><br/><i>{Chuc_Vu_Cua_Hang}</i><br/><i>(Ký, ghi rõ họ tên, đóng dấu)</i><div style="height:116px;overflow:hidden">{Con_Dau}</div><b>{Nguoi_Dai_Dien_Cua_Hang}</b></td>
  </tr></table>
</div>''';

const posA4AcceptanceHtml = r'''<div style="font-family:'Times New Roman',Times,serif;font-size:13px;line-height:1.4;color:#000">
  <table style="width:100%;border-collapse:collapse"><tr>
    <td style="width:42%;vertical-align:top;text-align:center;padding:0">
      <div style="font-weight:bold;text-transform:uppercase">{Ten_Cong_Ty}</div>
      <div>Số: {So_Chung_Tu}</div>
    </td>
    <td style="width:58%;vertical-align:top;text-align:center;padding:0;line-height:1.3">
      <div style="font-weight:bold">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div>
      <div style="font-weight:bold">Độc lập - Tự do - Hạnh phúc</div>
      <div style="border-top:1px solid #000;width:170px;margin:4px auto 4px"></div>
      <div><i>Ngày {Ngay_So} tháng {Thang} năm {Nam}</i></div>
    </td>
  </tr></table>
  <h2 style="text-align:center;font-size:18px;margin:16px 0 2px">BIÊN BẢN NGHIỆM THU HOÀN THÀNH</h2>
  <div style="text-align:center;font-weight:bold;margin-bottom:8px">BÀN GIAO HÀNG HÓA / HẠNG MỤC ĐƯA VÀO SỬ DỤNG</div>
  <p style="margin:4px 0"><!--IF:So_Hop_Dong-->- Căn cứ hợp đồng số <b>{So_Hop_Dong}</b><!--IF:Ngay_Hop_Dong--> ký ngày {Ngay_Hop_Dong}<!--ENDIF:Ngay_Hop_Dong--> giữa {Ben_A_Ten} và {Ten_Cong_Ty};<!--ENDIF:So_Hop_Dong--><!--IFNOT:So_Hop_Dong-->- Căn cứ báo giá số <b>{Ma_Bao_Gia}</b> đã được {Ben_A_Ten} chấp thuận;<!--ENDIFNOT:So_Hop_Dong--></p>
  <p style="margin:4px 0">- Căn cứ khối lượng thực tế Bên B đã hoàn thành.</p>

  <p style="margin:8px 0 2px"><b>1. Thành phần tham gia nghiệm thu</b></p>
  <div><b>Bên A (Chủ đầu tư / bên mua): {Ben_A_Ten}</b></div>
  <div>&nbsp;&nbsp;Ông/Bà: {Nguoi_Dai_Dien_Khach}<!--IF:Chuc_Vu_Khach--> — Chức vụ: {Chuc_Vu_Khach}<!--ENDIF:Chuc_Vu_Khach--><!--IF:SDT--> — ĐT: {SDT}<!--ENDIF:SDT--></div>
  <div><b>Bên B (Nhà thầu / bên bán): {Ten_Cong_Ty}</b></div>
  <div>&nbsp;&nbsp;Ông/Bà: {Nguoi_Dai_Dien_Cua_Hang} — Chức vụ: {Chuc_Vu_Cua_Hang}<!--IF:Dien_Thoai_Cong_Ty--> — ĐT: {Dien_Thoai_Cong_Ty}<!--ENDIF:Dien_Thoai_Cong_Ty--></div>

  <p style="margin:8px 0 2px"><b>2. Thời gian, địa điểm nghiệm thu</b></p>
  <div>- Thời gian: ngày {Ngay}.</div>
  <!--IF:Dia_Diem_Thi_Cong--><div>- Địa điểm: {Dia_Diem_Thi_Cong}.</div><!--ENDIF:Dia_Diem_Thi_Cong-->

  <p style="margin:8px 0 2px"><b>3. Khối lượng, chất lượng hoàn thành</b></p>
  <table style="width:100%;border-collapse:collapse;margin:4px 0;font-size:12px">
    <thead><tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:5px 3px;width:5%">STT</th>
      <th style="border:1px solid #000;padding:5px 4px;text-align:left">Hàng hóa / hạng mục</th>
      <th style="border:1px solid #000;padding:5px 3px;width:8%">ĐVT</th>
      <th style="border:1px solid #000;padding:5px 3px;width:10%">Khối lượng</th>
      <th style="border:1px solid #000;padding:5px 4px;width:15%;text-align:right">Thành tiền</th>
      <th style="border:1px solid #000;padding:5px 3px;width:12%">Đánh giá</th>
    </tr></thead>
    <tbody><!--BEGIN_ITEMS--><tr>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{STT}</td>
      <td style="border:1px solid #000;padding:4px 4px;vertical-align:top">{Ten_Hang_Hoa}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{Don_Vi_Tinh}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{So_Luong}</td>
      <td style="border:1px solid #000;padding:4px 4px;text-align:right;vertical-align:top">{Thanh_Tien}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">Đạt</td>
    </tr><!--END_ITEMS--></tbody>
  </table>
  <div>- Về chất lượng: hàng hóa / hạng mục đúng chủng loại, quy cách, vận hành bình thường, đạt yêu cầu theo hợp đồng.</div>
  <div>- Những tồn tại cần khắc phục (nếu có): {Ton_Tai}</div>

  <p style="margin:8px 0 2px"><b>4. Giá trị quyết toán</b></p>
  <div>Giá trị nghiệm thu: <b>{Tong_Cong} đ</b> (bằng chữ: <i>{Tong_Cong_Bang_Chu}</i>). {Cach_Tinh_VAT}.</div>
  <!--IF:Da_Thanh_Toan--><div>Bên A đã thanh toán: {Da_Thanh_Toan} đ. Còn phải thanh toán: <b>{Con_Phai_Thu} đ</b> (bằng chữ: {Con_Phai_Thu_Bang_Chu}).</div><!--ENDIF:Da_Thanh_Toan-->

  <p style="margin:8px 0 2px"><b>5. Kết luận</b></p>
  <div>Hai bên thống nhất nghiệm thu hoàn thành, Bên B bàn giao để Bên A đưa vào sử dụng. Thời hạn bảo hành tính từ ngày ký biên bản này<!--IF:Bao_Hanh--> ({Bao_Hanh})<!--ENDIF:Bao_Hanh-->.</div>
  <!--IF:Ghi_Chu--><div style="white-space:pre-line">Ý kiến khác: {Ghi_Chu}</div><!--ENDIF:Ghi_Chu-->
  <div>Biên bản lập thành 02 bản có giá trị như nhau, mỗi bên giữ 01 bản.</div>

  <table style="width:100%;margin-top:18px;border-collapse:collapse;page-break-inside:avoid"><tr>
    <td style="width:50%;text-align:center;vertical-align:top"><b>ĐẠI DIỆN BÊN A</b><br/><i>(Ký, ghi rõ họ tên)</i><div style="height:116px"></div><b>{Nguoi_Dai_Dien_Khach}</b></td>
    <td style="width:50%;text-align:center;vertical-align:top"><b>ĐẠI DIỆN BÊN B</b><br/><i>(Ký, ghi rõ họ tên, đóng dấu)</i><div style="height:116px;overflow:hidden">{Con_Dau}</div><b>{Nguoi_Dai_Dien_Cua_Hang}</b></td>
  </tr></table>
</div>''';

const posA4HandoverHtml = r'''<div style="font-family:'Times New Roman',Times,serif;font-size:13px;line-height:1.4;color:#000">
  <table style="width:100%;border-collapse:collapse"><tr>
    <td style="width:42%;vertical-align:top;text-align:center;padding:0">
      <div style="font-weight:bold;text-transform:uppercase">{Ten_Cong_Ty}</div>
      <div>Số: {So_Chung_Tu}</div>
    </td>
    <td style="width:58%;vertical-align:top;text-align:center;padding:0;line-height:1.3">
      <div style="font-weight:bold">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div>
      <div style="font-weight:bold">Độc lập - Tự do - Hạnh phúc</div>
      <div style="border-top:1px solid #000;width:170px;margin:4px auto 4px"></div>
      <div><i>Ngày {Ngay_So} tháng {Thang} năm {Nam}</i></div>
    </td>
  </tr></table>
  <h2 style="text-align:center;font-size:18px;margin:16px 0 8px">BIÊN BẢN BÀN GIAO HÀNG HÓA / CÔNG TRÌNH</h2>
  <p style="margin:4px 0"><!--IF:So_Hop_Dong-->- Căn cứ hợp đồng số <b>{So_Hop_Dong}</b><!--IF:Ngay_Hop_Dong--> ký ngày {Ngay_Hop_Dong}<!--ENDIF:Ngay_Hop_Dong-->;<!--ENDIF:So_Hop_Dong--><!--IFNOT:So_Hop_Dong-->- Căn cứ báo giá số <b>{Ma_Bao_Gia}</b>;<!--ENDIFNOT:So_Hop_Dong--></p>
  <p style="margin:4px 0">Hôm nay, ngày {Ngay}<!--IF:Dia_Diem_Thi_Cong--> tại {Dia_Diem_Thi_Cong}<!--ENDIF:Dia_Diem_Thi_Cong-->, chúng tôi gồm:</p>
  <div><b>BÊN GIAO (Bên B): {Ten_Cong_Ty}</b></div>
  <div>&nbsp;&nbsp;Đại diện: {Nguoi_Dai_Dien_Cua_Hang} — Chức vụ: {Chuc_Vu_Cua_Hang}<!--IF:Dien_Thoai_Cong_Ty--> — ĐT: {Dien_Thoai_Cong_Ty}<!--ENDIF:Dien_Thoai_Cong_Ty--></div>
  <div><b>BÊN NHẬN (Bên A): {Ben_A_Ten}</b></div>
  <div>&nbsp;&nbsp;Đại diện: {Nguoi_Dai_Dien_Khach}<!--IF:Chuc_Vu_Khach--> — Chức vụ: {Chuc_Vu_Khach}<!--ENDIF:Chuc_Vu_Khach--><!--IF:SDT--> — ĐT: {SDT}<!--ENDIF:SDT--></div>
  <p style="margin:8px 0 2px">Bên giao đã bàn giao cho bên nhận các hàng hóa / hạng mục sau:</p>
  <table style="width:100%;border-collapse:collapse;margin:4px 0;font-size:12px">
    <thead><tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:5px 3px;width:5%">STT</th>
      <th style="border:1px solid #000;padding:5px 4px;text-align:left">Hàng hóa / hạng mục</th>
      <th style="border:1px solid #000;padding:5px 3px;width:8%">ĐVT</th>
      <th style="border:1px solid #000;padding:5px 3px;width:9%">Số lượng</th>
      <!--IF:Co_Bao_Hanh_Dong--><th style="border:1px solid #000;padding:5px 3px;width:10%">Bảo hành</th><!--ENDIF:Co_Bao_Hanh_Dong-->
      <th style="border:1px solid #000;padding:5px 3px;width:16%">Tình trạng</th>
    </tr></thead>
    <tbody><!--BEGIN_ITEMS--><tr>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{STT}</td>
      <td style="border:1px solid #000;padding:4px 4px;vertical-align:top">{Ten_Hang_Hoa}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{Don_Vi_Tinh}</td>
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{So_Luong}</td>
      <!--IF:Co_Bao_Hanh_Dong--><td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">{Bao_Hanh}</td><!--ENDIF:Co_Bao_Hanh_Dong-->
      <td style="border:1px solid #000;padding:4px 3px;text-align:center;vertical-align:top">Mới, hoạt động tốt</td>
    </tr><!--END_ITEMS--></tbody>
  </table>
  <div>Kèm theo: hướng dẫn sử dụng, phiếu bảo hành (nếu có).</div>
  <div>Bên nhận đã kiểm tra, đồng ý nhận bàn giao. Kể từ thời điểm ký biên bản, bên nhận chịu trách nhiệm quản lý, sử dụng.</div>
  <!--IF:Ghi_Chu--><div style="white-space:pre-line">Ghi chú: {Ghi_Chu}</div><!--ENDIF:Ghi_Chu-->
  <div>Biên bản lập thành 02 bản có giá trị như nhau, mỗi bên giữ 01 bản.</div>
  <table style="width:100%;margin-top:18px;border-collapse:collapse;page-break-inside:avoid"><tr>
    <td style="width:50%;text-align:center;vertical-align:top"><b>BÊN NHẬN</b><br/><i>(Ký, ghi rõ họ tên)</i><div style="height:116px"></div><b>{Nguoi_Dai_Dien_Khach}</b></td>
    <td style="width:50%;text-align:center;vertical-align:top"><b>BÊN GIAO</b><br/><i>(Ký, ghi rõ họ tên, đóng dấu)</i><div style="height:116px;overflow:hidden">{Con_Dau}</div><b>{Nguoi_Dai_Dien_Cua_Hang}</b></td>
  </tr></table>
</div>''';

const posA4PaymentRequestHtml = r'''<!--NO_ITEMS--><div style="font-family:'Times New Roman',Times,serif;font-size:13px;line-height:1.4;color:#000">
  <table style="width:100%;border-collapse:collapse"><tr>
    <td style="width:42%;vertical-align:top;text-align:center;padding:0">
      <div style="font-weight:bold;text-transform:uppercase">{Ten_Cong_Ty}</div>
      <div>Số: {So_Chung_Tu}</div>
    </td>
    <td style="width:58%;vertical-align:top;text-align:center;padding:0;line-height:1.3">
      <div style="font-weight:bold">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div>
      <div style="font-weight:bold">Độc lập - Tự do - Hạnh phúc</div>
      <div style="border-top:1px solid #000;width:170px;margin:4px auto 4px"></div>
      <div><i>Ngày {Ngay_So} tháng {Thang} năm {Nam}</i></div>
    </td>
  </tr></table>
  <h2 style="text-align:center;font-size:18px;margin:16px 0 2px">GIẤY ĐỀ NGHỊ THANH TOÁN</h2>
  <div style="text-align:center;margin-bottom:8px"><i>(V/v: {De_Nghi_Dot})</i></div>
  <p style="margin:4px 0"><b>Kính gửi: {Ben_A_Ten}</b></p>
  <p style="margin:4px 0"><!--IF:So_Hop_Dong-->Căn cứ hợp đồng số <b>{So_Hop_Dong}</b><!--IF:Ngay_Hop_Dong--> ký ngày {Ngay_Hop_Dong}<!--ENDIF:Ngay_Hop_Dong--> giữa {Ben_A_Ten} và {Ten_Cong_Ty}.<!--ENDIF:So_Hop_Dong--><!--IFNOT:So_Hop_Dong-->Căn cứ báo giá số <b>{Ma_Bao_Gia}</b> đã được Quý khách chấp thuận.<!--ENDIFNOT:So_Hop_Dong--></p>
  <p style="margin:6px 0 2px"><b>1. Giá trị hợp đồng:</b> {Tong_Cong} đ ({Cach_Tinh_VAT}).</p>
  <!--IF:Co_Dot_Thanh_Toan-->
  <p style="margin:6px 0 2px"><b>2. Tình hình thanh toán theo các đợt:</b></p>
  <table style="width:100%;border-collapse:collapse;margin:4px 0;font-size:12px">
    <tr style="background:#f1f5f9">
      <th style="border:1px solid #000;padding:4px;width:7%">Đợt</th>
      <th style="border:1px solid #000;padding:4px;text-align:left">Nội dung</th>
      <th style="border:1px solid #000;padding:4px;width:15%;text-align:right">Phải thanh toán</th>
      <th style="border:1px solid #000;padding:4px;width:15%;text-align:right">Đã thanh toán</th>
      <th style="border:1px solid #000;padding:4px;width:15%;text-align:right">Còn lại</th>
      <!--IF:Co_Han_Dot--><th style="border:1px solid #000;padding:4px;width:12%">Hạn</th><!--ENDIF:Co_Han_Dot-->
    </tr>
    <!--BEGIN_STAGES--><tr>
      <td style="border:1px solid #000;padding:4px;text-align:center">{Dot_STT}</td>
      <td style="border:1px solid #000;padding:4px">{Dot_Ten}</td>
      <td style="border:1px solid #000;padding:4px;text-align:right">{Dot_So_Tien}</td>
      <td style="border:1px solid #000;padding:4px;text-align:right">{Dot_Da_Thu}</td>
      <td style="border:1px solid #000;padding:4px;text-align:right">{Dot_Con_Lai}</td>
      <!--IF:Co_Han_Dot--><td style="border:1px solid #000;padding:4px;text-align:center">{Dot_Han}</td><!--ENDIF:Co_Han_Dot-->
    </tr><!--END_STAGES-->
  </table>
  <!--ENDIF:Co_Dot_Thanh_Toan-->
  <!--IFNOT:Co_Dot_Thanh_Toan-->
  <p style="margin:6px 0 2px"><b>2. Đã thanh toán:</b> {Da_Thanh_Toan_Hien} đ.</p>
  <!--ENDIFNOT:Co_Dot_Thanh_Toan-->
  <p style="margin:8px 0 2px"><b>3. Đề nghị Quý khách thanh toán:</b></p>
  <div>- Nội dung: {De_Nghi_Dot}</div>
  <div>- Số tiền: <b>{De_Nghi_So_Tien} đ</b> (bằng chữ: <i>{De_Nghi_Bang_Chu}</i>)</div>
  <!--IF:Hinh_Thuc_Thanh_Toan--><div>- Hình thức: {Hinh_Thuc_Thanh_Toan}</div><!--ENDIF:Hinh_Thuc_Thanh_Toan-->
  <!--IF:Tai_Khoan_Cua_Hang--><div>- Chuyển khoản tới: {Tai_Khoan_Cua_Hang} — {Ngan_Hang_Cua_Hang} — Chủ TK: {Chu_Tai_Khoan_Cua_Hang}</div><!--ENDIF:Tai_Khoan_Cua_Hang-->
  <div>- Nội dung chuyển khoản: Thanh toán {So_Chung_Tu}</div>
  <!--IF:Ghi_Chu--><div style="white-space:pre-line">Ghi chú: {Ghi_Chu}</div><!--ENDIF:Ghi_Chu-->
  <p style="margin:8px 0">Rất mong Quý khách xem xét và thanh toán đúng tiến độ đã thỏa thuận. Trân trọng!</p>
  <table style="width:100%;margin-top:14px;border-collapse:collapse;page-break-inside:avoid"><tr>
    <td style="width:50%;text-align:center;vertical-align:top"><b>XÁC NHẬN CỦA BÊN A</b><br/><i>(Ký, ghi rõ họ tên)</i><div style="height:116px"></div></td>
    <td style="width:50%;text-align:center;vertical-align:top"><b style="text-transform:uppercase">ĐẠI DIỆN {Ten_Cong_Ty}</b><br/><i>{Chuc_Vu_Cua_Hang}</i><div style="height:116px;overflow:hidden">{Con_Dau}</div><b>{Nguoi_Dai_Dien_Cua_Hang}</b></td>
  </tr></table>
</div>''';
