﻿$f = 'e:\Flutter\ZKTecoADMS-master\ZKTecoADMS-master\flutter_client\lib\screens\system_admin\landing_content_tab.dart'
$s = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$r = [char]0xFFFD

# ---- TAB LABELS ----
$s = $s.Replace("Hero & Li${r}n h?", 'Hero & Liên hệ')
$s = $s.Replace("T${r}nh nang", 'Tính năng')
$s = $s.Replace("G${r}i d?ch v?", 'Gói dịch vụ')
$s = $s.Replace("Hu?ng d?n", 'Hướng dẫn')
$s = $s.Replace("S?n ph?m", 'Sản phẩm')

# ---- LABELS MAP ----
$s = $s.Replace("Ti${r}u d? Hero", 'Tiêu đề Hero')
$s = $s.Replace("M${r} t? Hero", 'Mô tả Hero')
$s = $s.Replace("S? di?n tho?i / Hotline", 'Số điện thoại / Hotline')
$s = $s.Replace("S? Zalo (ho?c link zalo.me/...)", 'Số Zalo (hoặc link zalo.me/...)')
$s = $s.Replace("Email li${r}n h?", 'Email liên hệ')
$s = $s.Replace("${r}?a ch?", 'Địa chỉ')

# ---- HERO CONTACT ----
$s = $s.Replace("${r}${r} luu n?i dung Hero & Li${r}n h?!", 'Đã lưu nội dung Hero & Liên hệ!')
$s = $s.Replace("Th${r}ng tin li${r}n h?", 'Thông tin liên hệ')
$s = $s.Replace("${r}ang luu...", 'Đang lưu...')
$s = $s.Replace("Luu thay d?i", 'Lưu thay đổi')
$s = $s.Replace("N?i dung hi?n th? ? ph?n d?u trang ch?", 'Nội dung hiển thị ở phần đầu trang chủ')
$s = $s.Replace('L?i: $e', 'Lỗi: $e')

# ---- FEATURES ----
$s = $s.Replace("${r}${r} luu danh s${r}ch t${r}nh nang!", 'Đã lưu danh sách tính năng!')
$s = $s.Replace("Danh s${r}ch t${r}nh nang", 'Danh sách tính năng')
$s = $s.Replace("label: const Text('Th${r}m')", "label: const Text('Thêm')")
$s = $s.Replace("Ti${r}u d? t${r}nh nang", 'Tiêu đề tính năng')
$s = $s.Replace("M${r} t? chi ti?t", 'Mô tả chi tiết')
$s = $s.Replace("Luu danh s${r}ch t${r}nh nang", 'Lưu danh sách tính năng')

# ---- PRICING ----
$s = $s.Replace("${r}${r} luu b?ng gi${r}!", 'Đã lưu bảng giá!')
$s = $s.Replace("G${r}i d?ch v? & B?ng gi${r}", 'Gói dịch vụ & Bảng giá')
$s = $s.Replace("Th${r}m g${r}i", 'Thêm gói')
$s = $s.Replace("T${r}n g${r}i", 'Tên gói')
$s = $s.Replace("X${r}a g${r}i", 'Xóa gói')
$s = $s.Replace("Gi${r} (VD: 900.000)", 'Giá (VD: 900.000)')
$s = $s.Replace("${r}on v? (d/nam)", 'Đơn vị (đ/năm)')
$s = $s.Replace("M${r} t? g${r}i", 'Mô tả gói')
$s = $s.Replace("N?i b?t (highlight)", 'Nổi bật (highlight)')
$s = $s.Replace("Li${r}n h? d? b${r}o gi${r}", 'Liên hệ để báo giá')
$s = $s.Replace("T${r}nh nang trong g${r}i", 'Tính năng trong gói')
$s = $s.Replace("Th${r}m t${r}nh nang", 'Thêm tính năng')
$s = $s.Replace('Chua c' + $r + ' t' + $r + 'nh nang. Nh?n "Th' + $r + 'm t' + $r + 'nh nang" d? b? sung.', 'Chưa có tính năng. Nhấn "Thêm tính năng" để bổ sung.')
$s = $s.Replace("VD: T?i da 30 nh${r}n vi${r}n", 'VD: Tối đa 30 nhân viên')
$s = $s.Replace("tooltip: 'X${r}a'", "tooltip: 'Xóa'")
$s = $s.Replace("Luu b?ng gi${r}", 'Lưu bảng giá')

# ---- GUIDE ----
$s = $s.Replace("${r}${r} luu hu?ng d?n!", 'Đã lưu hướng dẫn!')
$s = $s.Replace("C${r}c bu?c hu?ng d?n", 'Các bước hướng dẫn')
$s = $s.Replace("Th${r}m bu?c", 'Thêm bước')
$s = $s.Replace("Ti${r}u d? bu?c", 'Tiêu đề bước')
$s = $s.Replace("Luu hu?ng d?n", 'Lưu hướng dẫn')

# ---- VIDEO ----
$s = $s.Replace("${r}${r} luu c${r}i d?t video!", 'Đã lưu cài đặt video!')
$s = $s.Replace("Video 1 ${r} Gi?i thi?u", 'Video 1 – Giới thiệu')
$s = $s.Replace("Video 2 ${r} Hu?ng d?n", 'Video 2 – Hướng dẫn')
$s = $s.Replace("Ti${r}u d? video", 'Tiêu đề video')
$s = $s.Replace("Nh${r}n (badge)", 'Nhãn (badge)')
$s = $s.Replace("Th?i lu?ng", 'Thời lượng')
$s = $s.Replace("M${r} t? ng?n", 'Mô tả ngắn')
$s = $s.Replace("Luu c${r}i d?t video", 'Lưu cài đặt video')
$s = $s.Replace("URL YouTube (b?t bu?c)", 'URL YouTube (bắt buộc)')
$s = $s.Replace("Video gi?i thi?u", 'Video giới thiệu')
$s = $s.Replace("Video hu?ng d?n", 'Video hướng dẫn')
$s = $s.Replace("H?c ngay", 'Học ngay')
$s = $s.Replace("T${r}ng quan SBOX HRM ${r} ch?m c${r}ng, luong, ca l${r}m, b${r}o c${r}o", 'Tổng quan SBOX HRM – chấm công, lương, ca làm, báo cáo')
$s = $s.Replace("Thi?t l?p t? A${r}Z: k?t n?i m${r}y, th${r}m nh${r}n vi${r}n, c${r}i ca", 'Thiết lập từ A–Z: kết nối máy, thêm nhân viên, cài ca')

# ---- PRODUCTS ----
$s = $s.Replace("${r}${r} luu danh s${r}ch s?n ph?m!", 'Đã lưu danh sách sản phẩm!')
$s = $s.Replace("Danh s${r}ch m${r}y ch?m c${r}ng", 'Danh sách máy chấm công')
$s = $s.Replace("Th${r}m m${r}y", 'Thêm máy')
$s = $s.Replace("Luu danh s${r}ch s?n ph?m", 'Lưu danh sách sản phẩm')
$s = $s.Replace("'S?n ph?m ", "'Sản phẩm ")
$s = $s.Replace("X${r}a s?n ph?m", 'Xóa sản phẩm')
$s = $s.Replace("T${r}n s?n ph?m", 'Tên sản phẩm')
$s = $s.Replace("Thuong hi?u", 'Thương hiệu')
$s = $s.Replace("Gi${r} b${r}n", 'Giá bán')
$s = $s.Replace("Gi${r} g?c (n?u c${r})", 'Giá gốc (nếu có)')
$s = $s.Replace("Nh${r}n gi?m gi${r}", 'Nhãn giảm giá')
$s = $s.Replace("Th${r}ng s? t${r}m t?t", 'Thông số tóm tắt')
$s = $s.Replace("URL ?nh s?n ph?m", 'URL ảnh sản phẩm')
$s = $s.Replace("Link xem chi ti?t", 'Link xem chi tiết')
$s = $s.Replace("M${r} t? ng?n", 'Mô tả ngắn')

# ---- DEFAULT FEATURES DATA ----
$s = $s.Replace("Ch?m c${r}ng ZKTeco", 'Chấm công ZKTeco')
$s = $s.Replace("T${r}ch h?p m${r}y ch?m c${r}ng ZKTeco t? d?ng, d? li?u d?ng b? real-time qua giao th?c ADMS/PUSH.", 'Tích hợp máy chấm công ZKTeco tự động, dữ liệu đồng bộ real-time qua giao thức ADMS/PUSH.')
$s = $s.Replace("Qu?n l${r} ca l${r}m vi?c", 'Quản lý ca làm việc')
$s = $s.Replace("T?o ca linh ho?t, xoay ca, tang ca, ngh? b${r}. H? tr? ca qua d${r}m v${r} l?ch l${r}m vi?c ph?c t?p.", 'Tạo ca linh hoạt, xoay ca, tăng ca, nghỉ bù. Hỗ trợ ca qua đêm và lịch làm việc phức tạp.')
$s = $s.Replace("T${r}nh luong t? d?ng", 'Tính lương tự động')
$s = $s.Replace("T? d?ng t${r}nh luong theo ng${r}y c${r}ng, ph? c?p, thu?ng, kh?u tr? BHXH/thu? TNCN.", 'Tự động tính lương theo ngày công, phụ cấp, thưởng, khấu trừ BHXH/thuế TNCN.')
$s = $s.Replace("Qu?n l${r} ngh? ph${r}p", 'Quản lý nghỉ phép')
$s = $s.Replace("Theo d${r}i ng${r}y ph${r}p, x${r}t duy?t tr?c tuy?n, t?ng h?p b${r}o c${r}o ngh? ph${r}p theo th${r}ng/nam.", 'Theo dõi ngày phép, xét duyệt trực tuyến, tổng hợp báo cáo nghỉ phép theo tháng/năm.')
$s = $s.Replace("Ch?m c${r}ng ngo${r}i hi?n tru?ng", 'Chấm công ngoài hiện trường')
$s = $s.Replace("GPS check-in/check-out c${r} ?nh x${r}c th?c khu${r}n m?t, h? tr? nh${r}n vi${r}n field sales.", 'GPS check-in/check-out có ảnh xác thực khuôn mặt, hỗ trợ nhân viên field sales.')
$s = $s.Replace("B${r}o c${r}o & Ph${r}n t${r}ch", 'Báo cáo & Phân tích')
$s = $s.Replace("Dashboard tr?c quan, b${r}o c${r}o chuy${r}n c?n, t?ng h?p luong, xu?t Excel t?c th${r}.", 'Dashboard trực quan, báo cáo chuyên cần, tổng hợp lương, xuất Excel tức thì.')
$s = $s.Replace("Qu?n l${r} b?a an", 'Quản lý bữa ăn')
$s = $s.Replace("${r}ang k${r} xu?t an, theo d${r}i kh?u ph?n th?c t?, b${r}o c${r}o chi ph${r} b?a an h${r}ng ng${r}y.", 'Đăng ký xuất ăn, theo dõi khẩu phần thực tế, báo cáo chi phí bữa ăn hàng ngày.')
$s = $s.Replace("Qu?n l${r} c${r}ng vi?c", 'Quản lý công việc')
$s = $s.Replace("Giao vi?c, theo d${r}i ti?n d?, KPI c${r} nh${r}n v${r} ph${r}ng ban theo th?i gian th?c.", 'Giao việc, theo dõi tiến độ, KPI cá nhân và phòng ban theo thời gian thực.')
$s = $s.Replace("?ng d?ng Android/iOS d?y d? t${r}nh nang ${r} ch?m c${r}ng, xem l?ch, ph${r} duy?t ngh? ph${r}p m?i noi.", 'Ứng dụng Android/iOS đầy đủ tính năng – chấm công, xem lịch, phê duyệt nghỉ phép mọi nơi.')

# ---- DEFAULT PRICING DATA ----
$s = $s.Replace("Mi?n ph${r}", 'Miễn phí')
$s = $s.Replace("Tr?i nghi?m d?y d? t${r}nh nang co b?n", 'Trải nghiệm đầy đủ tính năng cơ bản')
$s = $s.Replace("T?i da 10 nh${r}n vi${r}n", 'Tối đa 10 nhân viên')
$s = $s.Replace("Ch?m c${r}ng & b${r}o c${r}o co b?n", 'Chấm công & báo cáo cơ bản')
$s = $s.Replace("H? tr? qua email", 'Hỗ trợ qua email')
$s = $s.Replace("H? kinh doanh", 'Hộ kinh doanh')
$s = $s.Replace("D${r}nh cho h? kinh doanh & c?a h${r}ng nh?", 'Dành cho hộ kinh doanh & cửa hàng nhỏ')
$s = $s.Replace("T?i da 30 nh${r}n vi${r}n", 'Tối đa 30 nhân viên')
$s = $s.Replace("Ch?m c${r}ng & ca l${r}m vi?c", 'Chấm công & ca làm việc')
$s = $s.Replace("B${r}o c${r}o chi ti?t", 'Báo cáo chi tiết')
$s = $s.Replace("H? tr? Zalo 24/7", 'Hỗ trợ Zalo 24/7')
$s = $s.Replace("Doanh nghi?p", 'Doanh nghiệp')
$s = $s.Replace("Cho doanh nghi?p v?a v${r} l?n", 'Cho doanh nghiệp vừa và lớn')
$s = $s.Replace("Kh${r}ng gi?i h?n nh${r}n vi${r}n", 'Không giới hạn nhân viên')
$s = $s.Replace("${r}?y d? t${r}nh nang HRM", 'Đầy đủ tính năng HRM')
$s = $s.Replace("KPI & c${r}ng vi?c", 'KPI & công việc')
$s = $s.Replace("Google Sheets sync", 'Google Sheets sync')
$s = $s.Replace("H? tr? uu ti${r}n 24/7", 'Hỗ trợ ưu tiên 24/7')
$s = $s.Replace("Nh${r} m${r}y SX", 'Nhà máy SX')
$s = $s.Replace("T? 1.950.000", 'Từ 1.950.000')
$s = $s.Replace("T?i uu cho nh${r} m${r}y s?n xu?t", 'Tối ưu cho nhà máy sản xuất')
$s = $s.Replace("Kh${r}ng gi?i h?n thi?t b?", 'Không giới hạn thiết bị')
$s = $s.Replace("Ch?m c${r}ng nhi?u ca / d${r}y chuy?n", 'Chấm công nhiều ca / dây chuyền')
$s = $s.Replace("S?n lu?ng & KPI s?n xu?t", 'Sản lượng & KPI sản xuất')
$s = $s.Replace("T${r}ch h?p ERP/Odoo", 'Tích hợp ERP/Odoo')
$s = $s.Replace("B${r}o c${r}o nh${r} m${r}y chuy${r}n s${r}u", 'Báo cáo nhà máy chuyên sâu')
$s = $s.Replace("Tri?n khai t?i ch? (on-premise)", 'Triển khai tại chỗ (on-premise)')
$s = $s.Replace("H? tr? k? thu?t ri${r}ng", 'Hỗ trợ kỹ thuật riêng')

# ---- DEFAULT GUIDE DATA ----
$s = $s.Replace("${r}ang k${r} t${r}i kho?n", 'Đăng ký tài khoản')
$s = $s.Replace("${r}i?n th${r}ng tin doanh nghi?p, nh?n m${r} c?a h${r}ng v${r} t${r}i kho?n admin qua email trong v${r}ng 5 ph${r}t.", 'Điền thông tin doanh nghiệp, nhận mã cửa hàng và tài khoản admin qua email trong vòng 5 phút.')
$s = $s.Replace("C${r}i d?t thi?t b?", 'Cài đặt thiết bị')
$s = $s.Replace("K?t n?i m${r}y ch?m c${r}ng ZKTeco v${r}o m?ng n?i b?, c?u h${r}nh IP server. H? tr? c${r}i d?t t? xa qua Zalo/Teamviewer.", 'Kết nối máy chấm công ZKTeco vào mạng nội bộ, cấu hình IP server. Hỗ trợ cài đặt từ xa qua Zalo/Teamviewer.')
$s = $s.Replace("Th${r}m nh${r}n vi${r}n", 'Thêm nhân viên')
$s = $s.Replace("Nh?p danh s${r}ch nh${r}n vi${r}n, dang k${r} v${r}n tay/khu${r}n m?t. D? li?u t? d?ng d?ng b? xu?ng m${r}y ch?m c${r}ng.", 'Nhập danh sách nhân viên, đăng ký vân tay/khuôn mặt. Dữ liệu tự động đồng bộ xuống máy chấm công.')
$s = $s.Replace("Thi?t l?p ca l${r}m vi?c", 'Thiết lập ca làm việc')
$s = $s.Replace("T?o ca l${r}m vi?c, ph${r}n ca cho nh${r}n vi${r}n/ph${r}ng ban. H? tr? ca c? d?nh, xoay ca v${r} l?ch linh ho?t.", 'Tạo ca làm việc, phân ca cho nhân viên/phòng ban. Hỗ trợ ca cố định, xoay ca và lịch linh hoạt.')
$s = $s.Replace("Xem b${r}o c${r}o", 'Xem báo cáo')
$s = $s.Replace("B${r}o c${r}o ch?m c${r}ng, luong, ngh? ph${r}p c?p nh?t t? d?ng. Xu?t Excel/PDF ch? v?i 1 c${r} nh?p.", 'Báo cáo chấm công, lương, nghỉ phép cập nhật tự động. Xuất Excel/PDF chỉ với 1 cú nhấp.')

# ---- DEFAULT PRODUCTS DATA ----
$s = $s.Replace("M${r}y ch?m c${r}ng v${r}n tay WiFi", 'Máy chấm công vân tay WiFi')
$s = $s.Replace("V${r}n tay ${r} WiFi ${r} 500 users", 'Vân tay – WiFi – 500 users')
$s = $s.Replace("Nh?n di?n khu${r}n m?t", 'Nhận diện khuôn mặt')
$s = $s.Replace("Khu${r}n m?t ${r} V${r}n tay ${r} Th? ${r} WiFi", 'Khuôn mặt – Vân tay – Thẻ – WiFi')
$s = $s.Replace("M${r}y ch?m c${r}ng v${r}n tay ADMS", 'Máy chấm công vân tay ADMS')
$s = $s.Replace("V${r}n tay ${r} Th? ${r} TCP/IP ${r} ADMS", 'Vân tay – Thẻ – TCP/IP – ADMS')
$s = $s.Replace("Nh?n di?n khu${r}n m?t ADMS", 'Nhận diện khuôn mặt ADMS')
$s = $s.Replace("Khu${r}n m?t ${r} V${r}n tay ${r} Th? ${r} ADMS", 'Khuôn mặt – Vân tay – Thẻ – ADMS')
$s = $s.Replace("Gi?m 12%", 'Giảm 12%')
$s = $s.Replace("Gi?m 8%", 'Giảm 8%')
$s = $s.Replace("Gi?m 16%", 'Giảm 16%')

# ---- REMAINING ?-only strings ----
$s = $s.Replace("1 thi?t b? ZKTeco", '1 thiết bị ZKTeco')
$s = $s.Replace("2 thi?t b? ZKTeco", '2 thiết bị ZKTeco')
$s = $s.Replace("5 thi?t b? ZKTeco", '5 thiết bị ZKTeco')
$s = $s.Replace("App mobile", 'App mobile')
$s = $s.Replace("d/nam", 'đ/năm')

# ---- COMMENT CLEANUP (optional but nice) ----
$s = $s.Replace("Sub-tab 1: Hero & Li${r}n h?", 'Sub-tab 1: Hero & Liên hệ')
$s = $s.Replace("Sub-tab 2: T${r}nh nang", 'Sub-tab 2: Tính năng')
$s = $s.Replace("Sub-tab 3: G${r}i d?ch v?", 'Sub-tab 3: Gói dịch vụ')
$s = $s.Replace("Sub-tab 4: Hu?ng d?n", 'Sub-tab 4: Hướng dẫn')
$s = $s.Replace("Sub-tab 6: S?n ph?m", 'Sub-tab 6: Sản phẩm')
$s = $s.Replace("Specs Editor Dialog ${r} controller ho${r}n to${r}n thu?c v? Dialog State", 'Specs Editor Dialog – controller hoàn toàn thuộc về Dialog State')

[System.IO.File]::WriteAllText($f, $s, [System.Text.UTF8Encoding]::new($false))
Write-Host "Done. Length: $($s.Length)"
