-- Sync all module display names to match seed values
UPDATE "Permissions" SET "ModuleDisplayName" = 'Trang chủ', "Description" = 'Màn hình tổng quan menu', "DisplayOrder" = 1 WHERE "Module" = 'Home';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thông báo', "Description" = 'Hệ thống thông báo', "DisplayOrder" = 2 WHERE "Module" = 'Notification';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Tổng quan', "Description" = 'Bảng điều khiển tổng quan', "DisplayOrder" = 3 WHERE "Module" = 'Dashboard';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Hồ sơ nhân sự', "Description" = 'Thông tin nhân viên, chức vụ', "DisplayOrder" = 4 WHERE "Module" = 'Employee';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Nhân sự chấm công', "Description" = 'Nhân sự trên máy chấm công', "DisplayOrder" = 5 WHERE "Module" = 'DeviceUser';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Phòng ban', "Description" = 'Quản lý phòng ban', "DisplayOrder" = 6 WHERE "Module" = 'Department';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Nghỉ phép', "Description" = 'Quản lý nghỉ phép', "DisplayOrder" = 7 WHERE "Module" = 'Leave';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thiết lập lương', "Description" = 'Cấu hình bảng lương', "DisplayOrder" = 8 WHERE "Module" = 'SalarySettings';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Chấm công', "Description" = 'Dữ liệu chấm công', "DisplayOrder" = 9 WHERE "Module" = 'Attendance';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Lịch làm việc', "Description" = 'Phân lịch làm việc', "DisplayOrder" = 10 WHERE "Module" = 'WorkSchedule';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Tổng hợp chấm công', "Description" = 'Bảng tổng hợp chấm công', "DisplayOrder" = 11 WHERE "Module" = 'AttendanceSummary';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Tổng hợp theo ca', "Description" = 'Chấm công theo ca làm việc', "DisplayOrder" = 12 WHERE "Module" = 'AttendanceByShift';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Duyệt chấm công', "Description" = 'Duyệt điều chỉnh chấm công', "DisplayOrder" = 13 WHERE "Module" = 'AttendanceApproval';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Duyệt lịch làm việc', "Description" = 'Duyệt lịch làm việc đăng ký', "DisplayOrder" = 14 WHERE "Module" = 'ScheduleApproval';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Tổng hợp lương', "Description" = 'Bảng lương nhân viên', "DisplayOrder" = 15 WHERE "Module" = 'Payroll';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thưởng / Phạt', "Description" = 'Quản lý thưởng phạt', "DisplayOrder" = 16 WHERE "Module" = 'BonusPenalty';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Phiếu phạt', "Description" = 'Phiếu phạt tự động từ chấm công', "DisplayOrder" = 27 WHERE "Module" = 'PenaltyTickets';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Ứng lương', "Description" = 'Quản lý ứng lương', "DisplayOrder" = 17 WHERE "Module" = 'AdvanceRequests';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thu chi', "Description" = 'Quản lý thu chi', "DisplayOrder" = 18 WHERE "Module" = 'CashTransaction';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Tài sản', "Description" = 'Quản lý tài sản', "DisplayOrder" = 19 WHERE "Module" = 'Asset';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Công việc', "Description" = 'Quản lý công việc', "DisplayOrder" = 20 WHERE "Module" = 'Task';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Truyền thông', "Description" = 'Truyền thông nội bộ', "DisplayOrder" = 21 WHERE "Module" = 'Communication';
UPDATE "Permissions" SET "ModuleDisplayName" = 'KPI', "Description" = 'Đánh giá KPI', "DisplayOrder" = 22 WHERE "Module" = 'KPI';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Sản lượng', "Description" = 'Nhập sản lượng, tính lương sản phẩm', "DisplayOrder" = 43 WHERE "Module" = 'Production';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Đăng ký chấm công Mobile', "Description" = 'Quản lý đăng ký thiết bị chấm công mobile', "DisplayOrder" = 46 WHERE "Module" = 'MobileDeviceRegistration';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Duyệt chấm công Mobile', "Description" = 'Duyệt yêu cầu chấm công mobile', "DisplayOrder" = 47 WHERE "Module" = 'MobileAttendanceApproval';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Chấm cơm', "Description" = 'Quản lý suất ăn ca', "DisplayOrder" = 48 WHERE "Module" = 'Meal';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Check-in điểm bán', "Description" = 'Quản lý check-in tại điểm bán hàng', "DisplayOrder" = 49 WHERE "Module" = 'FieldCheckIn';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Báo cáo nhân sự', "Description" = 'Thống kê nhân sự, phòng ban', "DisplayOrder" = 23 WHERE "Module" = 'HrReport';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Báo cáo chấm công', "Description" = 'Ngày, tháng, đi muộn, phòng ban', "DisplayOrder" = 24 WHERE "Module" = 'AttendanceReport';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Báo cáo lương', "Description" = 'Chi phí lương, phân bổ', "DisplayOrder" = 25 WHERE "Module" = 'PayrollReport';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thiết lập HRM', "Description" = 'Trung tâm cài đặt HRM', "DisplayOrder" = 26 WHERE "Module" = 'SettingsHub';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thiết lập ca', "Description" = 'Ca làm việc, vào sớm, đi trễ, về sớm, tăng ca', "DisplayOrder" = 27 WHERE "Module" = 'ShiftSetup';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Chấm công mobile', "Description" = 'Face ID, GPS, vùng chấm công', "DisplayOrder" = 28 WHERE "Module" = 'MobileAttendance';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Ngày lễ', "Description" = 'Ngày nghỉ lễ, hệ số công', "DisplayOrder" = 29 WHERE "Module" = 'Holiday';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Máy chấm công', "Description" = 'Kết nối, quản lý, điều khiển máy chấm công', "DisplayOrder" = 30 WHERE "Module" = 'Device';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Phụ cấp', "Description" = 'Phụ cấp cố định, phụ cấp ngày công', "DisplayOrder" = 31 WHERE "Module" = 'Allowance';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Phạt', "Description" = 'Đi trễ, về sớm, tái phạm, kỷ luật', "DisplayOrder" = 32 WHERE "Module" = 'PenaltySetup';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Bảo hiểm', "Description" = 'BHXH, BHYT, BHTN, lương cơ sở', "DisplayOrder" = 33 WHERE "Module" = 'Insurance';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thuế TNCN', "Description" = 'Bậc thuế, giảm trừ gia cảnh', "DisplayOrder" = 34 WHERE "Module" = 'Tax';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Tài khoản', "Description" = 'Người dùng, kích hoạt, vai trò', "DisplayOrder" = 35 WHERE "Module" = 'UserManagement';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Phân quyền', "Description" = 'Ma trận quyền, vai trò, module', "DisplayOrder" = 36 WHERE "Module" = 'Role';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Hệ thống', "Description" = 'Giờ kết thúc ngày, tham số vận hành', "DisplayOrder" = 38 WHERE "Module" = 'SystemSettings';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Thiết lập thông báo', "Description" = 'Nhóm thông báo, bật/tắt nhận thông báo', "DisplayOrder" = 39 WHERE "Module" = 'NotificationSettings';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Google Drive', "Description" = 'Lưu trữ ảnh, service account', "DisplayOrder" = 40 WHERE "Module" = 'GoogleDrive';
UPDATE "Permissions" SET "ModuleDisplayName" = 'AI Gemini', "Description" = 'API key, model, tham số AI', "DisplayOrder" = 41 WHERE "Module" = 'AIGemini';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Cài đặt', "Description" = 'Cài đặt hệ thống', "DisplayOrder" = 42 WHERE "Module" = 'Settings';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Lương sản phẩm', "Description" = 'Nhóm sản phẩm, sản phẩm, đơn giá theo bậc', "DisplayOrder" = 44 WHERE "Module" = 'ProductSalary';
UPDATE "Permissions" SET "ModuleDisplayName" = 'Phản ánh / Ý kiến', "Description" = 'Phản ánh, góp ý ẩn danh hoặc công khai', "DisplayOrder" = 45 WHERE "Module" = 'Feedback';

-- Delete DepartmentPermission module if it somehow still exists
DELETE FROM "RolePermissions" WHERE "PermissionId" IN (SELECT "Id" FROM "Permissions" WHERE "Module" = 'DepartmentPermission');
DELETE FROM "Permissions" WHERE "Module" = 'DepartmentPermission';
