#!/usr/bin/env python3
"""Fix corrupted Vietnamese strings in leave_screen.dart."""
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "lib/screens/leave_screen.dart"
text = path.read_text(encoding="utf-8", errors="replace")

replacements = [
    ("Text('T?ng quan & b? l?c'", "Text('Tổng quan & bộ lọc'"),
    ("tooltip: 'Quy d?nh ngh? ph", "tooltip: 'Quy định nghỉ ph"),
    ("_buildStatCard('L? t?t'", "_buildStatCard('Nghỉ lễ, Tết'"),
    ("1: 'L? t?t'", "1: 'Nghỉ lễ, Tết'"),
    ("2: 'VR c", "2: 'Việc riêng c"),
    ("3: 'VR kh", "3: 'Việc riêng kh"),
    ("4: '?m dau'", "4: 'Nghỉ ốm'"),
    ("5: 'Thai s?n'", "5: 'Thai sản'"),
    ("6: 'Ngh? b", "6: 'Nghỉ b"),
    ("7: 'Ngh? d", "7: 'Nghỉ d"),
    ("return 'Toàn b?'", "return 'Toàn bộ'"),
    ("return 'T?t c? NV'", "return 'Tất cả NV'"),
    ("title: const Text('T?t c? nh", "title: const Text('Tất cả nh"),
    ("title: 'Lo?i ngh?'", "title: 'Loại nghỉ'"),
    ("title: 'Tr?ng thái'", "title: 'Trạng thái'"),
    ("title: 'Th?i gian'", "title: 'Thời gian'"),
    ("(label: 'Toàn b?'", "(label: 'Toàn bộ'"),
    ("title: 'S? don'", "title: 'Số đơn'"),
    ("title: 'B? l?c'", "title: 'Bộ lọc'"),
    ("'Chua l?c'", "'Chưa lọc'"),
    ("} c?p'", "} cấp'"),
    ("'Hi?n th? ", "'Hiển thị "),
    ("Text('Hi?n th?:'", "Text('Hiển thị:'"),
    ("label: 'S?a'", "label: 'Sửa'"),
    ("label: 'H?y'", "label: 'Hủy'"),
    ("label: 'Duy?t'", "label: 'Duyệt'"),
    ("label: 'T? ch?i'", "label: 'Từ chối'"),
    ("'Duy?t ", "'Duyệt "),
    ("'Ti?n tr", "'Tiến tr"),
    ("'L?ch s? ph", "'Lịch sử ph"),
    ("'C?p ", "'Cấp "),
    ("'Th?c hi?n", "'Thực hiện"),
    ("'Lo?i ngh?'", "'Loại nghỉ'"),
    ("'Chi tr?'", "'Chi trả'"),
    ("'Gi?y BHXH'", "'Giấy BHXH'"),
    ("'S? ng", "'Số ng"),
    ("' (N?a ca)'", "' (Nửa ca)'"),
    ("'Ngu?i thay'", "'Người thay'"),
    ("'C?p nh?t'", "'Cập nhật'"),
    ("title: const Text('Ngh? ph", "title: const Text('Nghỉ ph"),
    ("'1. Doanh nghi?p tr? luong", "'1. Doanh nghiệp trả lương"),
    (
        "'   Phép nam, l?, vi?c riêng có luong, ngh? bù, ?m dùng phép nam.",
        "'   Phép năm, lễ, việc riêng có lương, nghỉ bù, ốm dùng phép năm.",
    ),
    ("'2. Không hu?ng luong", "'2. Không hưởng lương"),
    (
        "'   Vi?c riêng không luong, ngh? dài h?n không luong.",
        "'   Việc riêng không lương, nghỉ dài hạn không lương.",
    ),
    ("'3. BHXH & d?c bi?t", "'3. BHXH & đặc biệt"),
    (
        "'   ?m hu?ng BHXH (c?n gi?y ngh?), thai s?n DN + d?i soát BHXH.",
        "'   Ốm hưởng BHXH (cần giấy nghỉ), thai sản DN + đối soát BHXH.",
    ),
    (
        "'M?i ngày ngh? ch? m?t ch? d? — không v?a luong DN v?a tr? c?p BHXH.",
        "'Mỗi ngày nghỉ chỉ một chế độ — không vừa lương DN vừa trợ cấp BHXH.",
    ),
    (
        "'Ca ngh?: theo Thi?t l?p luong. Ngu?i thay ca: cùng phòng ban.'",
        "'Ca nghỉ: theo Thiết lập lương. Người thay ca: cùng phòng ban.'",
    ),
    ("title: 'H?y don ngh? ph", "title: 'Hủy đơn nghỉ ph"),
    (
        "content: 'B?n có ch?c ch?n mu?n h?y don ngh? phép này?'",
        "content: 'Bạn có chắc chắn muốn hủy đơn nghỉ phép này?'",
    ),
    ("confirmText: 'H?y don'", "confirmText: 'Hủy đơn'"),
    ("'Đã h?y don ngh? ph", "'Đã hủy đơn nghỉ ph"),
    ("'L?i khi h?y don'", "'Lỗi khi hủy đơn'"),
    ("title: 'Hoàn tác duy?t'", "title: 'Hoàn tác duyệt'"),
    (
        "'B?n có ch?c ch?n mu?n hoàn tác tr?ng thái don ngh? phép này v? Ch? duy?t?",
        "'Bạn có chắc chắn muốn hoàn tác trạng thái đơn nghỉ phép này về Chờ duyệt?",
    ),
    (
        "'H? th?ng s? khôi ph?c l?ch làm vi?c n?u don dã du?c duy?t.'",
        "'Hệ thống sẽ khôi phục lịch làm việc nếu đơn đã được duyệt.'",
    ),
    ("'Đã hoàn tác tr?ng thái don'", "'Đã hoàn tác trạng thái đơn'"),
    ("'L?i khi hoàn tác'", "'Lỗi khi hoàn tác'"),
    ("title: 'Xóa don ngh? ph", "title: 'Xóa đơn nghỉ ph"),
    (
        "'B?n có ch?c ch?n mu?n xóa vinh vi?n don ngh? phép này?",
        "'Bạn có chắc chắn muốn xóa vĩnh viễn đơn nghỉ phép này?",
    ),
    ("'Hành d?ng này không th? hoàn tác.'", "'Hành động này không thể hoàn tác.'"),
    ("'Đã xóa don ngh? ph", "'Đã xóa đơn nghỉ ph"),
    ("'L?i khi xóa don'", "'Lỗi khi xóa đơn'"),
    ("Text('Duy?t don ngh? ph", "Text('Duyệt đơn nghỉ ph"),
    ("child: const Text('H?y')", "child: const Text('Hủy')"),
    ("child: const Text('Duy?t')", "child: const Text('Duyệt')"),
    ("'Đã duy?t don ngh? ph", "'Đã duyệt đơn nghỉ ph"),
    ("'L?i khi duy?t don'", "'Lỗi khi duyệt đơn'"),
    ("confirmLabel: 'T? ch?i'", "confirmLabel: 'Từ chối'"),
    ("'Đã t? ch?i don ngh? ph", "'Đã từ chối đơn nghỉ ph"),
    ("'L?i khi t? ch?i don'", "'Lỗi khi từ chối đơn'"),
    ("title: 'L?i'", "title: 'Lỗi'"),
    ("'Ch? duy?t'", "'Chờ duyệt'"),
    ("'Đã duy?t'", "'Đã duyệt'"),
    ("'T? ch?i'", "'Từ chối'"),
    ("'Đã h?y'", "'Đã hủy'"),
    ("'Phép nam'", "'Phép năm'"),
    ("'VR có luong'", "'Việc riêng có lương'"),
    ("'VR không luong'", "'Việc riêng không lương'"),
    ("'?m dau'", "'Nghỉ ốm'"),
    ("'Thai s?n'", "'Thai sản'"),
    ("'Ngh? bù'", "'Nghỉ bù'"),
    ("'Ngh? dài h?n'", "'Nghỉ dài hạn'"),
    ("'L? t?t'", "'Nghỉ lễ, Tết'"),
    ("'Có luong'", "'Có lương'"),
    ("format(startDate)} ? ${DateFormat", "format(startDate)} → ${DateFormat"),
    ("// quy?n xóa", "// quyền xóa"),
    (
        "// NV xóa don pending c?a mình; QL xóa trên tab qu?n lý",
        "// NV xóa đơn pending của mình; QL xóa trên tab quản lý",
    ),
    ("// T?ng quan + b? l?c", "// Tổng quan + bộ lọc"),
]

for old, new in replacements:
    text = text.replace(old, new)

path.write_text(text, encoding="utf-8", newline="\n")
print(f"Fixed {path}")
