#!/usr/bin/env python3
"""Fix corrupted Vietnamese strings in leave_screen.dart (v2)."""
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "lib/screens/leave_screen.dart"
text = path.read_text(encoding="utf-8", errors="replace")

replacements = [
    ("// Tổng quan + bộ lọc (?n/hi?n cng nhau)", "// Tổng quan + bộ lọc (ẩn/hiện cùng nhau)"),
    ("no NestedScrollView).", "no NestedScrollView)."),
    ("'C\uFFFD luong'", "'Có lương'"),
    ("'C luong'", "'Có lương'"),
    ("// FILTER BAR (3 h\uFFFDng \uFFFD 2 chip)", "// FILTER BAR (3 hàng × 2 chip)"),
    ("// FILTER BAR (3 hng 2 chip)", "// FILTER BAR (3 hàng × 2 chip)"),
    ("}${f.format(_filterDateRange!.end)}", "} → ${f.format(_filterDateRange!.end)}"),
    ("'${q.substring(0, 22)}\uFFFD'", "'${q.substring(0, 22)}…'"),
    ("'${q.substring(0, 22)}'", "'${q.substring(0, 22)}…'"),
    ("title: 'Chi nh\uFFFDnh'", "title: 'Chi nhánh'"),
    ("title: 'Chi nhnh'", "title: 'Chi nhánh'"),
    ("'C\uFFFDn ", "'Còn "),
    ("'Cn ", "'Còn "),
    ("''", "'—'"),
    ("label: Text('Thao t\uFFFDc')", "label: Text('Thao tác')"),
    ("label: Text('Thao tc')", "label: Text('Thao tác')"),
    ("child: const Text('\uFFFD'", "child: const Text('⋯'"),
    ("child: const Text(''", "child: const Text('⋯'"),
    ("// LEAVE CARD \uFFFD 3 d\uFFFDng", "// LEAVE CARD — 3 dòng"),
    ("// LEAVE CARD 3 dng", "// LEAVE CARD — 3 dòng"),
    ("(t\uFFFDn \uFFFD lo?i \uFFFD ngày ngh?)", "(tên · loại · ngày nghỉ)"),
    ("(tn lo?i ngày ngh?)", "(tên · loại · ngày nghỉ)"),
    ("return 'Chua c\uFFFD ngày ngh?';", "return 'Chưa có ngày nghỉ';"),
    ("return 'Chua c ngày ngh?';", "return 'Chưa có ngày nghỉ';"),
    ("return '$startStr \uFFFD 1 ngày$halfNote';", "return '$startStr · 1 ngày$halfNote';"),
    ("return '$startStr 1 ngày$halfNote';", "return '$startStr · 1 ngày$halfNote';"),
    ("return '$startStr ? ${fmt.format(effectiveEnd)} \uFFFD $dayCount ngày$halfNote';",
     "return '$startStr → ${fmt.format(effectiveEnd)} · $dayCount ngày$halfNote';"),
    ("return '$startStr ? ${fmt.format(effectiveEnd)} $dayCount ngày$halfNote';",
     "return '$startStr → ${fmt.format(effectiveEnd)} · $dayCount ngày$halfNote';"),
    ("// D\uFFFDng 1 \uFFFD nh\uFFFDn vi\uFFFDn + trạng thái", "// Dòng 1 — nhân viên + trạng thái"),
    ("// Dng 1 nhn vin + trạng thái", "// Dòng 1 — nhân viên + trạng thái"),
    ("// D\uFFFDng 2 \uFFFD lo?i ngh?", "// Dòng 2 — loại nghỉ"),
    ("// Dng 2 lo?i ngh?", "// Dòng 2 — loại nghỉ"),
    ("// D\uFFFDng 3 \uFFFD ngày xin ngh? (d? dd/MM/yyyy)", "// Dòng 3 — ngày xin nghỉ (đủ dd/MM/yyyy)"),
    ("// Dng 3 ngày xin ngh? (d? dd/MM/yyyy)", "// Dòng 3 — ngày xin nghỉ (đủ dd/MM/yyyy)"),
    ("// Delete: c\uFFFD quy?n x\uFFFDa", "// Delete: có quyền xóa"),
    ("// Delete: c quy?n xa", "// Delete: có quyền xóa"),
    ("label: 'X\uFFFDa'", "label: 'Xóa'"),
    ("label: 'Xa'", "label: 'Xóa'"),
    ("'T\uFFFDnh c\uFFFDng'", "'Tính công'"),
    ("'Tnh cng'", "'Tính công'"),
    ("'Có · không ghi Phép tr\uFFFDn ch?m c\uFFFDng'", "'Có · không ghi Phép trên chấm công'"),
    ("'Có · không ghi Phép trn ch?m cng'", "'Có · không ghi Phép trên chấm công'"),
    ("'T? ngày'", "'Từ ngày'"),
    ("'\uFFFD?n ngày'", "'Đến ngày'"),
    ("'?n ngày'", "'Đến ngày'"),
    ("'Lý do t? ch?i'", "'Lý do từ chối'"),
    ("'Cấp nh?t'", "'Cập nhật'"),
    ("'Tiến tr\uFFFDnh duy?t: $currentStep/$totalLevels cấp'", "'Tiến trình duyệt: $currentStep/$totalLevels cấp'"),
    ("'Tiến trnh duy?t: $currentStep/$totalLevels cấp'", "'Tiến trình duyệt: $currentStep/$totalLevels cấp'"),
    ("'Lịch sử ph\uFFFD duy?t'", "'Lịch sử phê duyệt'"),
    ("'Lịch sử ph duy?t'", "'Lịch sử phê duyệt'"),
    ("'Ph\uFFFDn c\uFFFDng: $assignedUser'", "'Phân công: $assignedUser'"),
    ("'Phn cng: $assignedUser'", "'Phân công: $assignedUser'"),
    ("title: const Text('Ngh\uFFFD ph\uFFFDp theo ph\uFFFDp lu?t')", "title: const Text('Nghỉ phép theo pháp luật')"),
    ("title: const Text('Ngh php theo php lu?t')", "title: const Text('Nghỉ phép theo pháp luật')"),
    ("'   Phép năm, l?, vi?c ri\uFFFDng có lương, ngh? b\uFFFD, ?m d\uFFFDng phép năm.\\n\\n'",
     "'   Phép năm, lễ, việc riêng có lương, nghỉ bù, ốm dùng phép năm.\\n\\n'"),
    ("'   Phép năm, l?, vi?c ring có lương, ngh? b, ?m dng phép năm.\\n\\n'",
     "'   Phép năm, lễ, việc riêng có lương, nghỉ bù, ốm dùng phép năm.\\n\\n'"),
    ("'   Vi?c ri\uFFFDng không lương, ngh? dài h?n không lương.\\n\\n'",
     "'   Việc riêng không lương, nghỉ dài hạn không lương.\\n\\n'"),
    ("'   Vi?c ring không lương, ngh? dài h?n không lương.\\n\\n'",
     "'   Việc riêng không lương, nghỉ dài hạn không lương.\\n\\n'"),
    ("'   ?m hu?ng BHXH (c?n gi?y ngh?), thai s?n DN + d?i so\uFFFDt BHXH.\\n\\n'",
     "'   Ốm hưởng BHXH (cần giấy nghỉ), thai sản DN + đối soát BHXH.\\n\\n'"),
    ("'   ?m hu?ng BHXH (c?n gi?y ngh?), thai s?n DN + d?i sot BHXH.\\n\\n'",
     "'   Ốm hưởng BHXH (cần giấy nghỉ), thai sản DN + đối soát BHXH.\\n\\n'"),
    ("'M?i ngày ngh? ch? m?t ch? d? \uFFFD kh\uFFFDng v?a lương DN v?a tr? c\uFFFDp BHXH.\\n'",
     "'Mỗi ngày nghỉ chỉ một chế độ — không vừa lương DN vừa trợ cấp BHXH.\\n'"),
    ("'M?i ngày ngh? ch? m?t ch? d? kh\uFFFDng v?a lương DN v?a tr? c\uFFFDp BHXH.\\n'",
     "'Mỗi ngày nghỉ chỉ một chế độ — không vừa lương DN vừa trợ cấp BHXH.\\n'"),
    ("'Ca ngh?: theo Thi?t l?p lương. Ngu?i thay ca: c\uFFFDng ph\uFFFDng ban.'",
     "'Ca nghỉ: theo Thiết lập lương. Người thay ca: cùng phòng ban.'"),
    ("'Ca ngh?: theo Thi?t l?p lương. Ngu?i thay ca: cng phng ban.'",
     "'Ca nghỉ: theo Thiết lập lương. Người thay ca: cùng phòng ban.'"),
    ("title: 'H?y đơn nghỉ phép'", "title: 'Hủy đơn nghỉ phép'"),
    ("content: 'Bạn có chắc chắn mu?n h?y đơn nghỉ phép n\uFFFDy?'",
     "content: 'Bạn có chắc chắn muốn hủy đơn nghỉ phép này?'"),
    ("content: 'Bạn có chắc chắn mu?n h?y đơn nghỉ phép ny?'",
     "content: 'Bạn có chắc chắn muốn hủy đơn nghỉ phép này?'"),
    ("'Bạn có chắc chắn mu?n hoàn tác trạng thái đơn nghỉ phép n\uFFFDy v? Ch? duy?t?\\nH? th?ng s? kh\uFFFDi ph?c l?ch l\uFFFDm vi?c n?u don d\uFFFD du?c duy?t.'",
     "'Bạn có chắc chắn muốn hoàn tác trạng thái đơn nghỉ phép này về Chờ duyệt?\\nHệ thống sẽ khôi phục lịch làm việc nếu đơn đã được duyệt.'"),
    ("'Bạn có chắc chắn mu?n hoàn tác trạng thái đơn nghỉ phép ny v? Ch? duy?t?\\nH? th?ng s? khi ph?c l?ch lm vi?c n?u don d du?c duy?t.'",
     "'Bạn có chắc chắn muốn hoàn tác trạng thái đơn nghỉ phép này về Chờ duyệt?\\nHệ thống sẽ khôi phục lịch làm việc nếu đơn đã được duyệt.'"),
    ("' hoàn tác trạng thái don'", "'Đã hoàn tác trạng thái đơn'"),
    ("'Bạn có chắc chắn mu?n xóa vĩnh viễn đơn nghỉ phép n\uFFFDy?\\nHành động n\uFFFDy kh\uFFFDng th? hoàn tác.'",
     "'Bạn có chắc chắn muốn xóa vĩnh viễn đơn nghỉ phép này?\\nHành động này không thể hoàn tác.'"),
    ("'Bạn có chắc chắn mu?n xóa vĩnh viễn đơn nghỉ phép ny?\\nHành động ny khng th? hoàn tác.'",
     "'Bạn có chắc chắn muốn xóa vĩnh viễn đơn nghỉ phép này?\\nHành động này không thể hoàn tác.'"),
    ("confirmText: 'X\uFFFDa'", "confirmText: 'Xóa'"),
    ("confirmText: 'Xa'", "confirmText: 'Xóa'"),
    ("' x\uFFFDa đơn nghỉ phép'", "'Đã xóa đơn nghỉ phép'"),
    ("' xa đơn nghỉ phép'", "'Đã xóa đơn nghỉ phép'"),
    ("'L?i khi x\uFFFDa don'", "'Lỗi khi xóa đơn'"),
    ("'L?i khi xa don'", "'Lỗi khi xóa đơn'"),
    ("'S? tr? $daysNeeded ngày ph\uFFFDp nam. C\uFFFDn l?i: $balanceRemaining ngày.'",
     "'Sẽ trừ $daysNeeded ngày phép năm. Còn lại: $balanceRemaining ngày.'"),
    ("'S? tr? $daysNeeded ngày php nam. Cn l?i: $balanceRemaining ngày.'",
     "'Sẽ trừ $daysNeeded ngày phép năm. Còn lại: $balanceRemaining ngày.'"),
    ("'Ph\uFFFDp duy?t nhung v?n t\uFFFDnh c\uFFFDng'", "'Phép duyệt nhưng vẫn tính công'"),
    ("'Php duy?t nhung v?n tnh cng'", "'Phép duyệt nhưng vẫn tính công'"),
    ("'Không ghi \"Ph\uFFFDp\" tr\uFFFDn b?ng ch?m c\uFFFDng'", "'Không ghi \"Phép\" trên bảng chấm công'"),
    ("'Không ghi \"Php\" trn b?ng ch?m cng'", "'Không ghi \"Phép\" trên bảng chấm công'"),
    ("const Text('T? ch?i đơn nghỉ phép')", "const Text('Từ chối đơn nghỉ phép')"),
    ("const Text('Vui l\uFFFDng nh?p l\uFFFD do t? ch?i:')", "const Text('Vui lòng nhập lý do từ chối:')"),
    ("const Text('Vui lng nh?p l do t? ch?i:')", "const Text('Vui lòng nhập lý do từ chối:')"),
    ("hintText: 'Lý do t? ch?i...'", "hintText: 'Lý do từ chối...'"),
    ("title: 'Thi?u th\uFFFDng tin'", "title: 'Thiếu thông tin'"),
    ("title: 'Thi?u thng tin'", "title: 'Thiếu thông tin'"),
    ("message: 'Vui l\uFFFDng nh?p l\uFFFD do t? ch?i'", "message: 'Vui lòng nhập lý do từ chối'"),
    ("message: 'Vui lng nh?p l do t? ch?i'", "message: 'Vui lòng nhập lý do từ chối'"),
]

count = 0
for old, new in replacements:
    if old in text:
        text = text.replace(old, new)
        count += 1

path.write_text(text, encoding="utf-8", newline="\n")
print(f"Applied {count} replacement groups to {path}")
