using ZKTecoADMS.Application.DTOs.Settings;
using ZKTecoADMS.Domain.Entities;

namespace ZKTecoADMS.Application.Mappings;

public class SettingsMappingConfig : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        // Penalty Settings - Direct mapping for all penalty fields
        config.NewConfig<PenaltySetting, PenaltySettingDto>()
            .Map(dest => dest.Id, src => src.Id)
            .Map(dest => dest.LateMinutes1, src => src.LateMinutes1)
            .Map(dest => dest.LatePenalty1, src => src.LatePenalty1)
            .Map(dest => dest.LateMinutes2, src => src.LateMinutes2)
            .Map(dest => dest.LatePenalty2, src => src.LatePenalty2)
            .Map(dest => dest.LateMinutes3, src => src.LateMinutes3)
            .Map(dest => dest.LatePenalty3, src => src.LatePenalty3)
            .Map(dest => dest.EarlyMinutes1, src => src.EarlyMinutes1)
            .Map(dest => dest.EarlyPenalty1, src => src.EarlyPenalty1)
            .Map(dest => dest.EarlyMinutes2, src => src.EarlyMinutes2)
            .Map(dest => dest.EarlyPenalty2, src => src.EarlyPenalty2)
            .Map(dest => dest.EarlyMinutes3, src => src.EarlyMinutes3)
            .Map(dest => dest.EarlyPenalty3, src => src.EarlyPenalty3)
            .Map(dest => dest.RepeatCount1, src => src.RepeatCount1)
            .Map(dest => dest.RepeatPenalty1, src => src.RepeatPenalty1)
            .Map(dest => dest.RepeatCount2, src => src.RepeatCount2)
            .Map(dest => dest.RepeatPenalty2, src => src.RepeatPenalty2)
            .Map(dest => dest.RepeatCount3, src => src.RepeatCount3)
            .Map(dest => dest.RepeatPenalty3, src => src.RepeatPenalty3)
            .Map(dest => dest.ForgotCheckPenalty, src => src.ForgotCheckPenalty)
            .Map(dest => dest.UnauthorizedLeavePenalty, src => src.UnauthorizedLeavePenalty)
            .Map(dest => dest.ViolationPenalty, src => src.ViolationPenalty)
            .Map(dest => dest.CreatedAt, src => src.CreatedAt)
            .Map(dest => dest.UpdatedAt, src => src.UpdatedAt);

        config.NewConfig<UpdatePenaltySettingDto, PenaltySetting>()
            .Map(dest => dest.LateMinutes1, src => src.LateMinutes1)
            .Map(dest => dest.LatePenalty1, src => src.LatePenalty1)
            .Map(dest => dest.LateMinutes2, src => src.LateMinutes2)
            .Map(dest => dest.LatePenalty2, src => src.LatePenalty2)
            .Map(dest => dest.LateMinutes3, src => src.LateMinutes3)
            .Map(dest => dest.LatePenalty3, src => src.LatePenalty3)
            .Map(dest => dest.EarlyMinutes1, src => src.EarlyMinutes1)
            .Map(dest => dest.EarlyPenalty1, src => src.EarlyPenalty1)
            .Map(dest => dest.EarlyMinutes2, src => src.EarlyMinutes2)
            .Map(dest => dest.EarlyPenalty2, src => src.EarlyPenalty2)
            .Map(dest => dest.EarlyMinutes3, src => src.EarlyMinutes3)
            .Map(dest => dest.EarlyPenalty3, src => src.EarlyPenalty3)
            .Map(dest => dest.RepeatCount1, src => src.RepeatCount1)
            .Map(dest => dest.RepeatPenalty1, src => src.RepeatPenalty1)
            .Map(dest => dest.RepeatCount2, src => src.RepeatCount2)
            .Map(dest => dest.RepeatPenalty2, src => src.RepeatPenalty2)
            .Map(dest => dest.RepeatCount3, src => src.RepeatCount3)
            .Map(dest => dest.RepeatPenalty3, src => src.RepeatPenalty3)
            .Map(dest => dest.ForgotCheckPenalty, src => src.ForgotCheckPenalty)
            .Map(dest => dest.UnauthorizedLeavePenalty, src => src.UnauthorizedLeavePenalty)
            .Map(dest => dest.ViolationPenalty, src => src.ViolationPenalty);

        // Insurance Settings - Direct mapping for all insurance fields
        config.NewConfig<InsuranceSetting, InsuranceSettingDto>()
            .Map(dest => dest.Id, src => src.Id)
            .Map(dest => dest.BaseSalary, src => src.BaseSalary)
            .Map(dest => dest.MinSalaryRegion1, src => src.MinSalaryRegion1)
            .Map(dest => dest.MinSalaryRegion2, src => src.MinSalaryRegion2)
            .Map(dest => dest.MinSalaryRegion3, src => src.MinSalaryRegion3)
            .Map(dest => dest.MinSalaryRegion4, src => src.MinSalaryRegion4)
            .Map(dest => dest.MaxInsuranceSalary, src => src.MaxInsuranceSalary)
            .Map(dest => dest.BhxhEmployeeRate, src => src.BhxhEmployeeRate)
            .Map(dest => dest.BhxhEmployerRate, src => src.BhxhEmployerRate)
            .Map(dest => dest.BhytEmployeeRate, src => src.BhytEmployeeRate)
            .Map(dest => dest.BhytEmployerRate, src => src.BhytEmployerRate)
            .Map(dest => dest.BhtnEmployeeRate, src => src.BhtnEmployeeRate)
            .Map(dest => dest.BhtnEmployerRate, src => src.BhtnEmployerRate)
            .Map(dest => dest.UnionFeeEmployeeRate, src => src.UnionFeeEmployeeRate)
            .Map(dest => dest.UnionFeeEmployerRate, src => src.UnionFeeEmployerRate)
            .Map(dest => dest.DefaultRegion, src => src.DefaultRegion)
            .Map(dest => dest.CreatedAt, src => src.CreatedAt)
            .Map(dest => dest.UpdatedAt, src => src.UpdatedAt);

        config.NewConfig<UpdateInsuranceSettingDto, InsuranceSetting>()
            .Map(dest => dest.BaseSalary, src => src.BaseSalary)
            .Map(dest => dest.MinSalaryRegion1, src => src.MinSalaryRegion1)
            .Map(dest => dest.MinSalaryRegion2, src => src.MinSalaryRegion2)
            .Map(dest => dest.MinSalaryRegion3, src => src.MinSalaryRegion3)
            .Map(dest => dest.MinSalaryRegion4, src => src.MinSalaryRegion4)
            .Map(dest => dest.MaxInsuranceSalary, src => src.MaxInsuranceSalary)
            .Map(dest => dest.BhxhEmployeeRate, src => src.BhxhEmployeeRate)
            .Map(dest => dest.BhxhEmployerRate, src => src.BhxhEmployerRate)
            .Map(dest => dest.BhytEmployeeRate, src => src.BhytEmployeeRate)
            .Map(dest => dest.BhytEmployerRate, src => src.BhytEmployerRate)
            .Map(dest => dest.BhtnEmployeeRate, src => src.BhtnEmployeeRate)
            .Map(dest => dest.BhtnEmployerRate, src => src.BhtnEmployerRate)
            .Map(dest => dest.UnionFeeEmployeeRate, src => src.UnionFeeEmployeeRate)
            .Map(dest => dest.UnionFeeEmployerRate, src => src.UnionFeeEmployerRate)
            .Map(dest => dest.DefaultRegion, src => src.DefaultRegion);

        // Tax Settings - Direct mapping for all tax fields
        config.NewConfig<TaxSetting, TaxSettingDto>()
            .Map(dest => dest.Id, src => src.Id)
            .Map(dest => dest.PersonalDeduction, src => src.PersonalDeduction)
            .Map(dest => dest.DependentDeduction, src => src.DependentDeduction)
            .Map(dest => dest.TaxBracket1Max, src => src.TaxBracket1Max)
            .Map(dest => dest.TaxRate1, src => src.TaxRate1)
            .Map(dest => dest.TaxBracket2Max, src => src.TaxBracket2Max)
            .Map(dest => dest.TaxRate2, src => src.TaxRate2)
            .Map(dest => dest.TaxBracket3Max, src => src.TaxBracket3Max)
            .Map(dest => dest.TaxRate3, src => src.TaxRate3)
            .Map(dest => dest.TaxBracket4Max, src => src.TaxBracket4Max)
            .Map(dest => dest.TaxRate4, src => src.TaxRate4)
            .Map(dest => dest.TaxBracket5Max, src => src.TaxBracket5Max)
            .Map(dest => dest.TaxRate5, src => src.TaxRate5)
            .Map(dest => dest.TaxBracket6Max, src => src.TaxBracket6Max)
            .Map(dest => dest.TaxRate6, src => src.TaxRate6)
            .Map(dest => dest.TaxRate7, src => src.TaxRate7)
            .Map(dest => dest.CreatedAt, src => src.CreatedAt)
            .Map(dest => dest.UpdatedAt, src => src.UpdatedAt);

        config.NewConfig<UpdateTaxSettingDto, TaxSetting>()
            .Map(dest => dest.PersonalDeduction, src => src.PersonalDeduction)
            .Map(dest => dest.DependentDeduction, src => src.DependentDeduction)
            .Map(dest => dest.TaxBracket1Max, src => src.TaxBracket1Max)
            .Map(dest => dest.TaxRate1, src => src.TaxRate1)
            .Map(dest => dest.TaxBracket2Max, src => src.TaxBracket2Max)
            .Map(dest => dest.TaxRate2, src => src.TaxRate2)
            .Map(dest => dest.TaxBracket3Max, src => src.TaxBracket3Max)
            .Map(dest => dest.TaxRate3, src => src.TaxRate3)
            .Map(dest => dest.TaxBracket4Max, src => src.TaxBracket4Max)
            .Map(dest => dest.TaxRate4, src => src.TaxRate4)
            .Map(dest => dest.TaxBracket5Max, src => src.TaxBracket5Max)
            .Map(dest => dest.TaxRate5, src => src.TaxRate5)
            .Map(dest => dest.TaxBracket6Max, src => src.TaxBracket6Max)
            .Map(dest => dest.TaxRate6, src => src.TaxRate6)
            .Map(dest => dest.TaxRate7, src => src.TaxRate7);
    }
}
