import { Card } from '@/components/ui/card';
import { FileText } from 'lucide-react';

export function PayslipEmptyState() {
  return (
    <Card className="p-12">
      <div className="flex flex-col items-center justify-center text-center space-y-4">
        <FileText className="w-16 h-16 text-muted-foreground" />
        <div>
          <h3 className="text-lg font-semibold">No Payslips Found</h3>
          <p className="text-muted-foreground mt-2">
            You don't have any payslips yet. They will appear here once generated by your manager.
          </p>
        </div>
      </div>
    </Card>
  );
}
