namespace ZKTecoADMS.Api.Services;

/// <summary>
/// Đường dẫn menu đúng như trên app (nhóm › tên menu) theo mã chức năng — sinh từ
/// flutter_client/lib/screens/main_layout.dart + settings_hub_catalog.dart (scripts/gen_ai_menu_map.py).
/// Đổi tên / nhóm menu trên app thì chạy lại script sinh file này.
/// </summary>
public static class AiAssistantMenuMap
{
    public static readonly IReadOnlyDictionary<string, string> Paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Home"] = "Tổng quan › Trang chủ",
        ["Notification"] = "Tổng quan › Thông báo",
        ["Dashboard"] = "Tổng quan › Tổng quan",
        ["Employee"] = "Hồ sơ nhân sự › Hồ sơ nhân sự",
        ["DeviceUser"] = "Chấm công › Nhân sự chấm công",
        ["Department"] = "Hồ sơ nhân sự › Phòng ban",
        ["Leave"] = "Chấm công › Nghỉ phép",
        ["SalarySettings"] = "Hồ sơ nhân sự › Thiết lập lương",
        ["Attendance"] = "Chấm công › Chấm công thô",
        ["WorkSchedule"] = "Chấm công › Ca làm việc",
        ["AttendanceSummary"] = "Báo cáo nhân sự › Tổng hợp chấm công",
        ["AttendanceByShift"] = "Báo cáo nhân sự › Tổng hợp chấm công theo ca",
        ["LateEarlyReport"] = "Báo cáo nhân sự › Đi trễ / Về sớm",
        ["TravelHoursReport"] = "Báo cáo nhân sự › Báo cáo đi đường",
        ["AttendanceApproval"] = "Chấm công › Duyệt chấm công",
        ["ScheduleApproval"] = "Chấm công › Duyệt lịch làm việc",
        ["Payslip"] = "Báo cáo nhân sự › Phiếu lương",
        ["Payroll"] = "Báo cáo nhân sự › Tổng hợp lương",
        ["MobileDeviceRegistration"] = "Chấm công › Đăng ký chấm công Mobile",
        ["MobileAttendance"] = "Chấm công › Chấm công Mobile",
        ["Meal"] = "Quản lý Vận hành › Chấm cơm",
        ["BonusPenalty"] = "Tài chính › Thưởng phạt",
        ["AdvanceRequests"] = "Tài chính › Ứng lương",
        ["BusinessTripExpense"] = "Tài chính › Công tác phí",
        ["CashTransaction"] = "Tài chính › Thu chi",
        ["Asset"] = "Quản lý Vận hành › Tài sản",
        ["Task"] = "Quản lý Vận hành › Công việc",
        ["Communication"] = "Quản lý Vận hành › Truyền thông",
        ["KPI"] = "Quản lý Vận hành › KPI",
        ["Production"] = "Quản lý Vận hành › Sản lượng",
        ["Feedback"] = "Quản lý Vận hành › Phản ánh / Ý kiến",
        ["FieldCheckIn"] = "Quản lý Vận hành › Bản đồ nhân sự",
        ["PosProducts"] = "POS › Hàng hóa",
        ["PosSell"] = "POS › Bán hàng",
        ["PosQuotes"] = "POS › Báo giá",
        ["PosPrintTemplates"] = "POS › Mẫu in báo giá",
        ["PosKds"] = "POS › Màn hình bếp (KDS)",
        ["PosSaleOrders"] = "POS › Đơn hàng",
        ["PosQrOrder"] = "POS › Menu QR / Online",
        ["PosSaleReturns"] = "POS › Trả hàng bán",
        ["PosBooking"] = "POS › Đặt lịch",
        ["PosCustomers"] = "POS › Khách hàng POS",
        ["PosWarranty"] = "POS › Bảo hành POS",
        ["PosPurchaseReceipts"] = "POS › Nhà cung cấp",
        ["PosPurchaseReturns"] = "POS › Trả hàng nhập",
        ["PosStockCounts"] = "POS › Kiểm kho",
        ["PosDamageIssues"] = "POS › Xuất hủy",
        ["PosInternalUseIssues"] = "POS › Xuất dùng nội bộ",
        ["PosSalesReport"] = "Báo cáo kinh doanh › Báo cáo POS",
        ["AttendanceReport"] = "Báo cáo nhân sự › Báo cáo chấm công",
        ["PenaltyReport"] = "Báo cáo nhân sự › Báo cáo phạt",
        ["CashReport"] = "Báo cáo kinh doanh › Báo cáo thu chi",
        ["AdvanceReport"] = "Báo cáo nhân sự › Báo cáo ứng lương",
        ["BusinessTripReport"] = "Báo cáo nhân sự › Báo cáo công tác phí",
        ["LeaveReport"] = "Báo cáo nhân sự › Báo cáo nghỉ phép",
        ["AssetReport"] = "Báo cáo kinh doanh › Báo cáo tài sản",
        ["SettingsHub"] = "Cài đặt › Thiết lập SBOX",
        ["Settings"] = "Cài đặt › Cài đặt",
        ["SystemAdmin"] = "Cài đặt › Quản trị hệ thống",
        ["PenaltyTickets"] = "Tài chính › Phiếu phạt",
        ["NotificationSettings"] = "Cài đặt › Thiết lập thông báo",
        ["ShiftSwap"] = "Chấm công › Đổi ca làm việc",
        ["HrAnalyticsReport"] = "Báo cáo nhân sự › Báo cáo phân tích",
        ["ActivityLog"] = "Cài đặt › Lịch sử thao tác",
        ["Branch"] = "Thiết lập SBOX › Chi nhánh",
        ["SystemSettings"] = "Thiết lập SBOX › Tham số hệ thống",
        ["ShiftSetup"] = "Thiết lập SBOX › Ca làm việc",
        ["Holiday"] = "Thiết lập SBOX › Ngày lễ",
        ["Device"] = "Thiết lập SBOX › Máy chấm công",
        ["Allowance"] = "Thiết lập SBOX › Phụ cấp",
        ["PenaltySetup"] = "Thiết lập SBOX › Mức phạt",
        ["Insurance"] = "Thiết lập SBOX › Bảo hiểm",
        ["Tax"] = "Thiết lập SBOX › Thuế TNCN",
        ["ProductSalary"] = "Thiết lập SBOX › Lương sản phẩm",
        ["PosCustomerDisplay"] = "Thiết lập SBOX › Màn hình phụ",
        ["BankAccount"] = "Thiết lập SBOX › Tài khoản nhận tiền",
        ["PosEInvoice"] = "Thiết lập SBOX › Hóa đơn điện tử",
        ["PosShipping"] = "Thiết lập SBOX › Đơn vị giao hàng",
        ["PosPrinters"] = "Thiết lập SBOX › Máy in",
        ["UserManagement"] = "Thiết lập SBOX › Tài khoản nhân viên",
        ["Role"] = "Thiết lập SBOX › Phân quyền",
        ["AIGemini"] = "Thiết lập SBOX › Trợ lý AI",
    };
}
