#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Final cleanup: double-corruption + U+FFFD lines."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = [
    ROOT / "flutter_client/lib/screens/device_users_screen.dart",
    ROOT / "flutter_client/lib/screens/attendance/payroll_summary_tab.dart",
]

R = "\ufffd"  # replacement char

PAIRS = [
    # double-fix from prior passes
    ("đăng kýý", "đăng ký"),
    ("Đăng kýý", "Đăng ký"),
    ("đăng ký·", "đăng ký"),
    ("Đăng ký·", "Đăng ký"),
    ("đăng ký ", "đăng ký "),
    ("cóhưa", "chưa"),
    ("có hưa", "chưa"),
    ("Quản trỏ viên", "Quản trị viên"),
    ("Quản trỏ vi", "Quản trị vi"),
    ("Người dng", "Người dùng"),
    ("dng getDevices", "dùng getDevices"),
    (f"v{R}ng", "vòng"),
    ("giay", "giây"),
    (f"gi{R}y", "giây"),
    (f"H{R}y", "Hãy"),
    ("nh?n", "nhấn"),
    (" nao ", " nào "),
    (" nao.", " nào."),
    (" nao,", " nào,"),
    (" nao'", " nào'"),
    (f"n{R}o", "nào"),
    (f"T{R}m", "Tìm"),
    (f"th{R}ng", "thông"),
    ("Thử tự khóa khác", "Thử từ khóa khác"),
    (f"Thẻ tự kh{R}a kh{R}c", "Thử từ khóa khác"),
    (f"V{R}n tay", "Vân tay"),
    (f"Danh s{R}ch", "Danh sách"),
    (f"ng{R}n", "ngón"),
    (f"tr{R}ng", "trùng"),
    (f"b{R}n tay", "bàn tay"),
    (f"C{R}i", "Cái"),
    ("TAY TRÁI", "TAY TRÁI"),
    (f"TAY TR{R}I", "TAY TRÁI"),
    (f"C{R}c ng", "Các ng"),
    (f"L{R}ng b", "Lòng b"),
    (f"Thống kê{R}", "Thống kê"),
    ("Ch· thích màu", "Chú thích màu"),
    (f"Ch· th{R}ch m{R}u", "Chú thích màu"),
    (f"h{R}nh động", "hành động"),
    (f"hnh đểng", "hành động"),
    (f"X{R}c nh", "Xác nh"),
    ("Xác nh?n", "Xác nhận"),
    (f"bằng c{R}ch", "bằng cách"),
    (f"bộng c{R}ch", "bằng cách"),
    (f"tr{R}ng th", "trạng th"),
    (f"trỏng th{R}i", "trạng thái"),
    (f"thành c{R}ng", "thành công"),
    (f"Thửng b{R}o", "Thông báo"),
    (f"Qu{R} kh{R}ch", "Quý khách"),
    (f"vui l{R}ng", "vui lòng"),
    (f"{R}Đồng bộ", "Đồng bộ"),
    (f"Khu{R}n mặt", "Khuôn mặt"),
    (f"{R}đường", "đường"),
    (f"v{R}o", "vào"),
    (f"ch{R}nh", "chính"),
    (f"d{R}ng", "dùng"),
    (f"dialog ch{R}nh", "dialog chính"),
    (f"v{R} refresh", "và refresh"),
    (f"kh{R}ch", "khách"),
    (f"l{R}ng", "lòng"),
    (f"m{R}u", "màu"),
    (f"tr{R}n", "trên"),
    (f" ? tr{R}n", " — trên"),
    (f"Nh{R}n sự", "Nhân sự"),
    (f"Quản tr{R} vi", "Quản trị vi"),
    (f"bộng d", "bảng d"),
    (f"ch{R}p", "chụp"),
    (f"Chọnh s", "Chỉnh s"),
    (f"C{R}p nh", "Cập nh"),
    (f"{R}ng bộ", "Đồng bộ"),
    (f"vo m", "vào m"),
    (f"th{R}ng tin", "thông tin"),
    (f"t{R} Employee", "từ Employee"),
    (f"th{R}nh c", "thành c"),
    (f"thể đ", "thể đ"),
    (f"{R}i liên", "Đổi liên"),
    (f"khc đ", "khác đ"),
    (f"tm ki", "tìm ki"),
    (f"ph{R}ng ban", "phòng ban"),
    (f"ph· h", "phù h"),
    (f"cn nh", "còn nh"),
    (f"M{R}:", "Mã:"),
    (f"ti{R}n tr", "tiến tr"),
    (f"S{R} lần", "Số lần"),
    (f"th{R}nh c", "thành c"),
    (f"th{R}ng c", "thường c"),
    (f"cu tr", "cũ tr"),
    (f"{R}i m", "Đợi m"),
    (f"đặt ng", "đặt ng"),
    (f"l{R}n m", "lên m"),
    (f"tr{R}ng th", "trạng th"),
    (f"th{R}i gian", "thời gian"),
    (f"ch{R} qu", "chờ qu"),
    (f"c{R}m bi", "cảm bi"),
    (f"nh{R}n được", "nhận được"),
    (f"th{R} l", "thử l"),
    (f"H{R}t th", "Hết th"),
    (f"gi{R} y", "giữ y"),
    (f"ho{R}n t", "hoàn t"),
    (f"nhn th", "nhìn th"),
    (f"Kh{R}n m", "Khuôn m"),
    (f"luu tr", "lưu tr"),
    (f"Thửng b", "Thông b"),
    (f"h{R} tr", "hỗ tr"),
    (f"đăng ký tr", "đăng ký tr"),
    (f"m{R} màn", "mở màn"),
    (f"sau đã", "sau đó"),
    (f"v? h", "về h"),
    (f"nh{R}n được", "nhận được"),
    (f"r{R}i th", "rồi th"),
    (f"thể g", "thể g"),
    (f"Chọn máy để", "Chọn máy để"),
    (f"để lấy", "để lấy"),
    (f"đểi m", "đợi m"),
    (f"Trỏ v", "Trỏ v"),
    (f"c{R}a m", "của m"),
    (f"?n di", "ẩn di"),
    (f"tự c", "tự c"),
    (f"mu{R}n", "muốn"),
    (f"b{R} comment", "bỏ comment"),
    (f"ph{R}a d", "phía d"),
    (f"{R} tr", "để tr"),
    (f"s{R} tự", "sẽ tự"),
    (f"Nguy{R}n", "Nguyễn"),
    (f"b{R}n d", "bên d"),
    (f"thể l", "thể l"),
    (f"Chọn & s", "Chọn & s"),
    (f"s{R}p x", "sắp x"),
    (f"M{R}c đ", "Mặc đ"),
    (f"C{R}t c", "Cột c"),
    (f"chuy{R}n", "chuyển"),
    (f"K{R}o đ", "Kéo đ"),
    (f"{R}p d", "Áp d"),
    # payroll
    (f" đểnh nghia", " định nghĩa"),
    (f"c{R}t b", "cột b"),
    (f"dang ho", "đang ho"),
    (f"b{R}ng l", "bảng l"),
    (f"b{R} lo", "bỏ lo"),
    (f"từng h{R}p", "tổng hợp"),
    (f"K{R} to", "Kế to"),
    (f"Gi{R}m đ", "Giám đ"),
    (f"Luong theo c", "Lương theo c"),
    (f"PC c{R} đ", "PC cố đ"),
    (f"theo ng{R}y", "theo ngày"),
    (f"Từng PC", "Tổng PC"),
    (f"S{R}n lu", "Sản lu"),
    (f"K{R} tên", "Ký tên"),
    (f"Ch{R} d", "Chỉ d"),
    (f"mn cha", "màn cha"),
    (f"tr{R}nh qu", "tránh qu"),
    (f"h{R}ng tr", "hàng tr"),
    (f"ch{R} manager", "chỉ manager"),
    (f"Lo{R}i b", "Loại b"),
    (f"tr{R}nh qu", "tránh qu"),
    (f"B{R}n ch", "Bản ch"),
    (f"ch{R}p ch", "chấp ch"),
    (f"luu đ", "lưu đ"),
    (f"ch{R}t phi", "chốt phi"),
    (f"V{R}o", "Vào"),
    (f"Không dng", "Không dùng"),
    (f"p đểng m", "Áp dụng m"),
    (f"co s{R}", "cơ sở"),
    (f"tải thi", "tối thi"),
    (f"lu{R}t Vi", "luật Vi"),
    (f"c{R}ng thu", "công thu"),
    (f"mn Thi", "màn Thi"),
    (f"m{R}c c", "mức c"),
    (f"th{R}c nh", "thực nh"),
    (f"Ch{R}m c", "Chấm c"),
    (f"c{R}ng n", "công n"),
    (f"thu{R}t to", "thuật to"),
    (f"tênh l", "tính l"),
    (f"hon th", "hoàn th"),
    (f"m{R}c th", "mức th"),
    (f"B{R} qua", "Bỏ qua"),
    (f"gi{R} th", "giữ th"),
    (f"on ph", "Đoàn ph"),
    (f"chua d", "chưa đ"),
    (f"m{R}c d", "mức đ"),
    (f"h{R} s", "hệ s"),
    (f"NL{R} d", "NLĐ"),
    (f"Nhn vi", "Nhân vi"),
    (f"ph{R}m vi", "phạm vi"),
    (f"Ch{R}t l", "Chốt l"),
    (f"K{R}:", "Kỳ:"),
    (f"Phi{R}u", "Phiếu"),
    (f"c{R}ng k", "công k"),
    (f"c{R}p nh", "cập nh"),
    (f"Xc nh", "Xác nh"),
    (f"h{R}p l", "hợp l"),
    (f"thi{R}u", "thiếu"),
    (f"pha app", "phía app"),
    (f"Đang ch{R}t", "Đang chốt"),
    (f"để li", "dữ li"),
    (f"Xu{R}t", "Xuất"),
    (f"luu v", "lưu v"),
    (f"Tải v{R}", "Tải về"),
    (f"TừNG C{R}NG", "TỔNG CỘNG"),
    (f"B{R}NG T", "BẢNG T"),
    (f"ghi r{R}", "ghi rõ"),
    (f"h{R} tên", "họ tên"),
    (f"luu v{R}", "lưu vào"),
    (f"?nh/", "ảnh/"),
    (f"Chi ti{R}t", "Chi tiết"),
    (f"C{R}ng ch", "Công ch"),
    (f"Ngy ", "Ngày "),
    (f"ng{R}y", "ngày"),
    (f"Tang ca", "Tăng ca"),
    (f"thu{R}ng", "thường"),
    (f"ngy l", "ngày l"),
    (f"i tr", "Đi tr"),
    (f"Luong h", "Lương h"),
    (f"Ph{R} c", "Phụ c"),
    (f"M{R}c d", "Mức đ"),
    (f"b{R}o hi", "ảo hi"),
    (f"TH{R}C NH", "THỰC NH"),
    (f"tênh to", "tính to"),
    (f"kho{R}ng th", "khoảng th"),
    (f"Th{R}ng n", "Tháng n"),
    (f"Tu{R}n n", "Tuần n"),
    (f"H{R}m n", "Hôm n"),
    (f"Ty ch", "Tùy ch"),
    (f"Ph{R}ng ban", "Phòng ban"),
    (f"Từng l", "Tổng l"),
    (f"Ngy c", "Ngày c"),
    (f"ton c", "toàn c"),
    (f"d{R}ng", "dòng"),
    (f"ton m", "toàn m"),
    (f"Thoút ch", "Thoát ch"),
    (f"chi ti{R}t", "chi tiết"),
    (f"đểy đ", "đầy đ"),
    (f"Không tm", "Không tìm"),
    (f"Không c{R}n", "Không còn"),
    # remove stray replacement chars in known words
    (f"đăng ký{R}", "đăng ký"),
    (f"Đăng ký{R}", "Đăng ký"),
    (f"đăng ký{R}:", "đăng ký:"),
    (f"đăng ký{R},", "đăng ký,"),
    (f"đăng ký{R}.", "đăng ký."),
    (f"đăng ký{R} ", "đăng ký "),
    (f"đăng ký{R}\n", "đăng ký\n"),
    (f"đăng kýý{R}", "đăng ký"),
    (f"đăng kýý", "đăng ký"),
    (f"Đăng kýý", "Đăng ký"),
    (f"đăng ký·", "đăng ký"),
    (f"Đăng ký·", "Đăng ký"),
    (f"v· ", "và "),
    (f" v· ", " và "),
    (f"ký· ", "ký "),
    (f"· v", " v"),
    (f"· c", " c"),
    (f"· t", " t"),
    (f"· k", " k"),
    (f"· h", " h"),
    (f"· n", " n"),
    (f"· g", " g"),
    (f"· d", " d"),
    (f"· m", " m"),
    (f"· ", " "),
]

def main():
    for path in FILES:
        text = path.read_text(encoding="utf-8")
        before = text.count(R)
        for good, bad in sorted(PAIRS, key=lambda x: -len(x[1])):
            if bad and good != bad:
                text = text.replace(bad, good)
        # strip remaining lone replacement chars between letters (last resort)
        import re
        text = re.sub(
            rf"([\w]){R}([\w])",
            lambda m: m.group(1) + m.group(2),
            text,
        )
        path.write_text(text, encoding="utf-8")
        after = text.count(R)
        print(f"{path.name}: U+FFFD {before} -> {after}, ?-broken: {text.count('nh?n')}")


if __name__ == "__main__":
    main()
