#!/usr/bin/env python3
"""Attempt to fix corrupted Vietnamese strings in device_users_screen.dart."""
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "flutter_client/lib/screens/device_users_screen.dart"

# Known irreversible ? replacements (literal 0x3F in source)
LITERAL_FIXES = {
    "Thi?t b?": "Thiết bị",
    "M? th?": "Mã thẻ",
    "M?t kh?u": "Mật khẩu",
    "quy?n": "quyền",
    "S?a tên": "Sửa tên",
    "m? th?": "mã thẻ",
    "m?t kh?u": "mật khẩu",
    "Qu?n lý": "Quản lý",
    "vân tay": "vân tay",
    "d?u vân tay": "dấu vân tay",
    "khuôn m?t": "khuôn mặt",
    "ngu?i dùng": "người dùng",
    "Ngu?i dùng": "Người dùng",
    "Qu?n tr? viên": "Quản trị viên",
    "qu?n tr? viên": "quản trị viên",
    "Ch?n": "Chọn",
    "ch?n": "chọn",
    "thi?t b?": "thiết bị",
    "Thi?t b?": "Thiết bị",
    "Kh?ng": "Không",
    "kh?ng": "không",
    "th?": "thẻ",
    "Th?": "Thẻ",
    "t?i": "tải",
    "T?i": "Tải",
    "d? li?u": "dữ liệu",
    "danh sách": "danh sách",
    "nhân viên": "nhân viên",
    "nhân s?": "nhân sự",
    "Nhân s?": "Nhân sự",
    "máy ch?m công": "máy chấm công",
    "ch?m công": "chấm công",
    "liên k?t": "liên kết",
    "Liên k?t": "Liên kết",
    "Chua": "Chưa",
    "chua": "chưa",
    "du?c": "được",
    "k?t n?i": "kết nối",
    "H?y": "Hãy",
    "h?y": "hãy",
    "L?i": "Lỗi",
    "l?i": "lỗi",
    "Ki?m tra": "Kiểm tra",
    "ki?m tra": "kiểm tra",
    "xu?t": "xuất",
    "Xu?t": "Xuất",
    "Hi?n th?": "Hiển thị",
    "hi?n th?": "hiển thị",
    "B? l?c": "Bộ lọc",
    "b? l?c": "bộ lọc",
    "T?ng quan": "Tổng quan",
    "t?ng quan": "tổng quan",
    "T?t c?": "Tất cả",
    "t?t c?": "tất cả",
    "tr?ng thái": "trạng thái",
    "Tr?ng thái": "Trạng thái",
    "th?t b?i": "thất bại",
    "th? khóa": "từ khóa",
    "T? khóa": "Từ khóa",
    "G?n": "Gán",
    "g?n": "gán",
    "v?i": "với",
    "V?i": "Với",
    "h? th?ng": "hệ thống",
    "H? th?ng": "Hệ thống",
    "G?i": "Gửi",
    "g?i": "gửi",
    "l?nh": "lệnh",
    "L?nh": "Lệnh",
    "d?ng b?": "đồng bộ",
    "Đ?ng b?": "Đồng bộ",
    "đ?ng b?": "đồng bộ",
    "ho?c": "hoặc",
    "Ho?c": "Hoặc",
    "dang": "đang",
    "Đang": "Đang",
    "đang": "đang",
    "Đ?i": "Đổi",
    "đ?i": "đổi",
    "X?a": "Xóa",
    "x?a": "xóa",
    "kh?i": "khỏi",
    "Kh?i": "Khỏi",
    "Thêm": "Thêm",
    "thêm": "thêm",
    "Ngón": "Ngón",
    "ngón": "ngón",
    "tr?": "trỏ",
    "Tr?": "Trỏ",
    "gi?a": "giữa",
    "Gi?a": "Giữa",
    "út": "út",
    "áp": "áp",
    "t?": "tự",
    "T?": "Tự",
    "sinh": "sinh",
    "d?u": "dấu",
    "D?u": "Dấu",
    "c?n": "cần",
    "C?n": "Cần",
    "quét": "quét",
    "Quét": "Quét",
    "l?n": "lần",
    "L?n": "Lần",
    "thành công": "thành công",
    "Thành công": "Thành công",
    "chi nhánh": "chi nhánh",
    "Chi nhánh": "Chi nhánh",
    "tru?c": "trước",
    "Tru?c": "Trước",
    "sau": "sau",
    "ph?i": "phải",
    "Ph?i": "Phải",
    "trái": "trái",
    "Trái": "Trái",
    "cái": "cái",
    "Cái": "Cái",
    "áp út": "áp út",
    "Nh?p": "Nhập",
    "nh?p": "nhập",
    "bên du?i": "bên dưới",
    "không d?u": "không dấu",
    "có d?u": "có dấu",
    "Vui lòng": "Vui lòng",
    "vui lòng": "vui lòng",
    "Refresh": "Refresh",
    "n?u": "nếu",
    "N?u": "Nếu",
    "th?y": "thấy",
    "Th?y": "Thấy",
    "user": "user",
    "User": "User",
    "PIN": "PIN",
    "ID": "ID",
}

# U+FFFD context fixes (order matters — longer first)
REPLACEMENT_FIXES = [
    ("Không thể tải dữ liệu", "Khng th? ti d? li?u"),
    ("Không thể tải danh sách user", "Khng th? ti danh sch user"),
    ("Chọn máy để tải danh sách nhân viên", "Chn my d ti danh sch nhn vin"),
    ("Đang gửi lệnh tải nhân viên từ máy...", "ang gi lnh ti nhn vin t my..."),
    ("Đã gửi lệnh tải nhân viên. Đang chờ dữ liệu từ máy...", " gi lnh ti nhn vin. ang ch d liu t my..."),
    ("Đã tải", " ti"),
    ("nhân viên từ máy!", "nhn vin t my!"),
    ("Lệnh đã gửi. Hãy nhấn Refresh nếu chưa thấy dữ liệu.", "Lnh  gi. Hy nhn Refresh nu chua thy d liu."),
    ("Không thể gửi lệnh đến máy chấm công", "Khng th? gi lnh dn my chm cng"),
    ("Chưa có thiết bị nào được kết nối", "Chua c thi?t b? no du?c k?t n?i"),
    ("Chưa có hồ sơ nhân sự nào", "Chua c h? so nhn s? no"),
    ("Tải hồ sơ nhân sự xuống máy", "Ti h? so nhn s? xu?ng my"),
    ("Chọn thiết bị *", "Chn thi?t b? *"),
    ("Vui lòng chọn thiết bị để xem nhân viên", "Vui lng chn thi?t b? d xem nhn vin"),
    ("nhân viên chưa có trên máy chấm công", "nhn vin chua c trn my chm cng"),
    ("Chọn tất cả", "Chn tt c?"),
    ("Chọn thiết bị để xem danh sách nhân viên", "Chn thi?t b? d xem danh sch nhn vin"),
    ("Tất cả nhân viên đã có trên máy chấm công", "Tt c? nhn vin  c trn my chm cng"),
    ("Tải", "Ti"),
    ("nhân viên", "nhn vin"),
    ("Đang tải", "ang ti"),
    ("xuống máy", "xu?ng my"),
    ("thất bại", "th?t b?i"),
    ("Nhân viên tải thất bại", "Nhn vin ti th?t b?i"),
    ("Không có user đã liên kết", "Khng c user  lin k?t"),
    ("Liên kết user máy chấm công với hồ sơ nhân sự", "Lin k?t user my chm cng vi h? so nhn s?"),
    ("Không có user chưa liên kết", "Khng c user chua lin k?t"),
    ("Tất cả user trên máy đã được liên kết nhân sự", "Tt c? user trn my  du?c lin k?t nhn s?"),
    ("Không có user trên thiết bị online", "Khng c user trn thi?t b? online"),
    ("Chưa có thiết bị online hoặc chưa có user trên các máy đang kết nối", "Chua c thi?t b? online ho?c chua c user trn cc my dang k?t n?i"),
    ("Thêm user hoặc đồng bộ từ nhân viên", "Thm user ho?c d?ng b? t nhn vin"),
    ("nhân viên ·", "nhn vin "),
    ("thiết bị", "thi?t b?"),
    ("Đang lọc", "ang l?c"),
    ("Bộ lọc", "B? l?c"),
    ("Tổng quan", "T?ng quan"),
    ("Đang tải...", "ang ti..."),
    ("Chưa có thiết bị", "Chua c thi?t b?"),
    ("Hãy kết nối máy chấm công trước", "Hy k?t n?i my chm cng tru?c"),
    ("Không tìm thấy user", "Khng tm thy user"),
    ("Thử từ khóa khác hoặc bộ lọc tổng quan", "Th? t kh?a khc ho?c b? l?c t?ng quan"),
    ("Chưa có chi nhánh", "Chua c chi nhnh"),
    ("Mã thẻ", "M th?"),
    ("Liên kết NV", "Lin k?t NV"),
    ("Chưa liên kết", "Chua lin k?t"),
    ("Sửa tên, mã thẻ, mật khẩu, quyền", "Sa tn, m th?, m?t kh?u, quy?n"),
    ("Quản lý vân tay", "Qu?n l vntay"),
    ("Thêm, xóa dấu vân tay", "Thm, xa d?u vntay"),
    ("Quản lý khuôn mặt", "Qu?n l khun m?t"),
    ("Thêm, xóa khuôn mặt", "Thm, xa khu?n m?t"),
    ("Đổi liên kết nhân viên", "?i lin k?t nhn vin"),
    ("Gán với nhân sự", "Gn vi nhn s?"),
    ("Đang liên kết", "ang lin k?t"),
    ("Liên kết với nhân viên trong hệ thống", "Lin k?t vi nhn vin trong h? th?ng"),
    ("Xóa người dùng", "Xa ngu?i dng"),
    ("Xóa khỏi máy chấm công", "Xa kh?i my chm cng"),
    ("·", ""),
]


def main():
    text = PATH.read_text(encoding="utf-8", errors="replace")
    original = text

    # Fix U+FFFD sequences by pattern (use regex with )
    import re

    # Common single-char replacements for 
    char_map = {
        "á": "",
        "à": "",
        "ả": "",
        "ã": "",
        "ạ": "",
        "ă": "",
        "â": "",
        "đ": "",
        "ê": "",
        "é": "",
        "è": "",
        "ẻ": "",
        "ẽ": "",
        "ẹ": "",
        "í": "",
        "ì": "",
        "ỉ": "",
        "ĩ": "",
        "ị": "",
        "ó": "",
        "ò": "",
        "ỏ": "",
        "õ": "",
        "ọ": "",
        "ô": "",
        "ơ": "",
        "ú": "",
        "ù": "",
        "ủ": "",
        "ũ": "",
        "ụ": "",
        "ư": "",
        "ý": "",
        "ỳ": "",
        "ỷ": "",
        "ỹ": "",
        "ỵ": "",
        "ế": "",
        "ề": "",
        "ể": "",
        "ễ": "",
        "ệ": "",
        "ố": "",
        "ồ": "",
        "ổ": "",
        "ỗ": "",
        "ộ": "",
        "ớ": "",
        "ờ": "",
        "ở": "",
        "ỡ": "",
        "ợ": "",
        "ứ": "",
        "ừ": "",
        "ử": "",
        "ữ": "",
        "ự": "",
        "ấ": "",
        "ầ": "",
        "ẩ": "",
        "ẫ": "",
        "ậ": "",
        "ắ": "",
        "ằ": "",
        "ẳ": "",
        "ẵ": "",
        "ặ": "",
    }

    # Apply literal ? fixes (longest keys first)
    for bad, good in sorted(LITERAL_FIXES.items(), key=lambda x: -len(x[0])):
        text = text.replace(bad, good)

    # Replace remaining U+FFFD with heuristic - can't auto-fix all
    if "\ufffd" in text:
        # Try cp1252 roundtrip on lines with replacement char
        lines = text.split("\n")
        fixed_lines = []
        for line in lines:
            if "\ufffd" in line:
                try:
                    recovered = line.encode("utf-8").decode("latin-1").encode("latin-1").decode("utf-8")
                    if "\ufffd" not in recovered and recovered.count("?") < line.count("\ufffd"):
                        line = recovered
                except Exception:
                    pass
            fixed_lines.append(line)
        text = "\n".join(fixed_lines)

    if text != original:
        PATH.write_text(text, encoding="utf-8")
        print(f"Updated {PATH}")
        print(f"Remaining ?: {text.count('?')} (many are null-safe)")
        print(f"Remaining U+FFFD: {text.count(chr(0xFFFD))}")
    else:
        print("No changes made")


if __name__ == "__main__":
    main()
