"""Sinh lib/utils/pos_commercial_templates.g.dart (flutter_client + flutter_pos)
từ src/ZKTecoADMS.Api/PrintTemplates/A4/*.html — một nguồn mẫu A4 cho server và app.

Chạy lại mỗi khi sửa file .html:  python scripts/gen_commercial_templates.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "ZKTecoADMS.Api" / "PrintTemplates" / "A4"
TARGETS = [
    ROOT / "flutter_client" / "lib" / "utils" / "pos_commercial_templates.g.dart",
    ROOT / "flutter_pos" / "lib" / "utils" / "pos_commercial_templates.g.dart",
]
NAMES = {
    "Quote": "posA4QuoteHtml",
    "Contract": "posA4ContractHtml",
    "Acceptance": "posA4AcceptanceHtml",
    "Handover": "posA4HandoverHtml",
    "PaymentRequest": "posA4PaymentRequestHtml",
}


def main() -> None:
    out = [
        "// GENERATED by scripts/gen_commercial_templates.py — KHÔNG sửa tay.",
        "// Nguồn: src/ZKTecoADMS.Api/PrintTemplates/A4/*.html (dùng chung với API).",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
    ]
    for stem, ident in NAMES.items():
        html = (SRC / f"{stem}.html").read_text(encoding="utf-8").strip()
        if "'''" in html:
            raise SystemExit(f"{stem}.html chứa ''' — không nhúng được raw string")
        out.append(f"const {ident} = r'''{html}''';")
        out.append("")
    text = "\n".join(out)
    for t in TARGETS:
        if t.parent.exists():
            t.write_text(text, encoding="utf-8", newline="\n")
            print("wrote", t.relative_to(ROOT))


if __name__ == "__main__":
    main()
